### ISSUE TITLE
Undocumented BC break about migration generator

### ISSUE THREAD

**Issue by VincentLanglet** [doctrine/migrations#1000]
#### Summary

The migration generator does not replace the same variable between 2.x and 3.0.
It leads to a BC break non documented if you use custom template.

#### Previous behavior

```
final class Version<version>
```
was correctly replaced.

#### Current behavior

Now it's not. We have to write
```
final class <classname>
```

**Comment by greg0ire** [comment]
@tarlepp documented it with https://github.com/doctrine/DoctrineMigrationsBundle/pull/334, but on the bundle repository.

**Comment by VincentLanglet** [comment]
I think it can be enough on the bundle.

But I missed it because I looked at the default branch UPGRADE file: https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/UPGRADE.md

**Comment by greg0ire** [comment]
Right, I will do an up-merge PR

**Comment by VincentLanglet** [comment]
Ok, I close this then :)
