### ISSUE TITLE
Existing entries in the migrations table don't get automatically updated

### ISSUE THREAD

**Issue by simivar** [doctrine/migrations#1002]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary
I've updated from 2.2.1 to 3.0.0. [UPGRADE.md](https://github.com/doctrine/migrations/blob/master/UPGRADE.md) states that:
> existing entries in the migrations table will be automatically updated

but it wasn't the case for me. 

#### Current behavior
I've run both `doctrine:migrations:diff` as I've made changes in one of the entities and `doctrine:migrations:sync-metadata-storage` after looking into issues.

First one results in migration with content:
<details>
<summary>Version20200617170000.php</summary>

```php
<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200617170000 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE migration_versions');
        $this->addSql('MY_SQL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE migration_versions (version VARCHAR(14) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, executed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('MY_SQL');
    }
}
```
</details>

The second one creates only one table `doctrine_migration_versions` which is empty. 

#### How to reproduce
Update from 2.2.1 to 3.0.0.

#### Expected behavior
Create `doctrine_migration_versions`, migrate records from `migration_versions` and remove it.

**Comment by simivar** [comment]
I guess it's related to/the same as #991

**Comment by goetas** [comment]
See https://github.com/doctrine/DoctrineMigrationsBundle/pull/340 for more info about this issue
