### ISSUE TITLE
The metadata storage is not up to date?

### ISSUE THREAD

**Issue by aa-aahmed** [doctrine/migrations#1003]
**The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.**

"doctrine/migrations": "~3.0",

Summary

New Project but migration fails.

Recreate Error: 

Setup new Project: composer create-project symfony/website-skeleton App-X ^4.4
Create new entity: bin/console make:user
Make Migration :  bin/console make:migration

**Comment by pawellen** [comment]
I have same issue. Adding serverVersion=mariadb-10.4.11 to connection string helped me on one environment but on another one didn't. I have no idea why.

Running sync-metadata-storage command on empty database causes error:
"The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue", but no info why is provided

**Comment by pawellen** [comment]
@aa-aahmed please try this solution from: https://github.com/doctrine/DoctrineMigrationsBundle/issues/337 and let me know if this helped you?

**Comment by aa-aahmed** [comment]
thanks I tried that and now migrations are running correctly.
