### ISSUE TITLE
migrate --write-sql from a specific version without database

### ISSUE THREAD

**Issue by loverg-c** [doctrine/migrations#1022]
Hello,

I know it is maybe a weird question, or maybe a duplicate one: Is there a way to generate .sql file (like  `doctrine:migrations:migrate --write-sql YYYYMMDDHHMMSS` with symfony console) but with a specific "FROM" version in argument without accessing to the database for getting current version ?

_For the context of my question: I am working on project where only database admin can modify the database structure in production, with only sql file. And only sysadmin can execute command on my production environment. So I am not allowed to access to the database from my development/staging environment and neither call migration command directly on production._

_The two things I can do for the moment is :_
_- Asking the database last version on production environment, and downgrade my development/staging database to this version_
_- Or asking sysadmin to execute directly the generate .sql command on the production machine and give the files to database admin_

_Both solutions can work but generating the .sql diff FROM specific version TO another specific one will be really great !_

**Comment by goetas** [comment]
- first: :sob::sob::sob::sob::sob:  (i know that does not help... but still)


- second:
> Asking the database last version on production environment, and downgrade my development/staging database to this version

This is the only solution I have in my mind.

**Comment by loverg-c** [comment]
Sadly I was expecting this :cry: 

Thanks for this fast answer ! Have a nice day ! :smile:
