### ISSUE TITLE
Is there a way to manually define version name stored in db❔

### ISSUE THREAD

**Issue by piegus** [doctrine/migrations#1029]
|    Q        |   A
|------------ | -----
| Version     | 1.8 -> 3.x

### Support Question

I upgraded from 1.8 to 3.x. right now I have table with around 10k rows in migration_version. 
I would love to be able to maually set that "old"i mgrations should be stored on old way. Just date. I.e. 20200606121212. But new migrations from 3.x would be stored as fcqn. How can I achieve this?

I want to modify only the old migrations. So I will be able to have BC.

**Comment by goetas** [comment]
You can provide a custom implementation of https://github.com/doctrine/migrations/blob/master/lib/Doctrine/Migrations/Metadata/Storage/MetadataStorage.php and inside there you can represent the migrations in any format you want.

However I do not recommend doing it in the situation you have described, the conversion from date format to fqcn is done automatically. Of course if you have other applications relying on that particular table structure, that might be the only way to do so.
