### ISSUE TITLE
Missed index schema on drop

### ISSUE THREAD

**Issue by a-menshchikov** [doctrine/migrations#1035]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.1

#### Summary

Drop index statement doesn't contain schema prefix when it used (PostgreSQL).

#### Current behavior

When I generate migration that change name of foreign key for table in custom schema, sql statement with `DROP INDEX ...` doesn't contain necessary schema name. My case looks like:

```
$this->addSql('ALTER TABLE travel.accounting_document_select_option DROP CONSTRAINT fk_8af3960e8ec3641b');
$this->addSql('DROP INDEX idx_8af3960e8ec3641b');
```

but should be

```
$this->addSql('ALTER TABLE travel.accounting_document_select_option DROP CONSTRAINT fk_8af3960e8ec3641b');
$this->addSql('DROP INDEX travel.idx_8af3960e8ec3641b');
```

**Comment by goetas** [comment]
This is something that should be reported to the https://github.com/doctrine/dbal project

**Comment by a-menshchikov** [comment]
This bug was described in the [dbal issue #2535](https://github.com/doctrine/dbal/issues/2535).
