### ISSUE TITLE
Lost data on update SQLite DB

### ISSUE THREAD

**Issue by i-terezie** [doctrine/migrations#1040]
### Bug Report

When updating the SLQLite database, I got an error with a newly added column. It had a type with a ban of null and a missing default value. As a result, an error occurred during the upgrade process. As a result, all the data in the table was lost.

IMHO this happened because in the process of migration the transaction is not used, which in such a situation rolled back the database to its original value.

Pay attention to this moment.

**Comment by goetas** [comment]
Transactions are used by default. I think that the issue is not related to this library, as it can hardly lead to database corruption.

If you are able to reproduce the issue, feel free to comment, and I will re open the ticket
