### ISSUE TITLE
Migrations configuration key "table_storage" does not exist.  

### ISSUE THREAD

**Issue by StasToken** [doctrine/migrations#1044]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | v2.7.3@d95e03ba660d50d785a9925f41927fef0ee553cf

#### Summary

./vendor/bin/doctrine-migrations generate

In InvalidConfigurationKey.php line 14:
                                                                
  Migrations configuration key "table_storage" does not exist.  
                                                                

#### How to reproduce
This is exactly the same question as [here](https://github.com/doctrine/migrations/issues/1024), I did everything the same as in the question from the link, but I get an error with a different key

#### Expected behavior
Creation of migration

**Comment by goetas** [comment]
`table_storage` is an option for migrations 3.x, if you are using migrations 2.x, please use that configuration format (see https://www.doctrine-project.org/projects/doctrine-migrations/en/2.3/reference/configuration.html#configuration).

In your report you also mention "version: 2.7"... that does not exists for doctrine migrations (currently the there is 2.3, 2.3 and 3.0)
