### ISSUE TITLE
Support for PHP8 in 2.x

### ISSUE THREAD

**Issue by thiagocordeiro** [doctrine/migrations#1048]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

Allow PHP8

**Comment by alcaeus** [comment]
Note: I've renamed this issue to cover 2.x, as 3.0 got its PHP 8 support in #1101. If PHP 8 support in 2.x is important to you, please react with a 👍 reaction on this comment. Thanks!

**Comment by alcaeus** [comment]
Everybody consider sponsoring @nicolas-grekas: his work in #1102 ensures PHP 8 support in 2.3.2 as well. Thanks Nicolas!
