### ISSUE TITLE
Subdirectories for each year within migrations folder

### ISSUE THREAD

**Issue by ic-hv** [doctrine/migrations#1049]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no (if done correctly)

#### Summary

Currently all migrations pile up within the migrations directory. So with time progressing the amount of entries within this directory will grow quite fast. It would be really nice if the migrations could be kept within subdirectories which reflect the current year (migrations/2020, migrations/2021 ...)

**Comment by greg0ire** [comment]
Have you considered using [the rollup feature](https://github.com/doctrine/migrations/pull/689), you might not know about it, apparently it's not documented…

**Comment by ic-hv** [comment]
Well, I have stumbled over it, but it seems it's not so ideal when many people are wporking on the same project and have not applied all migrations so far ... but well some documentation (examples especially) for its usage could convince me ...

**Comment by bfoosness** [comment]
This is now supported, so I believe this issue can be closed.

Search https://www.doctrine-project.org/projects/doctrine-migrations/en/3.0/reference/configuration.html#migrations-configuration for "organize_migrations", which can be set to `year` or `year_and_month` (defaults to `none`).

**Comment by greg0ire** [comment]
Thanks @bfoosness !
