### ISSUE TITLE
dropColumn removes backticks in column name

### ISSUE THREAD

**Issue by disstudio** [doctrine/migrations#1053]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.1

#### Summary

Calling dropColumn() removes backticks from column name.

#### Current behavior

Executing SQL statement: `ALTER TABLE tableName DROP period` fails with syntax error.

#### How to reproduce

```
    public function up(Schema $schema) : void
    {
        $table = $schema->getTable('tableName');
        
        if(!$table->hasColumn('period')) {
            $table->addColumn('`period`', Types::STRING, [
                'length' => 10,
                'notnull' => true,
            ]);
        }
    }

    public function down(Schema $schema) : void
    {
        $table = $schema->getTable('tableName');
        
        if($table->hasColumn('period')) {
            $table->dropColumn('`period`');
        }
    }
```

#### Expected behavior

SQL statement: ``ALTER TABLE tableName DROP `period` ``

**Comment by goetas** [comment]
This is a https://github.com/doctrine/dbal issue (and probably related to the particular version of mysql you might be using). 
Please create a report on the dedicated repo.
