### ISSUE TITLE
Option --all-or-nothing does not work correctly

### ISSUE THREAD

**Issue by javaDeveloperKid** [doctrine/migrations#1057]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.2.1

#### Summary

Option --all-or-nothing does not work correctly

#### Current behavior

This option does not rollback previous migrations.

#### How to reproduce

```php
class Migration1
{
    function up()
    {
        $this->connection->executeUpdate('ALTER TABLE table1 DROP column1');
    }
}

class Migration2
{
    function up()
    {
       $this->connection->executeUpdate('ALTER TABLE table1 DROP column2');
       throw new \Exception();
    }
}
```
```bash
$ bin/console d:m:m --all-or-nothing=true #using doctrine migrations bundle for Symfony
```

Migration2 is not executed, but Migration1 is. Did anybody encountered this problem?
I am trying to debug this at the moment, but no results so far.

#### Expected behavior

Should rollback all the previous migrations.

**Comment by javaDeveloperKid** [comment]
That is awkward:
```php
$connection->beginTransaction();
$connection->beginTransaction();
$connection->executeQuery('ALTER TABLE table1 DROP column1');
$connection->commit();
$connection->rollback();
```
It drops column1 eventually...

**Comment by javaDeveloperKid** [comment]
Ok, I can see where is the problem: https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by goetas** [comment]
Have you tried using https://github.com/doctrine/migrations/blob/3.0.x/lib/Doctrine/Migrations/Event/Listeners/AutoCommitListener.php to disable the auto commit feature?

**Comment by javaDeveloperKid** [comment]
I did not. Will check this out soon. Thank you.

**Comment by stof** [comment]
`--all-or-nothing` requires support for transactional DDL. MySQL does not support that.

**Comment by javaDeveloperKid** [comment]
@stof I would add this information to this option's description. Will create a PR.
