### ISSUE TITLE
How to force other connection on Doctrine/migrations v3 ?

### ISSUE THREAD

**Issue by darkcattz** [doctrine/migrations#1062]
|    Q        |   A
|------------ | -----
| Version     | 3.1-dev

### Support Question

Hello,

I tried the new "--conn" option command on version 3.1 but it still tries to connect to the default database.

Command : console doctrine:migrations:migrate --conn=factory

Error :
SQLSTATE[HY000] [1045] Access denied for user 'user-account'@'planisphere_php_1.planisphere_default' (using passw
ord: YES)

Normally the user for the factory is 'root', not 'user-account'.
user-account is default-user for the default connection.

I tried this solution to force privileged connection : Same result.

```
#In packages/prod/doctrine_migrations.yml
doctrine_migrations:
    connection: factory
```
Any idea ?

Thanks

**Comment by goetas** [comment]
This has not yet been merged in the bundle, see https://github.com/doctrine/DoctrineMigrationsBundle/pull/364

**Comment by kuzinmv** [comment]
https://github.com/doctrine/migrations/issues/1021#issuecomment-734202400

**Comment by goetas** [comment]
solved by https://github.com/doctrine/DoctrineMigrationsBundle/pull/364 and https://github.com/doctrine/migrations/pull/1023

**Comment by ureimers** [comment]
Hi @goetas, and thanks for your work on this fix!

As https://github.com/doctrine/DoctrineMigrationsBundle/pull/364 was pushed to 3.1.x I switched to the DEV branch, so that I'm currently on:

```
doctrine/doctrine-migrations-bundle      3.1.x-dev 33004b4
doctrine/migrations                      3.1.1
```

The `--em` command line parameter now works but `--conn` is just ignored (I can set any random string as `--conn` and it would proceed to migrate the `default` connection).

Am I missing something?

Kind regards,

Ulf

**Comment by MauriceH1** [comment]
Same issue here!

Also when specifying the connection for migrations in doctrine_migrations.yaml.

**Comment by fzizmann** [comment]
Hi same issue here.
I think a warning message with a reason would be helpful, thank you.
