### ISSUE TITLE
[v3] Programmatically filter tables / sql diffs

### ISSUE THREAD

**Issue by ro0NL** [doctrine/migrations#1064]
We use 2 migration storages for a single schema. Respectively pre- and post-deploy with independent configuration.

We configured all excluded tables using the bundle's `schema_filter` option.

Given we have 2 storage tables, the diff always tries to drop one depending on the used configuration.

If we exclude both tables using the schema_filter, the migration itself crashes as Doctine tries to `CREATE TABLE` _every time_ because it's now unaware of it's existence (i wow'ed at this point ;))

Programmatically filtering tables / generated SQL diffs is VERY hard, AFAIK.

For now i'm extending the `SqlGenerator`, which seems to work but is internal :( Perhaps expose an interface or dispatch some event?

I also tried defaulting the `--filter-expression` from console events, but bumped into https://github.com/symfony/symfony/issues/19441 still :(

**Comment by ro0NL** [comment]
Btw, the extensibility is also heavily implied by the `DependencyFactory`, as im allowed to override it from the bundle, e.g.

```yaml
doctrine_migrations:
    # ...
    services:
        'Doctrine\Migrations\Generator\SqlGenerator': <service_ID>
```

**Comment by diimpp** [comment]
Couldn't you just create two namespaces for two type of migrations and execute them separately?

> App\PreDeployMigration
> App\PostDeployMigration

**Comment by ro0NL** [comment]
@diimpp AFAIK you cant run per namespace from a single storage.

**Comment by diimpp** [comment]
@ro0NL it's certainly possible in v3. Migrations are identified by fqcn, so there is no problem with how many namespaces you will have.

![image](https://user-images.githubusercontent.com/870747/98378200-4c1c0080-2078-11eb-950a-cea75c5d0858.png)
![image](https://user-images.githubusercontent.com/870747/98378159-3eff1180-2078-11eb-9af8-4552716fdaff.png)

**Comment by ro0NL** [comment]
it's a 2-step process; run all pre-deploy migrations, then run all post-deploy migrations.


i could imagine `d:m:m Namespace\\` may solve it, but it isnt possible currently AFAIK.

i also dont like to have "executed unavailable" migrations for a status, given i'd filter by namespace. Hence i choose different storages and switch at the configuration level (eg. `--configuration=post-deploy.yaml`) to keep both states separate

**Comment by ro0NL** [comment]
to clarify the semantics; pre-deploy is all about schema changes (new columns required for the app etc), post-deploy can now assume the schema is in valid state while it still could remove columns (not required for the app anymore) or use the container in valid state :)

we basically use a 2nd doctrine migration instance as cheap solution for post-deploy console tasks. Works pretty nice actually :)
