### ISSUE TITLE
use ocramius/package-versions 2.0 to support composer 2 

### ISSUE THREAD

**Issue by czhDavid** [doctrine/migrations#1066]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

Doctrine migrations requires ocramius/package-versions in version ^1.3 . 
This version is using composer plugin which was dropped in composer version 2. 
ocramius/package-versions 2.0 is out which is compatible with composer 2 and if possible shoud be used with doctrine migrations.

**Comment by stof** [comment]
`ocramius/package-versions` 1.x can also support composer 2 in 1.8+. But it only supports Composer 2 in versions requiring PHP 7.4+.
What the ORM did is switching to `composer/package-versions-deprecated` which replaces `ocramius/package-versions` but supports Composer 1 and 2 on PHP 7.0+. This allows to keep the existing PHP support matrix.

Once dropping support for Composer 1 is an option (we should watch for Composer announcements about how the migration to Composer 2 happens), using `composer-runtime-api` directly will be the right path (`ocramius/package-versions` is just a BC wrapper around `composer-runtime-api` and will likely be deprecated in the future).

@czhDavid as a workaround, you can require `composer/package-versions-deprecated` in your own project to make it used as a replacement, which will work with Composer 2.

**Comment by kevinpapst** [comment]
> using composer-runtime-api directly will be the right path

Yes please, its time that `ocramius/package-versions` is banned from all major libs ...

**Comment by goetas** [comment]
As of https://github.com/doctrine/migrations/pull/999, `doctrine/migrations` does not depend anymore on `ocramius/package-versions`
