### ISSUE TITLE
Order of migrations was made by namespace not by Version filename

### ISSUE THREAD

**Issue by neokdev** [doctrine/migrations#1074]
Order of migrations was made by namespace by not by Version filename

|    Q        |   A
|------------ | -----
| Version     | 3.0.1

I figure that migrations was lunched in namespace order. It was a problem when namespace is different and the filename VersionXXXXXXXXXX.php order is ignored.

### Support Question

Is exist a solution for ignoring namespace at lunch or choose priority for a namespace to lunch migration ?

**Comment by neokdev** [comment]
ok I can use a Comparator

**Comment by fezfez** [comment]
@neokdev im facing the same issue, How did you use a different comparator?

**Comment by goetas** [comment]
I wrote time ago a guide about it https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/

**Comment by fezfez** [comment]
Thanks for inspiration @goetas 

I use laminas so i have to deal with it differently.

First in my config


```php
    'doctrine_factories' => [
        'migrations_cmd'           => MigrationsCommandFactory::class,
    ],
```
just to add `$dependencyFactory->setService(Comparator::class, new VersionComparatorWithoutNamespace());\\

And my version comparator is lighter than yours 

```php
<?php

declare(strict_types=1);

use Doctrine\Migrations\Version\Comparator;
use Doctrine\Migrations\Version\Version;

use function array_pop;
use function explode;
use function strcmp;

class VersionComparatorWithoutNamespace implements Comparator
{
    public function compare(Version $a, Version $b): int
    {
        return strcmp($this->versionWithoutNamespace($a), $this->versionWithoutNamespace($b));
    }

    private function versionWithoutNamespace(Version $version): string
    {
        $path = explode('\\', (string) $version);

        return array_pop($path);
    }
}

```

**Comment by goetas** [comment]
I'm happy to hear that it helped

**Comment by gggeek** [comment]
@goetas the link you posted is dead :-(

To everyone else in this thread: I do not think that sorting migrations versions by namespace by default makes much sense.
I'd rather have the default sort order be based on version names without the namespace, with a config option which allows to enable sorting with namespace.

Maybe we are doing something wrong in our project, but this is how things are going:
- we have project migrations in /migrations
- we use some 'company bundles', which also carry their own migrations (which only make sense when those  bundles are in use)
- project migrations use the `DoctrineMigrations` namespace
- bundle migrations use the bundle php namespace (probably not the best idea, as those do not need autoloading anyway)

This is what happens, when we add a new migration to the project:
- when running `doctrine:migrations:status`, "current" as well as "latest" version is always one from the last (alphabetically) bundle, even if there is the more recent one from the project. That one shows up as "next" though
- when running `doctrine:migrations:migrate --dry-run`, it says "migrating up to" the bundle version, and at the end it says that there was 1 migration executed
- when running `php bin/console doctrine:migrations:migrate`, it says again "migrating up to" the bundle version

I understand that this can be explained logically, as from the POV of the system we are staying at the latest db version and 'backfilling' an older version, but it was extremely confusing for us. The 'next' & 'latest' version we expected to be the one from the project.
It seems that the pattern of keeping migrations in different namespaces is not well supported / easy to adopt...

I'd like to have the mig. versions to be sorted based purely on name for mental sanity, and atm I am not sure what is the best way forward:
- can we keep migs in different folders, which all share the same migration namespace?
- or are we forced to use one migration namespace per folder, and implement a custom comparator?
- what is the relationship between mig namespace and php migration classes namespace?

(of course I can write a migration to patch the existing data in the migration tables, once we decide on the correct configuration... inception!)

**Comment by goetas** [comment]
>@goetas the link you posted is dead :-( 

the OVH datacenter went on fire two weeks ago.. it takes some time to get backups back :)

**Comment by gggeek** [comment]
Sorry about that.

**Comment by goetas** [comment]
@gggeek  the article i've mentioned should be back.

>It seems that the pattern of keeping migrations in different namespaces is not well supported / easy to adopt...

Prior to 3.0, it was not possible (without hacks) to have migrations in multiple namespaces. As of 3.0 it is.

When you have multiple namespaces you need to tell to the library what are the dependencies between those namespaces. Are the dependency only time-based? if yes, then the namespace is kinda useless and you can use only the class name. Are the dependencies both time based and there is one namespace that should run first than other? then you need to decide which namespace goes first. This should be done using a migration comparator.

I suggest you to read this:
>I wrote time ago a guide about it https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/

**Comment by gggeek** [comment]
@goetas thanks for putting that blog post back online, much appreciated!

As for the implementation of the "namespaces" feature, since we are on topic, I'll add little feedback (if anyone thinks it is valuable, I can create new tickets for improvements).

1. Your blog post should be part of the Migrations official docs, as otherwise the Namespaces feature remains mysterious and error-prone. Also, we should clearly document the relationship between namespace of migrations and namespaces of migrations php classes which implement them. Can migrations classes implement any namespace, regardless of the folder they are in ?
2. I think that there should also be "official recommendations" of configurations for common scenarios such as:
   - having "plugins migrations" and "app migrations". In such case plugins generally have to be executed first, and app last. Hence namespace of plugin should be alphabetically lower than the standard migrations namespace to be sorted correctly without having to implement comparators. (In fact in your example you have both 'app' and 'plugins' inside `/src` - that seems weird to me. plugins are generally managed as separate composer packages)
   - having migrations stored in different bundles which are still all part of the same "app", and thus should belong all to the same namespace for correct sorting
3. when there are multiple independent plugins, eg. A and B standalone, C which depends on B and D which depends on A and C, I don't think that sorting migrations for execution based on one-namespace-per-plugin is sufficient. In theory it could, but in projects I've worked on migrations are used not only to change table definitions to match doctrine entities, they are used to fix bad data, seed new data and much more. Trying to find a simple "golden rule" for making migrations sortable often backfires, and the safest way to have things working as expected is to have a single prioritized list, not many (that, and making migrations as much idempotent as possible, eg. always using `IF EXISTS` on `DROP TABLE`).
4.  In the spirit of allowing many folders to be mapped to the same Migrations namespace, I think that the default configuration should be swapped. It should not be `[ns => folder,]+` but `[folder => ns,]+`

**Comment by goetas** [comment]
> Your blog post should be part of the Migrations official docs, as otherwise the Namespaces feature remains mysterious and error-prone.

It is true that more documentation/examples are needed. My blogpost explains a usecase for an application i've developed, but I know other devs who have build different types of apps but using the same migrations feature  (see https://github.com/SyliusLabs/DoctrineMigrationsExtraBundle)

> Also, we should clearly document the relationship between namespace of migrations and namespaces of migrations php classes which implement them. 

This is not the best thing to do. Here the relation is intentionally loose, so you can model it in the way that fits better for your app.

> Can migrations classes implement any namespace, regardless of the folder they are in ?

yes if there is a proper class loader that can locate those migrations. is it a good idea? i do not know.

> having "plugins migrations" and "app migrations". In such case plugins generally have to be executed first, and app last.

again, it depends on the application. as example in all the apps i've built, the "app migrations" are executed first, not last.

> In fact in your example you have both 'app' and 'plugins' inside /src - that seems weird to me. plugins are generally managed as separate composer packages

that was just an example, you can place your files where you prefer

> when there are multiple independent plugins, eg. A and B standalone, C which depends on B and D which depends on A and C, I don't think that sorting migrations for execution based on one-namespace-per-plugin is sufficient. In theory it could, but in projects I've worked on migrations are used not only to change table definitions to match doctrine entities, they are used to fix bad data, seed new data and much more. Trying to find a simple "golden rule" for making migrations sortable often backfires, and the safest way to have things working as expected is to have a single prioritized list, not many (that, and making migrations as much idempotent as possible, eg. always using IF EXISTS on DROP TABLE).

You do not have always control over who writes migrations. They could be developed by different companies in different times, for different versions of your app, but stil you need to make it work.
The sorting function is simple enough and powerful too. If you can get a single prioritized list, nothing blocks you from hardcoding it in your comparator function bypassing the whole sorting concept.

> In the spirit of allowing many folders to be mapped to the same Migrations namespace, I think that the default configuration should be swapped. It should not be [ns => folder,]+ but [folder => ns,]+


this is a more complex topic that should be discussed in a separate ticket (that I've seen you've already created)

**Comment by gggeek** [comment]
> > Also, we should clearly document the relationship between namespace of migrations and namespaces of migrations php classes which implement them.
> 
> This is not the best thing to do. Here the relation is intentionally loose, so you can model it in the way that fits better for your app.

Indeed that's what I feel should be explained better: that the relationship is loose, and that migrations stored in a bundle do not necessarily need to use the "proper" namespace of the bundle - they could f.e. use the same namespace as the "app" migrations, given, as you said, a proper class loader

**Comment by gggeek** [comment]
> as example in all the apps I've built, the "app migrations" are executed first, not last.

Interesting.
In my case, the app "knows" about the fact that plugins are installed and enabled, but plugins do not know about the app. So, f.e., in the release in which a new plugin gets installed, a plugin migration might create a table, and an app migration might fill it in with data.
Are the plugins in your apps fulfilling a different role, are you organizing the migrations differently, or are the envisaged scenarios different?

**Comment by goetas** [comment]
>Interesting.
In my case, the app "knows" about the fact that plugins are installed and enabled, but plugins do not know about the app. So, f.e., in the release in which a new plugin gets installed, a plugin migration might create a table, and an app migration might fill it in with data.
Are the plugins in your apps fulfilling a different role, are you organizing the migrations differently, or are the envisaged scenarios different?

in my apps plugins might depend on data structures provided by the "app". as example the app might add a `users` table, and when that table has been created by the "app", the plugin can create some `report (fk_user, some_other_col)` table. here `fk_user` is a foreign key referencing the `users` table. 

In that situation the FK can be created only if the `users` table has been already added by the core app, thus, the plugin migration has to run after the app migration. in the same way a plugin can depend on another plugin, and have the same kind of dependency relation
