### ISSUE TITLE
Migrations per Bundle

### ISSUE THREAD

**Issue by KingCrunch** [doctrine/migrations#109]
Currently it is only possible to have a single folder with the migrations in it, usually in `app/DoctrineMigrations`. I don't know complicated this may be, or which pitfalls can appear, but I think it would be interesting, if it is possible to have different migrations per bundle. I thougt of something similar to `DoctrineFixturesBundle`, but for migrations.

**Comment by mikeSimonson** [comment]
If you want a migration per bundle you should just have multiple migration configuration.
But trying to share those migration in a bundle is probably a bad idea (impossible to prevent conflicts).
