### ISSUE TITLE
Asserting instance of specific ConfigurationHelper instead of depending on ConfigurationHelperInterface

### ISSUE THREAD

**Issue by tadasaa** [doctrine/migrations#1115]
|    Q        |   A
|------------ | -----
| Version     | 2.3.2

### Issue

Hello, I was wondering why AbstractCommand class in 2.3.x versions is asserting that existing `configuration` helper is of instance `\Doctrine\Migrations\Tools\Console\Helper\ConfigurationHelper`, instead of asserting that it's an instance of the `ConfigurationHelperInterface`, similar to the way the private function `AbstractCommand::hasConfigurationHelper()` acts ? We use a different configuration helper from the DoctrineORMModule and the assertion ends up in unwanted warnings being logged in our logs. 

Line we're having problems with:
https://github.com/doctrine/migrations/blob/2.3.x/lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php#L119
Line that I think acts correctly:
https://github.com/doctrine/migrations/blob/2.3.x/lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php#L188

**Comment by greg0ire** [comment]
Fixed in #1205
