### ISSUE TITLE
Error "There is no active transaction" instead of Error about SQL syntax

### ISSUE THREAD

**Issue by AntoineRoue** [doctrine/migrations#1139]
### Bug Report

Syntax errors in SQL does not always display a syntax error message. It can display the error "There is no active transaction"

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.1

#### Summary

When executing one migration with two DDL statements, if the second one has a syntax error, then the error displayed by the command is not a syntax error, but the error "There is no active transaction".
Note : I also tried when executing several migrations and in this case the error message showed is a syntax error message. It seems to happen only when migrating one file.

#### Current behavior

A syntax error can display the error "There is no active transaction"

#### How to reproduce

1. Have all your migrations up to date
2. Create a migration where you have two ALTER TABLE statements, and make any syntax error in the second statement.
3. Run this migration

Code example :
`$this->addSql('ALTER TABLE article ADD publish_at DATETIME DEFAULT NULL');`
`$this->addSql('ALTER TABLE article CHANGE publish_at DATETIME NOT NULL');`

#### Expected behavior

A syntax error message should be displayed

**Comment by greg0ire** [comment]
> A syntax error can display the error "There is no active transaction"

Can you please get a stack trace for this? See https://symfony.com/doc/current/contributing/code/stack_trace.html

Also, what RDBMS are you using? With what driver? What version of PHP? My money is on Mysql + PDO + PHP 8, because this looks somewhat related to https://github.com/doctrine/migrations/issues/1104

**Comment by AntoineRoue** [comment]
I am using MySQL 8.0.3 with PDO and PHP 8.
I'll get the stack trace this evening, in about 9 hours.

**Comment by AntoineRoue** [comment]
Here is the stack trace :
```
at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1845
 PDO->rollBack() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1845
 Doctrine\DBAL\Connection->rollBack() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\Version\DbalExecutor.php:257
 Doctrine\Migrations\Version\DbalExecutor->migrationEnd() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\Version\DbalExecutor.php:115
 Doctrine\Migrations\Version\DbalExecutor->execute() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\DbalMigrator.php:101
 Doctrine\Migrations\DbalMigrator->executePlan() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\DbalMigrator.php:74
 Doctrine\Migrations\DbalMigrator->executeMigrations() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\DbalMigrator.php:151
 Doctrine\Migrations\DbalMigrator->migrate() at C:\prog\tests\symfonycertification\test-migration\vendor\doctrine\migrations\lib\Doctrine\Migrations\Tools\Console\Command\MigrateCommand.php:207
 Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\console\Command\Command.php:256
 Symfony\Component\Console\Command\Command->run() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\console\Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\framework-bundle\Console\Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\console\Application.php:290
 Symfony\Component\Console\Application->doRun() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\framework-bundle\Console\Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\prog\tests\symfonycertification\test-migration\vendor\symfony\console\Application.php:166
 Symfony\Component\Console\Application->run() at C:\prog\tests\symfonycertification\test-migration\bin\console:43
```

And some log :
```
[debug] "START TRANSACTION"

[info] ++ migrating DoctrineMigrations\Version20210330205434
[debug] ALTER TABLE article CHANGE name name VARCHAR(255) NOT NULL
[debug] ALTER TABLE article CHANGE name name VARCHAR(255) NOT NULL

[debug] ALTER TABLE article CHANGE name VARCHAR(255) NOT NULL
[debug] ALTER TABLE article CHANGE name VARCHAR(255) NOT NULL

[debug] "ROLLBACK"

[critical] Error thrown while running command "doctrine:migrations:migrate -n -vvv". Message: "There is no active transaction"
```

**Comment by greg0ire** [comment]
We can see in the stack trace that the error is occurring during a rollback, that's interesting! Maybe this could be fixed by doing a PR similar to https://github.com/doctrine/migrations/pull/1131 , but for rollback? Cc @ostrolucky

**Comment by ostrolucky** [comment]
Yeah looks like same issue
