### ISSUE TITLE
doctrine/dbal 3 support

### ISSUE THREAD

**Issue by weaverryan** [doctrine/migrations#1141]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Apologies if I've missed some discussion somewhere! Is there any blocker for making a PR to add doctrine/dbal 3 support?

Thanks!

**Comment by greg0ire** [comment]
I don't think so, you can give it a try if you want IMO 👍

**Comment by greg0ire** [comment]
In fact, I just gave it a try, and there is no point until the ORM supports DBAL 3.

**Comment by PowerKiKi** [comment]
Do you mean that it is technically impossible to do, or that even if we did it would not really be useful ?

What blocker did you see ?

**Comment by greg0ire** [comment]
There is a dev dependency on the ORM which prevents installing DBAL 3, so you cannot run the test suite with it.

**Comment by scaytrase** [comment]
Any updates on this? dbal 3 seems useless on most of our projects because we have migrations and migrations bundle preventing installation of that version.

**Comment by PowerKiKi** [comment]
This issue is blocked by https://github.com/doctrine/orm/projects/5

**Comment by greg0ire** [comment]
If you feel that blocker is important, you can work on removing it by adding a CI job that does `composer remove doctrine/orm` then runs the tests suite but skips tests involving the orm

**Comment by derrabus** [comment]
ORM 2.10.x-dev allows the installation of DBAL 3. The blocker should be gone, I guess.

**Comment by gjuric** [comment]
ORM now supports DBAL 3, any chance somebody is working on this?

**Comment by derrabus** [comment]
@gjuric Did you see #1198?

**Comment by gjuric** [comment]
Saw it, this was just a little nudge to make it happen without putting pressure on anybody :)

**Comment by goetas** [comment]
implemented in https://github.com/doctrine/migrations/pull/1198
