### ISSUE TITLE
More robust migrations

### ISSUE THREAD

**Issue by pedrofs** [doctrine/migrations#115]
Hi, guys. I'm trying to perform some migrations to alter my database schema and then normalize data on the new tables.

For example: I want to create new entities based on those that already exist in my database. So, raw SQL is not an option here. Then I'm trying to use the entity manager from container to retrieve entities and create new ones from them.

I got stuck when I need to persist an entity and then gets it to use in another entity relation. The id from the first flushed entity is null. Can it be because the whole migration is executed inside a database transaction?

If it is really occurring by the database transaction, is it possible to make it more flexible in the way we can perform this kind of migration?

I'm not sure if here is the right place for this kind of post... but it could be an improvement for migrations.

Thanks.

**Comment by mikeSimonson** [comment]
There is no problem about moving your data from old entities to new entities in sql.
It's even the only performant way of doing it.
Using the entity manager here is really not recommended.

**Comment by rjmunro** [comment]
Using the entity manager is likely to break because if you change your entities later, e.g. to remove a field, the entity manager will not be set up to work with the version of the database that the migration is working against.

**Comment by mikeSimonson** [comment]
@rjmunro Well right using the entity manager is not going to work if you change your entities.
And even if you don't it's going to be slow as hell.
