### ISSUE TITLE
RFC: config key to generate non-transactional migrations

### ISSUE THREAD

**Issue by greg0ire** [doctrine/migrations#1153]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

To fix issues related to PHP 8 finally exposing a long living issue with implicit transactions, it would be great to give our users the necessary tool to easily generate non-transactional migrations. A simple boolean could govern the generation of an override of `AbstractMigration::isTransactional()` that would return false. They would still be able to have transactional DDL migrations by dropping that override.

When implementing and reviewing this, we should be mindful of `all_or_nothing`, which could be set to `true` iff the boolean defined in this RFC is set to `true` as well.

The silencing mechanism introduced in #1131 and #1143 could be deprecated , and then dropped in the next major release.

A shell script could be provided as part of the UPGRADE guide to help people make their existing migrations non-transactional via `sed`.

**Comment by stof** [comment]
> A shell script could be provided as part of the UPGRADE guide to help people make their existing migrations non-transactional via `sed`.

Or maybe this could be contributed to rector, which might be more reliable than a sed replacement.

**Comment by greg0ire** [comment]
Alternatively, we could use a setting that could take more than 2 values:

- `always`: no override method generated, disables `TransactionHelper`
- `silence_failures`: is the default setting, deprecated from the start, no override method generated, `TransactionHelper` is used 
- `never`: generates an override method, disables `TransactionHelper`

That way we can get rid of `TransactionHelper`

**Comment by greg0ire** [comment]
Or maybe 2 booleans:

- `transactional`: whether to generate an override method
- `silence_transaction_failures`: setting that one to true is the default, but is deprecated.

But then we would have to deprecate `silence_transaction_failures` in 4.x and remove it in 5.x… maybe the best way is a node that is ideally boolean, but can take a special string value (`silence_failures`)

**Comment by greg0ire** [comment]
Now that I think of it, I can't think of a situation where it would be useful to have `silence_transaction_failures` set to `false`, so just the first boolean will be useful.

**Comment by VincentLanglet** [comment]
@greg0ire I was going to open an issue because the migration was not transactional and I just saw your issue saying it's transactionnal.

The following migration
```
        $this->addSql('DROP TABLE asv_relaunch');
        $this->addSql('ALTER TABLE asv_client DROP next_check_by_lab');
        $this->addSql('ALTER TABLE asv_lab DROP relaunched_by_grc, CHANGE level level VARCHAR(255) DEFAULT \'form.lab.level.not_computed\' NOT NULL');
    }
```
Failed on the third SQL.

Now, if I run again the migration, it fail on the first line because the `asv_relaunch` table doesn't exist anymore.

**Comment by stof** [comment]
@VincentLanglet MySQL simply does not support transactional migrations (DDL statements are causing an implicit COMMIT of the current transaction).
Transactional migrations are indeed a lot nicer as they ensure you don't end up with a half-migrated state in case of failure, which is why they are the default on platforms supporting them (hint: Postgresql for instance)

**Comment by greg0ire** [comment]
@VincentLanglet you can review https://github.com/doctrine/migrations/pull/1157 , I added a detailed explanation about all this in it.

**Comment by goetas** [comment]
solved by https://github.com/doctrine/migrations/pull/1157
