### ISSUE TITLE
Skipped migration should not generate an error log

### ISSUE THREAD

**Issue by ogizanagi** [doctrine/migrations#1164]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.2

#### Summary

A skipped migration is logged as an error.

#### Current behavior

We have Sentry wired on Monolog, so any log with `level >= NOTICE` is reported to Sentry.
Whenever some migrations are skipped (as expected), we now have Sentry reports about it, since it's logged as an error:

https://github.com/doctrine/migrations/blob/8274a0a52bb801ff2424ad4533449985c30bea7c/lib/Doctrine/Migrations/Version/DbalExecutor.php#L273-L280

#### How to reproduce

Generate a new migration with:

```php
    public function preUp(Schema $schema): void 
    {
        $this->skipIf(true, 'Some normal and expected reason this should be skipped');    
    }
```

#### Expected behavior

Use another log level, more appropriated? A level INFO should be enough?
If this level is legit, we might add a dedicated channel in the Symfony bundle, so it can be excluded.

**Comment by goetas** [comment]
I believe that `NOTICE` is the right error level in this case... , so for sure it should not be `ERROR` (but `NOTICE` will not solve @ogizanagi 's issue).

I'm not sure if it makes sense to have it `INFO`. @greg0ire  what to you think?

**Comment by greg0ire** [comment]
I agree that `NOTICE` seems best here… info is for stuff that is fully normal, like "user logs in". A skipped migration is something that is normal but should probably still raise eyebrows.

**Comment by ogizanagi** [comment]
I guess `NOTICE` is fine regarding the PSR 3 description. I think we mostly have notices reported to Sentry to cover PHP notices (`E_NOTICE`). But we could either re-map these to warning using [`framework.php_errors.log` mapping](https://github.com/symfony/symfony/blob/c71c8727cc665c9e9b56e299fcfcc0adfbf02bac/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1122), or filter out these logs if we also add a channel to use in the bundle.

**Comment by goetas** [comment]
@ogizanagi If you are willing to crete a PR with the change you have proposed, it seems that we have an agreement here in NOTICE as error level
