### ISSUE TITLE
Deprecate silencing

### ISSUE THREAD

**Issue by greg0ire** [doctrine/migrations#1169]
Some platforms do not support transactions for DDL statements, and doctrine/migrations historically swipes the issue under the rug by not letting uninformed users know about it. Since PHP 8, we even silence the issue suddenly made visible by PDO. Let's stop doing that.

MySQL users should typically set `transactional` to `false` in their configuration and manually edit the `isTransactional` method override generated in their migrations to `return true` (or drop it entirely) if they run DDL migrations and want those to be transactional.

**Comment by goetas** [comment]
Done in https://github.com/doctrine/migrations/pull/1170
