### ISSUE TITLE
Allow to change config file path

### ISSUE THREAD

**Issue by dextervip** [doctrine/migrations#117]
Hi,

I am not sure if this feature is already implemented. I couldn't find it. I am setting up doctrine migrations on top of silex and I have to pass --configuration argument everytime I run it at commandline or I have to change working dir to the same as migration configuration file.

php console.php migrations:status --configuration=config/migrations.yml
or
chdir(__DIR__.'/config');

It would be nice to allow configure it before running commandline.

**Comment by mikeSimonson** [comment]
@dextervip Can you provide a PR so that it works like the connection configuration ?

**Comment by dextervip** [comment]
@mikeSimonson I can't remember what was my real issue but configuration argurment works fine but you must pass the absolute path.
    php app/console.php migrations:migrate --configuration=c:/htdocs/myproject/app/config/migrations.yml

However I have been using chdir(DIR.'/config') in the console script file.

**Comment by mikeSimonson** [comment]
@dextervip Where did you make that change (file and line number) ?

Are you sure you run on the last version of doctrine migration ?
