### ISSUE TITLE
Error-prone sort behaviour on loadMigrations

### ISSUE THREAD

**Issue by asysrieke** [doctrine/migrations#1172]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.4

#### Summary

The order of loaded migrations on the abstract MigrationFinder is misleading and probably not as intended. 

#### Current behavior

In Doctrine\Migrations\Finder\Finder::loadMigrations() migration classes are loaded by submitted migration files.
After loading the classes they are iterated and transferred into the $versions Array. 
The $versions array is then sorted by key with SORT_STRING option and returned.
As the array is sorted by key with SORT_STRING option and you have more than 10 migrations, the returned versions array will be in misleading order as follows:
[0] => Version 0
[1] => Version 1
[10] => Version 10
[11] => Version 11
[2] => Version 2

The screenshot shows the unsorted version array and the sorted one.
![2021-06-23 17_48_58-Window](https://user-images.githubusercontent.com/15608701/123132727-56480f00-d44f-11eb-953d-7ca1be34e635.png)

#### How to reproduce
Add more than 10 migrations to your project and dump the output of loadMigrations()

#### Expected behavior
I would expect the returned array to be sorted by the version number or not sorted at all.

**Comment by goetas** [comment]
This is not a bug but an intentional choice. you can see https://github.com/doctrine/migrations/issues/457 and the related tickets for more context

**Comment by asysrieke** [comment]
Thanks for the quick response. 

But just to verify: It is intended that the migrations are sorted by the numeric array key with SORT_STRING option?
From the context #457 I get that the aim was to get a valid order by the version-number even when it's alphanumeric. 

But in that former version the array key was the version number
```
$this->migrations[$version->getVersion()] = $version;
ksort($this->migrations, SORT_STRING);
```

In the current version the array key is just default numerical array key
```
$versions = [];
foreach ($classes as $class) {
    $versions[] = $class->getName();
}

ksort($versions, SORT_STRING);

return $versions;
```

So the ksort is sorting just the numeric array key which does not lead to any useful order in the returned versions

**Comment by goetas** [comment]
> In the current version the array key is just default numerical array key

Where did you get that code? the current sorting algo is: 

https://github.com/doctrine/migrations/blob/48c6992b2db84e3997d5c887203da6705b572f6c/lib/Doctrine/Migrations/Version/AlphabeticalComparator.php

**Comment by asysrieke** [comment]
In Doctrine\Migrations\Finder\Finder::loadMigrations(). Lines 65-73.

https://github.com/doctrine/migrations/blob/3.1.x/lib/Doctrine/Migrations/Finder/Finder.php

**Comment by stof** [comment]
In any case, using SORT_STRING on numeric keys indeed does not make sense.

**Comment by goetas** [comment]
I believe that the sorting done there could be removed since the real sorting happens in the migration sorter (probably that is just a leftover of the 2.x branch)
