### ISSUE TITLE
Migrate down

### ISSUE THREAD

**Issue by pmithrandir** [doctrine/migrations#118]
Hello.

On cakephp, there was a great function that allow us to simply migrate from a version n to version n-1.
Migrate down.

Do you think you could implement such a function ?

The nicea thing is taht when you actually test your migration, you can easily go back to the last version without wondering what name it has.

When you have to generate / modify / update few time the migration script to get the right result, it's much easier to test that the new script works fine in both way like that.

Best regards,
Pierre

**Comment by mikeSimonson** [comment]
@pmithrandir That feature would be really usefull. Can you provide a PR ?

**Comment by chrisguitarguy** [comment]
I think this can already be done? See 29cdbe0f9158df3411a10ec9856ae7bc8289c00a

```
$ ./vendor/bin/doctrine-migrations migrations:migrate
$ ./vendor/bin/doctrine-migrations migrations:migrate prev
```

**Comment by mikeSimonson** [comment]
@chrisguitarguy yes it has been implemented since then.
