### ISSUE TITLE
Always drop table Migration_version

### ISSUE THREAD

**Issue by Charlewic** [doctrine/migrations#119]
Hello, 

Config : symfony 2.2, os x 10.8.3, PHP 5.4.4, Apache 2, Database ; oracle OSI 8.

When I type the doctrine:migrations:diff, I always have this line generated : 

```php
public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "oracle");
        
        $this->addSql("DROP TABLE MIGRATION_VERSIONS");
    }
```

So the big problem is : always when I create a DIFF migration file, he drop the table migration and re-create it after with the new migration value. When I get my third migration file he forgot that he already have execute the first one (who have been drop by the second one) and generate a lot of error.

So why he always generate this drop table ?!

Thanks to help me !

**Comment by chrisguitarguy** [comment]
This was fixed in #217 (42892264635df59e62d89c58f8545fa108c818f3) and can be closed.
