### ISSUE TITLE
Exception on wrong transactional logic hides underlying exception

### ISSUE THREAD

**Issue by UlrichThomasGabor** [doctrine/migrations#1209]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | 
| Version     | 3.3.0

#### Summary

Flawed transaction logic throws an Exception and leads to loss of the underlying Exception thus making it hard to debug the issue.

#### Details

https://github.com/doctrine/migrations/blob/36205d5af1d00fa2348ab91fddee5f4f45511732/lib/Doctrine/Migrations/Tools/TransactionHelper.php#L60-L64

This does not work anymore, because `wrappedConnection` returns `PDO\Connection` since one of the last updates. Line 60 should be replaced by `$connection->getWrappedConnection()->getWrappedConnection();` or something like that.

This method is executed deep down in this block (line 115):
https://github.com/doctrine/migrations/blob/36205d5af1d00fa2348ab91fddee5f4f45511732/lib/Doctrine/Migrations/Version/DbalExecutor.php#L112-L118
thus resulting in trying to rollback a transaction already rolled back, therefore throwing an exception and then leads to the loss of the underlying Exception `$e`.

#### How to reproduce

Write a failing migration playing with transactions?

**Comment by greg0ire** [comment]
> wrappedConnection returns `PDO\Connection` since one of the last updates

:thinking: out of curiosity, what is `$connection` then?

> something like that

```php
$wrappedConnection = $connection;
while (method_exists($wrappedConnection, 'getWrappedConnection')) {
    $wrappedConnection = $wrappedConnection->getWrappedConnection();
}
```

I don't feel great about this, so let's fully understand this first, please.

**Comment by UlrichThomasGabor** [comment]
There is an abstract Connection in the namespace above, which contains a wrapped concrete abstract Connection, e.g. PDO\Connection which again contains the real PDO Connection.

Don’t know why this change was made. It’s a little bit awkward indeed.

**Comment by greg0ire** [comment]
Oh so "the last updates" contain an update from doctrine/dbal 2 to 3 I suppose?

> Don’t know why this change was made. 

Probably to use composition over inheritance? It would make sense not to expose APIs we don't control.

**Comment by UlrichThomasGabor** [comment]
> Oh so "the last updates" contain an update from doctrine/dbal 2 to 3 I suppose?

Yes this may be true.


> > Don’t know why this change was made.
> 
> Probably to use composition over inheritance? It would make sense not to expose APIs we don't control.

Yes, this makes sense, but writing the recursive unwrapping is nevertheless awkward ;)

**Comment by greg0ire** [comment]
It is, isn't it? Can you please test #1210 ?

**Comment by UlrichThomasGabor** [comment]
Yes, works

**Comment by michaelphillpotts** [comment]
Hi

Getting an issue with this change when using SQLSrv driver on PHP 8.0 (Windows)

The exception is a PDOException

>  SQLSTATE[IMSSP]: This function is not implemented by this driver.

The class types I get while looping are:
Doctrine\DBAL\Connection
Doctrine\DBAL\Driver\PDO\SQLSrv\Connection
PDO

Then the exception is thrown on the _method_exists_ call

Not too sure on the logic around PDO / SQLSrv and the behavior when calling method_exists but I suggest we change the while loop to stop if the $innermostConnection is a instanceof PDO ?

**Comment by greg0ire** [comment]
See #1214
