### ISSUE TITLE
PHP attributes usage cause unexpected changes

### ISSUE THREAD

**Issue by mpiot** [doctrine/migrations#1222]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.3.2

#### Summary

In a project I try to update from Doctrine Annotations to PHP Attributes, but it causing unexpected schema changes.

#### Current behavior

Previous annotations:
```php
/**
 * @ORM\ManyToMany(targetEntity=User::class)
 * @ORM\JoinColumn(nullable=false)
 */
private Collection $users;
```

New attributes:
```php
#[ORM\ManyToMany(targetEntity: User::class)]
#[ORM\JoinColumn(nullable: false)]
private Collection $users;
```

When executing a migrations we have something like:
```php
public function up(Schema $schema): void
 {
    // this up() migration is auto-generated, please modify it to your needs
    $this->addSql('ALTER TABLE soleau_envelope_user DROP CONSTRAINT FK_A06D2FACA2F59D5');
    $this->addSql('ALTER TABLE soleau_envelope_user ADD CONSTRAINT FK_A06D2FACA2F59D5 FOREIGN KEY (soleau_envelope_id) REFERENCES soleau_envelope (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
}

public function down(Schema $schema): void
{
    // this down() migration is auto-generated, please modify it to your needs
    $this->addSql('ALTER TABLE soleau_envelope_user DROP CONSTRAINT fk_a06d2faca2f59d5');
    $this->addSql('ALTER TABLE soleau_envelope_user ADD CONSTRAINT fk_a06d2faca2f59d5 FOREIGN KEY (soleau_envelope_id) REFERENCES soleau_envelope (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
}
```

#### Expected behavior

By changing from DoctrineAnnotations to PHP Attributes, this change should not appear. This appear 10 times for 51 ManyToMany relations.

The change is always the same, we loose the 'ON DELETE CASCADE'.

**Comment by stof** [comment]
should be reported to the ORM. doctrine/migrations does not read annotations or attributes. It uses the mapping info from the ORM. So if the schema needs to change, it means those 2 mappings are not actually equivalent in the ORM, which indicates either a bug in the ORM or a documentation issue.
there is strictly nothing that doctrine/migrations can change by itself.

**Comment by mpiot** [comment]
@stof Thanks a lot for your answer.
