### ISSUE TITLE
Issue with migration dry-runs and ORM

### ISSUE THREAD

**Issue by samjarrett** [doctrine/migrations#124]
The Symfony manual encourages users to go and fetch the ORM Entity Manager inside postUp functions to go and set up entities/manipulate data (see http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#container-aware-migrations).

The problem with this is that it doesn't get along with dry-run operations. The console ends up with an error, as the postUp function actually executes, and the entity manager is oblivious to the fact that it's only _pretending_ to be doing operations.

As far as I could tell, there isn't an exposed way to detect dry runs and therefore skip processing inside your postUp functions. 

Either the Doctrine EM needs to be able to detect dry runs and just log what it wanted to do, or we need a way of detecting dry run mode and choosing to skip.

**Comment by mikeSimonson** [comment]
@stof What do you mean by should use a different service ?

**Comment by stof** [comment]
@mikeSimonson the use case for container-aware migrations in a Symfony2 project is not to access the EntityManager (which makes the migration fragile as it can run only if it is the latest one). The valid use case is accessing other Symfony services not related to the Doctrine layer. A use case could be migrating a field from storing a Markdown text to storing an HTML text. Your migration will want to use the Markdown parser to convert the data.

**Comment by mikeSimonson** [comment]
@stof Ok so the example in the Symfony documentation should be changed to use any other service than the entity manager.

**Comment by stof** [comment]
@mikeSimonson please open an issue (or better a PR) on https://github.com/doctrine/DoctrineMigrationsBundle

**Comment by mikeSimonson** [comment]
@stof done. https://github.com/doctrine/DoctrineMigrationsBundle/pull/105
