### ISSUE TITLE
Weird migration is generated after updating from 3.3.2 to 3.4.1

### ISSUE THREAD

**Issue by rmikalkenas** [doctrine/migrations#1241]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.3.2 -> 3.4.1

#### Summary

After updating from 3.3.2 to 3.4.1 weird migration is creating.
Using 3.3.2 created an entity ant generated a migration: https://github.com/rmikalkenas/migration-issue/blob/master/migrations/Version20220224201549.php
Everything looks correct and no issues at this point.
Then updated to 3.4.1 and run diff command. Doctrine generates a new migration: https://github.com/rmikalkenas/migration-issue/blob/master/migrations/Version20220224201642.php
the `up` migration looks correct and is fixable by defining default value to `0.0000`, but the `down` migration looks strange. And even after executing this migration and running diff again, doctrine generates new migration file with empty `up` and the same `down` migration as on Version20220224201642

Attaching reproducer

#### How to reproduce

Reproducer: https://github.com/rmikalkenas/migration-issue

**Comment by pkly** [comment]
I have the same issue after upgrading, it seems that the `up` method is being generated correctly, but `down` seems to regenerate _all fields_ for _all entities_ in my case, which is obviously incorrect. 
Thankfully it can be corrected by hand in the meantime, but it's a pretty awful bug that I'm pretty sure I've encountered before.

**Comment by greg0ire** [comment]
This looks related to https://github.com/doctrine/DoctrineBundle/pull/1471

I would check what the collation is desired, and which is the actual one.

**Comment by rmikalkenas** [comment]
@greg0ire managed to fix most of errors by changing config key from `collate` to `collation`.

But there is still one weird error:
if entity has
```
/**
 * @ORM\Version()
 * @ORM\Column(type="datetime")
 */
private \DateTime $version;
```
column, the same migration is generated even after executing it:

```
public function up(Schema $schema): void
{
    $this->addSql('ALTER TABLE customer CHANGE version version TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL');
}

public function down(Schema $schema): void
{
    $this->addSql('ALTER TABLE customer CHANGE version version DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
}
```

Tried to debug and find a root cause:
- `\Doctrine\DBAL\Platforms\AbstractMySQLPlatform::getDateTimeTypeDeclarationSQL` takes into consideration whether it's column definition has a `version` config or not
- `\Doctrine\Migrations\Generator\DiffGenerator::generate` creates `$fromSchema` (based on actual database tables represenations) and `$toSchema` (based on entities). And found out that `$fromSchema` does not add `$_platformOptions`, resulting to different `\Doctrine\DBAL\Platforms\AbstractMySQLPlatform::getDateTimeTypeDeclarationSQL` output

**Comment by greg0ire** [comment]
Nice job with the debugging! What difference in the platform options results in the different output? Is it the collation?

**Comment by rmikalkenas** [comment]
@greg0ire I simply did such changes:
![image](https://user-images.githubusercontent.com/14221532/156145849-84eb0138-2c8c-4a09-a82e-e8cb37643553.png)
`collate` -> `collation`

But it didnt help with versioned field.. Will try to spend more time today to find out what has changed

**Comment by rmikalkenas** [comment]
Closing in favor of https://github.com/doctrine/dbal/issues/5307
