### ISSUE TITLE
Add description option for migration generation

### ISSUE THREAD

**Issue by tom-combet** [doctrine/migrations#1245]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

**Usecase**:
As a user, I want to provide a description that will be used to generate the migration class, so that I don't have to fill it manually.

**Solution**: 
Add `<description>` placeholder in the default template (replacing the return value of [`getDescription`](https://github.com/doctrine/migrations/blob/8b9391f455d08fb0a9734bd0061457380e75858b/lib/Doctrine/Migrations/Generator/Generator.php#L48) method to be precise) and add a `$description` argument with `string` type to [`generateMigration`](https://github.com/doctrine/migrations/blob/8b9391f455d08fb0a9734bd0061457380e75858b/lib/Doctrine/Migrations/Generator/Generator.php#L77) method from Generator.

**Comment by greg0ire** [comment]
> so that I don't have to fill it manually.

Is your plan to generate a migration programmatically for each migration? If yes, based on what?

**Comment by tom-combet** [comment]
Yep, I'd like to call `generateMigration` programmatically when specific events are fired in my application.

**Comment by greg0ire** [comment]
Are you already calling `generateMigration` directly? Because you might be at risk of a BC-break:
https://github.com/doctrine/migrations/blob/8b9391f455d08fb0a9734bd0061457380e75858b/lib/Doctrine/Migrations/Generator/Generator.php#L27

**Comment by tom-combet** [comment]
Upsy... so there is no safe way to generate or migrate programmatically without executing the console commands?

**Comment by greg0ire** [comment]
A quick look at references to that method confirms that there isn't.

**Comment by tom-combet** [comment]
Uh, this is unfortunate... I'll take the risk and use it anyway.

Thanks for the clarification.
