### ISSUE TITLE
support dropping and re-adding indexes

### ISSUE THREAD

**Issue by arderyp** [doctrine/migrations#1261]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ?
| BC Break    | no

#### Summary

Often times migrations:diff will trigger changes to foreign-key and/or index fields that can't be executed without first dropping the key/index.  This has to be done manually by the developer, as Doctrine Migrations doesn't detect the situation and write sql statements to drop the key/index before the statement to execute the field changes.  Likewise, it also does not write a follow up SQL statement to run after the changes to re-add the key/index accordingly.

**Comment by arderyp** [comment]
I don't really know what's going on here, because sometimes indexes are handles properly, and sometimes they are not.  I will close this, because I can't determine a pattern.  Something seems to be up though.

**Comment by stof** [comment]
In any case, the logic about deciding which SQL queries to execute is provided by doctrine/dbal.
