### ISSUE TITLE
Problem with executing INSERT/DELETE/UPDATE during the migration

### ISSUE THREAD

**Issue by olegkrivtsov** [doctrine/migrations#127]
Hello, I need to execute some inserts/deletions/updates on entities in the database during migrations. I tried to use the connection field of the migration, like below:

public function up(Schema $schema)
{
  $this->_connection->insert('user', array(
    'login' => 'admin',
    'name' => 'Admin',
    'password' => crypt('admin'),
    'status' => 1,
  ));
}

But when executing migrations, it prints the error message "No SQL commands found", unless I add this line:

$this->_version->markMigrated();

So, how am I supposed to perform INSERTS/DELETIONS/UPDATES on data during migration of the database?

Thanks for your help.

**Comment by msrumon** [comment]
I agree with what @olegkrivtsov said here: https://github.com/doctrine/migrations/issues/126#issuecomment-24369553. Devs shouldn't issue SQL queries directly. You should always use abstraction layers, to avoid any unwanted circumstances. I kinda summed up the issue with `insert()` method at https://github.com/doctrine/migrations/pull/362#issuecomment-779658040, a longer version can be found [here](https://symfony-devs.slack.com/archives/C3EQ7S3MJ/p1613458061249000) as well if anyone's interested.

**Comment by fnagel** [comment]
I found this issue as my migration with UPDATE and DELETE do not work:

```
public function up(Schema $schema): void
{
    $this->addSql('DELETE ...');
    $this->addSql('UPDATE ...');
}
```


> you should add the SQL to the list of queries being executed instead of executing them directly IMO, by using `$this->addSQL()`

Sounds like a should rather create statement using the query builder (`$this->connection->createQueryBuilder()`)? The docs say that UPDATE is fine, see https://www.doctrine-project.org/projects/doctrine-migrations/en/3.7/reference/migration-classes.html#addsql

Any idea what is best practice here?

**Comment by stof** [comment]
you can still use the query builder if you want, if you then do `$this->addSql($qb->getSQL(), $qb->getParameters(), $qb->getParameterTypes())` instead of using `$qb->execute()`.

**Comment by fnagel** [comment]
Thanks for your feedback!

I _can_ use? So it's _no must_ to use the query builder for UPDATE and DELETE statements? Because plain SQL statements in `addSql()` (see my code snippet above) seem not to work.

Still unsure how to do it the right way.

**Comment by stof** [comment]
Please open a new issue with the full detail ("does not work" is not debugable as is) instead of discussing that in a closed issue.
