### ISSUE TITLE
Access the logger inside a migration script

### ISSUE THREAD

**Issue by Kern046** [doctrine/migrations#1271]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I was implementing some logic in the `postUp` method of my migration class, and I would've liked being able to log some stats. I noticed that `AbstractMigration` has a injected instance of `LoggerInterface`, but as it is private, I can't use it.

As I use Symfony, I can easily manage with `ContainerAwareInterface`, but I think it would be more appropriate to use directly the injected `LoggerInterface`. Any particular reason to keep it private or can I create a Pull Request to make it protected or implement a getter ?

**Comment by stof** [comment]
The logger implementation injected into AbstractMigration is not your Symfony logger though. It is a special implementation in doctrine/migrations that writes to stdout.

**Comment by Kern046** [comment]
Actually it would also fit my needs :)

EDIT: In fact `write()` could totally make the job in that case. Thanks for helping me figuring it out !
