### ISSUE TITLE
doctrine:migrations:migrate doesn't execute more than one migration

### ISSUE THREAD

**Issue by JoDrm** [doctrine/migrations#1272]
|    Q        |   A
|------------ | -----
| Version     |3.2.2

### Support Question

Hello, 

I have actually 4 migrations in my folder Migrations, when I launch `doctrine:migrations:migrate` only the first migration pass. I have this logs : 

> [notice] Migrating up to DoctrineMigrations\Version20220827190131
> [warning] Migration DoctrineMigrations\Version20220812120107 was executed but did not result in any SQL statements.
> [warning] Migration DoctrineMigrations\Version20220812120108 was executed but did not result in any SQL statements.
> [warning] Migration DoctrineMigrations\Version20220827190131 was executed but did not result in any SQL statements.
> [notice] finished in 38.8ms, used 32M memory, 4 migrations executed, 1 sql queries

In my table of migration version all migrations is referenced but `execution_time` is set to 0.

How can doctrine pass all migrations one by one and not just the first one and reference the other with `execution_time` to 0 ?

**Comment by stof** [comment]
Well, if the 2nd to 4th migrations did not generate any SQL queries, getting an `execution_time` of 0 is quite expected. That's indeed the time it takes to execute 0 queries.

To know why they generated no statements, we would need to see the content of your 4 migration files.

**Comment by JoDrm** [comment]
Second migration : 

    public function upgrade(Schema $schema): void
    {
        $this->addSql("ALTER TABLE templates ADD hidden BOOLEAN DEFAULT false NOT NULL");
        $this->addSql("ALTER TABLE templates DROP image");
        $this->addSql("ALTER TABLE operations DROP COLUMN image;");
    }

    public function downgrade(Schema $schema): void
    {
        $this->addSql("ALTER TABLE templates DROP hidden");
        $this->addSql("ALTER TABLE templates ADD image string DEFAULT 'https://cdn.legal-pilot.com/img/models/model_1.jpg'");
        $this->addSql("ALTER TABLE operations ADD image string DEFAULT 'https://cdn.legal-pilot.com/img/models/model_1.jpg'");
    }


Third migration : 

    public function upgrade(Schema $schema): void
    {
        $this->addSql("INSERT INTO questions_types (code, datatype_code, name, position, has_choices, default_type) VALUES ('number'::varchar(45), 'text'::varchar(20), 'Nombre'::varchar(100), 6::smallint, false::boolean, null::boolean)");
    }

    public function downgrade(Schema $schema): void
    {
        $this->addSql("DELETE FROM questions_types WHERE code LIKE 'number' ESCAPE '#'");
    }


4th migration : 

    public function upgrade(Schema $schema): void
    {
        // this upgrade() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE IF EXISTS dataset_entity_dataset_column DROP CONSTRAINT fk_973759ea15ded2ef');
        $this->addSql('ALTER TABLE IF EXISTS dataset_entity_dataset_column DROP CONSTRAINT fk_973759ea2a752167');
        $this->addSql('DROP TABLE IF EXISTS dataset_entity_dataset_column CASCADE');
        $this->addSql('ALTER TABLE IF EXISTS dataset_values ALTER content TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE IF EXISTS teams ADD IF NOT EXISTS color VARCHAR(20) DEFAULT NULL');
        $this->addSql('UPDATE teams SET color = \'#DCEBF0\'');
    }

    public function downgrade(Schema $schema): void
    {
        // this downgrade() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE dataset_entity_dataset_column (dataset_entity_id INT NOT NULL, dataset_column_id INT NOT NULL, PRIMARY KEY(dataset_entity_id, dataset_column_id))');
        $this->addSql('CREATE INDEX idx_973759ea2a752167 ON dataset_entity_dataset_column (dataset_column_id)');
        $this->addSql('CREATE INDEX idx_973759ea15ded2ef ON dataset_entity_dataset_column (dataset_entity_id)');
        $this->addSql('ALTER TABLE dataset_entity_dataset_column ADD CONSTRAINT fk_973759ea15ded2ef FOREIGN KEY (dataset_entity_id) REFERENCES dataset_entities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dataset_entity_dataset_column ADD CONSTRAINT fk_973759ea2a752167 FOREIGN KEY (dataset_column_id) REFERENCES dataset_columns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teams DROP color');
        $this->addSql('ALTER TABLE dataset_values ALTER content TYPE VARCHAR(70)');
    }
}


I create a custom AbstratMigration file and CustomTemplate for change the name of the function up and down.

AbstractMigration.php :

```php
 public static bool $upHasBeenCalled = false;
    public static bool $downHasBeenCalled = false;

    abstract public function upgrade(Schema $schema);
    abstract public function downgrade(Schema $schema);

    public function up(Schema $schema): void
    {
        if (self::$upHasBeenCalled) {
            return ;
        }

        $this->upgrade($schema);
        self::$upHasBeenCalled = true;
    }

    public function down(Schema $schema): void
    {
        if (self::$downHasBeenCalled) {
            return ;
        }

        $this->downgrade($schema);
        self::$downHasBeenCalled = true;
    }
```
custom-template.tpl : 

```
    public function getDescription(): string
    {
        return '';
    }

    public function upgrade(Schema $schema): void
    {
        // this upgrade() migration is auto-generated, please modify it to your needs
       <up>
    }

    public function downgrade(Schema $schema): void
    {
        // this downgrade() migration is auto-generated, please modify it to your needs
        <down>
    } <override>
```

If I pass each migration one by one it runs fine.

**Comment by stof** [comment]
The issue is that you use a static property. So when calling `up()` on the first migration, `self::$upHasBeenCalled` is set to `true`, and next migration return early without calling the `upgrade()` method.

To me, you should remove that property entirely, always forwarding the call.

**Comment by JoDrm** [comment]
Ohh yes thanks you !!! You save my day !
