### ISSUE TITLE
Deprecate passing arguments for `--all-or-nothing` command option

### ISSUE THREAD

**Issue by agustingomes** [doctrine/migrations#1304]
During the resolution of a bug with the `--all-or-nothing` command option, it was suggested to deprecate passing values with the option, and as consequence, treat the presence of the option as `true` from version `4.0.x` onwards. 

[reference](https://github.com/doctrine/migrations/pull/1296#issuecomment-1376282500)

**Comment by agustingomes** [comment]
@greg0ire since the related PR was merged, should this issue be closed?

**Comment by greg0ire** [comment]
Yes, thanks again for this!
