### ISSUE TITLE
Generating the same migrations over and over again for the numeric field

### ISSUE THREAD

**Issue by dragu** [doctrine/migrations#1316]
### Bug Report

The same migrations are generated all the time.
Worked fine in 2.3.5.

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 3.5.5

#### Summary

up:
`$this->addSql('ALTER TABLE table CHANGE field field NUMERIC(14, 6) DEFAULT \'0.6\'');`

down:
`$this->addSql('ALTER TABLE table CHANGE field field NUMERIC(14, 6) DEFAULT \'0.600000\'');`

#### Current behavior

When the database query is executed, the default value does not change (it is still 0.600000), so migrations are generated over and over again with the same queries.

#### How to reproduce

1. Create table with field NUMERIC(14, 6) DEFAULT '0.600000'
2. Any make:migration creates the same queries again

Server: 10.4.27-MariaDB-1:10.4.27+maria~deb10-log and 8.0.32-0ubuntu0.20.04.2

#### Expected behavior

Migration is not generated because the value 0.6 cannot be set.

**Comment by abunch** [comment]
I'm seeing the same thing on 3.5.0.

**Comment by vaughnskinner** [comment]
FWIW I found that if I put quotes around the default value in the Entity annotation, that this repeated update stopped.

This:
`#[ORM\Column( type: Types::DECIMAL, precision: 10, scale: 2, options:["default" => "0.00"])]`

Instead of:
`#[ORM\Column( type: Types::DECIMAL, precision: 10, scale: 2, options:["default" => 0.00])]`

**Comment by stof** [comment]
Specifying the default value as a float is indeed invalid (casting the float `0.00` as string will not produce a numeric string with 2 decimals)

**Comment by dragu** [comment]
> FWIW I found that if I put quotes around the default value in the Entity annotation, that this repeated update stopped.
> 
> This: `#[ORM\Column( type: Types::DECIMAL, precision: 10, scale: 2, options:["default" => "0.00"])]`
> 
> Instead of: `#[ORM\Column( type: Types::DECIMAL, precision: 10, scale: 2, options:["default" => 0.00])]`

I already have the string in the column definition

> #[ORM\Column(type: 'decimal', precision: 14, scale: 6, nullable: true, options: ['default' => '0.6'])]

**Comment by stof** [comment]
@dragu you need a string that corresponds to your scale. `'0.600000'` and `'0.6'` are not the same strings.

**Comment by dragu** [comment]
> @dragu you need a string that corresponds to your scale. `'0.600000'` and `'0.6'` are not the same strings.

That's the point, thanks
