### ISSUE TITLE
GlobFinder looking for ONLY Version*.php

### ISSUE THREAD

**Issue by rendix2** [doctrine/migrations#1357]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | I have now idea how to find it

#### Summary

I can't rename migration file from Version{date} to Migration{date}

#### Current behavior

I HAVE to use illogical naming Version. But I'm extending Migration. It does not make any sence.

#### How to reproduce

Rename Version{date}.php to Migration{Date}.php as it SHOULD be.

#### Expected behavior

Find what whatever file I want

**Comment by greg0ire** [comment]
Manners.
