### ISSUE TITLE
Escaping a backslash requires 3 backslashes?

### ISSUE THREAD

**Issue by stefantalen** [doctrine/migrations#136]
Is it default behavior to use 3 backslashes to get one backslash in my database when using migrations?

Using two backslashes results in no backslashes in my table.

I have to use this in order to get it working

``` php
$this->addSql("INSERT INTO report_category (name, baseEntity, image, slug) VALUES ('demo', 'Acme\\\DemoBundle\\\Entity\\\DemoEntity', 'bundles/acmedemo/images/demo.png', 'demo')");
```

**Comment by gggeek** [comment]
Even in php single quoted string literal, two consecutive backslash chars are actually interpreted as a single one, as mentioned at https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single
