### ISSUE TITLE
Migration with a binary type

### ISSUE THREAD

**Issue by lecneri** [doctrine/migrations#1376]
I'm trying to create a migration with uuid as follow
```php
$table = $schema->createTable('t');
$table->addColumn('id', Types::BINARY, [
    'comment' => '(DC2Type:uuid)',
    'notnull' => true,
    'length' => 16,
]);
```
What happens is Types::BINARY returns string 'binary', which is mapped to [varbinary](https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/reference/types.html#mapping-matrix) and after my migration command runs, it executes an extra migration modifying the column to binary type.

This last modification messes with any migration that has foreign key added, because it can't change type anymore.

To notice this extra command running, I used `doctrine:migrations:migrate -vv`

**Comment by derrabus** [comment]
Does it work if you omit the `comment` setting?

**Comment by lecneri** [comment]
Hello @derrabus thank for your reply
Today I tried to setup a micro project to reproduce this error, and it didn't happened. So I used `composer update` and I'm not getting the extra migration anymore.

Although, can you explain when I do `php bin/console make:migration` the script generated uses binary and if I use $schema to be more abstract it uses varbinary?

**Comment by derrabus** [comment]
> Although, can you explain when I do `php bin/console make:migration` the script generated uses binary and if I use $schema to be more abstract it uses varbinary?

Not without knowing more about your project. And at this point, this issue shifts from a bug report to a support question. Please use StackOverflow, https://github.com/doctrine/orm/discussions/ or https://github.com/symfony/symfony/discussions/ for those.

If you feel like you've hit a bug, feel free to open a new issue with detailed steps for reproducing your bug.
