### ISSUE TITLE
Allow multiple versions in doctrine:migrations:version command

### ISSUE THREAD

**Issue by ralphje** [doctrine/migrations#142]
In some cases it is useful to mark all migrations upto a certain point as completed. I'd suggest the following syntax for this:

    doctrine:migrations:version --add version1..version2

This would mark all versions between (and including) version1 and version2 as added. Note that version1 and version2 do not need to exist; only at least one version should be between those values (and an error may be thrown otherwise). (That would allow version1 to be 0, or version2 to be 99999999999999).

Similar syntax could be used for other commands where it makes sense.

**Comment by mikeSimonson** [comment]
@ralphje Can you provide a PR ?
