### ISSUE TITLE
Static variables are persisted across migrations, breaking cache logic.  Each migrations should be independent, and carry its own PHP request.

### ISSUE THREAD

**Issue by bs-thomas** [doctrine/migrations#1420]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.4.3 (and also newer versions)

#### Summary

Consider I have 2 migration versions in my stack: Version 001, and Version 002.

Version 001: Creates a "user" table, makes a few inserts, and a few selects.
Version 002: Adds a new column to the "user" table, makes a few inserts, and a few selects.

Inside Version 001, it creates a "user" table, makes a few user inserts, and then when selecting these new users, it needs to find out what the columns are for the user table, and thus it makes a database call to retrieve that.  Since this needs to be retrieved multiple times within the same PHP request, there is a cache logic implemented to remember these columns in the table.  It makes use of a static variable inside a static class method.
So now, it remembers the "user" table has 2 columns: "user_id", and "user_name"

Inside Version 002, it makes a modification to the "user" table, and adds a new column (eg. "user_age").  Then, it will further make a few new user inserts.  When making user inserts, it needs to find out what the columns are for the user table, and thus will make use of the same static method used inside Version 001.

But this time, it finds a cache (the static variable, cached in Version 001), and returns that the "user" table has 2 columns.  But this is **incorrect**, as there should be 3 columns now.  This is because the "static variable" from Version 001 persisted.

#### Current behavior

There is persistence on static variables between migration.

**Note that**, if I execute Version 001 migration first, and execute Version 002 separately afterwards (not in one go), then the problem does not occur (because they are separated into 2 different PHP requests).  But if I migrate versions altogether in one go, where it makes use of the same PHP request across both migrations, this problem will arise.

#### How to reproduce

See summary.

#### Expected behavior

If I migrate Versions 001 and 002 separately, then the problem does not occur (because they are separated into 2 different PHP requests).  But if I migrate versions altogether, where it makes use of the same PHP request across both migrations, this problem will arise.

Expected behavior is that regardless if I run all migration versions in one go, or run them separately, the result should be the same.

There should not be any static variable persistence between migration versions.  (In other words, each migration should be run by in its own PHP request).

**Comment by stof** [comment]
Starting a new PHP process for each migration would have a huge performance impact for the execution of migrations, which seems a no-go.

I suggest you to fix that in your project: register a listener for the `onMigrationsVersionExecuted` or `onMigrationsVersionExecuting` event (not sure which one of them is best for your case) that would clear your cache between migrations.

**Comment by derrabus** [comment]
This is how static variables work. Using a static variable as a cache was a bad call on you side, sorry. For the reasons given by @stof, this bug report is not actionable for us.

**Comment by bs-thomas** [comment]
Thanks for your quick response.  I appreciate it.

I can understand it is a performance impact for doctrine.  And I did think about it, and also agree so.  So I will try to find an alternative for this.

@derrabus  While I appreciate your advice, actually I don't quite understand why it was a bad idea.  From my understanding, the use of static variable caching is actually quite a common use-case scenario for request-based caching, especially when PHP was made to be "request independent".  Also for my use-case, it was not "object-dependent", so all instances of that same class are going to have the same table columns, so "static" seems to be the way to go.  Or did I misunderstand something here?

** I understand this is off-topic already, just a friendly social discussion, just hoping to learn from you a little more :-)

**Comment by stof** [comment]
@bs-thomas static variables are not request-based. They are process-based.
