### ISSUE TITLE
`--all-or-nothing` without value computes to `false`

### ISSUE THREAD

**Issue by MatTheCat** [doctrine/migrations#1443]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | not sure
| Version     | 3.7.4

#### Summary

There seems to be a discrepancy between this deprecation: https://github.com/doctrine/migrations/blob/535a70dcbd88b8c6ba945be050977457f4f4c06c/src/Tools/Console/ConsoleInputMigratorConfigurationFactory.php#L46-L49
and this test: https://github.com/doctrine/migrations/blob/535a70dcbd88b8c6ba945be050977457f4f4c06c/tests/Tools/Console/Command/MigrateCommandTest.php#L384
which asserts that `--all-or-nothing` without value will compute to `false`.

#### Current behavior

Running a migration with the `--all-or-nothing` option without value, “all or nothing” mode is disabled (whatever the value from the configuration).

#### How to reproduce

Run a migration passing the `--all-or-nothing` option without value.

#### Expected behavior

“All or nothing” mode is enabled.

**Comment by greg0ire** [comment]
@agustingomes can you please look into it?

**Comment by agustingomes** [comment]
@greg0ire I'll try during the weekend. Likely is the deprecation text that should be adjusted.

**Comment by MatTheCat** [comment]
Maybe this is due to the fact I’m using the DoctrineMigrationsBundle which defaults `all_or_nothing` to `false`?

Either way passing this option to the CLI and not having it enabled came as a surprise.

**Comment by MatTheCat** [comment]
Note that it seems the current behavior doesn’t match [the documentation](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.8/reference/configuration.html#from-the-command-line) either:

> You can also set this option from the command line with the `migrate` command and the `--all-or-nothing` option:
> ```
> ./vendor/bin/doctrine-migrations migrate --all-or-nothing
> ```

**Comment by agustingomes** [comment]
@MatTheCat @greg0ire I created a PR with an initial iteration of the possible fix: https://github.com/doctrine/migrations/pull/1444

Let's discuss in the PR how to move forward.

**Comment by agustingomes** [comment]
I believe this issue may now be closed with the new `3.8.1` release

https://github.com/doctrine/migrations/releases/tag/3.8.1

**Comment by MatTheCat** [comment]
That was fast! Thanks ♥️
