### ISSUE TITLE
Migrations are ordered name if migrations has name

### ISSUE THREAD

**Issue by KeNJiKunG** [doctrine/migrations#146]
Migration will ordered by migration's name if migration implemented getName method.

I don't know that this is intended behavior or not.

**Comment by mikeSimonson** [comment]
That method should probably be final to avoid that.

**Comment by mikeSimonson** [comment]
@Ocramius What about the BC break if I put the getName() method as final ?

It feels like it would be a bug to let it non final even thought it's probably going to break some people migrations.

**Comment by Ocramius** [comment]
@mikeSimonson why would this be the correct solution in first place?

**Comment by mikeSimonson** [comment]
Well I feel like it would be confusing to have one order in the folder and then a different order in the execution of the migration file because some name are overridden by the getName() but I am not sure that it's the best solution.

**Comment by mikeSimonson** [comment]
It's related to this PR #100

**Comment by mikeSimonson** [comment]
@Ocramius Is there a better solution to that issue than putting the getName as final ?

**Comment by Ocramius** [comment]
@mikeSimonson I'm wondering if we can stop relying on `getName` in first place

**Comment by mikeSimonson** [comment]
It looks like it would be possible.

The addition comes from this commit https://github.com/doctrine/migrations/commit/aab5b209a69a9b513ed7a89ba6404ef53e50e1e4 .

And the PR #100 would probably makes more sense in my opinion if the goal is to only have a more descriptive name.

It's not clear to me if that getName() was added when doctrine migration was tagged 1.0alpha1 or not and if removing it means a BC breaks.
It has been there for 4 years...

**Comment by stof** [comment]
@mikeSimonson I think we could keep it for the descriptive name, but using a different (final) method for the sorting.
