### ISSUE TITLE
#[ORM\Column(type:'text', columnDefinition:'JSON')] causes needless diff

### ISSUE THREAD

**Issue by tomasfejfar** [doctrine/migrations#1462]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     |  3.8.1

#### Summary

When I create a column with following attribute
```
#[ORM\Column(type:'text', columnDefinition:'JSON')]
```

when i run `bin/console d:m:diff` I get the correct definition
```
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversations ADD agent_memory JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversations DROP agent_memory');
    }
```

#### Current behavior

Then when I run `bin/console d:m:diff` I get:

```
public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        ...
        $this->addSql('ALTER TABLE conversations CHANGE agent_memory agent_memory JSON');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        ...
        $this->addSql('ALTER TABLE conversations CHANGE agent_memory agent_memory JSON DEFAULT NULL');
    }
``` 

#### How to reproduce

See above

#### Expected behavior

No change or only relevant change generated in the diff. 

#### Note

I tried to change the columnDefinition to `#[ORM\Column(type:'text', columnDefinition:'JSON DEFAULT NULL')]` to no avail. It still creates the same diff. Only this time both up and down are the same with `JSON DEFAULT NULL`. 

Is this intended behavior?

**Comment by stof** [comment]
Using `columnDefinition` means you override the behavior of DBAL regarding building the column, which will not play well with the schema comparator. If you want the schema comparator to work well (detecting properly when nothing should be changed), don't use `columnDefinition`

Use the `json` type of DBAL instead to have JSON.

**Comment by tomasfejfar** [comment]
I need the entity column to be json-string, not array (to not reparse whatever JSON is there). So I will need a custom type?

**Comment by stof** [comment]
then the good solution is indeed to use a custom type. This would make it work with the schema comparator

**Comment by tomasfejfar** [comment]
OK, thanks!
