### ISSUE TITLE
escaped namespaces don't work  in  single quotes

### ISSUE THREAD

**Issue by delboy1978uk** [doctrine/migrations#1467]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.8.2

#### Summary
The single quotes should be replaced by double quotes in the text output upon generating a migration diff, so that the pasted command does not fail due to the migration class not being found

#### Current behavior

The instructions for executing the migration uses single quotes:
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/e65b3e82-6cba-4c79-b3ff-af35168a875d">
When I copy paste as is, I get class not found.
<img width="711" alt="image" src="https://github.com/user-attachments/assets/8d849e4c-5635-45df-8698-b15fc71efb14">
If I change to using quotation marks `"`, it works:
<img width="551" alt="image" src="https://github.com/user-attachments/assets/8054fd65-88e0-427c-b7b5-9eba39898dd6">
 

#### How to reproduce

copy paste the execute down command and see if t runs

#### Expected behavior

It should run without failing

If you like, I can make the changes and send a PR.

**Comment by greg0ire** [comment]
> If you like, I can make the changes and send a PR.

Please do :pray: 

Another way to make it work might be to remove the double backslash and keep the single quotes.

**Comment by stof** [comment]
Given that single quotes don't work on Windows, I would suggest using double quotes in the command, to display a portable command.
