### ISSUE TITLE
MySQL 5.6 - Cannot change column 'fkProjectId': used in a foreign key constraint

### ISSUE THREAD

**Issue by cmodijk** [doctrine/migrations#148]
MySQL 5.6 is strict on altering tables with foreign key constraint's.

Generated SQL 

```
ALTER TABLE badges CHANGE fkProjectId fkProjectId INT NOT NULL
```

Result in the following error

```
Cannot change column 'fkProjectId': used in a foreign key constraint 'FK_1483A5E9F28AE4EA'
```

More info:
- http://stackoverflow.com/questions/17015844/mysql-5-6-foreign-key-constraint-error-didnt-occur-in-5-5
- http://dev.mysql.com/doc/refman/5.6/en/alter-table.html

```
As of 5.6.7, the server prohibits changes to foreign key columns with the potential to cause loss of referential integrity. A workaround is to use ALTER TABLE ... DROP FOREIGN KEY before changing the column definition and ALTER TABLE ... ADD FOREIGN KEY afterward.
```

**Comment by iBasit** [comment]
404 http://www.doctrine-project.org/jira/browse/DBAL-732

**Comment by stof** [comment]
Well, the DBAL issues have been migrated to Github in the meantime, and Jira has been shutdown.

**Comment by ndench** [comment]
Here's the github issue: https://github.com/doctrine/dbal/issues/1958
