### ISSUE TITLE
[DX] Help the user know how to test a migration file

### ISSUE THREAD

**Issue by weaverryan** [doctrine/migrations#173]
Hi guys!

One of the trickiest parts of using migrations are testing them. That's a tough workflow (and sometimes you'll just need to pull a production schema dump to test things).

After running a `generation` or `diff`, what about adding a message to tell the user how they could run this migration independently locally to test it:

> To run just this migration for testing purposes, you can use `migrations:diff --up 2014XXXXXXX`

Thoughts in general? Overall, I want to help people into the right migrations workflow - it's tough.

**Comment by allan-simon** [comment]
what is the status of this ticket ? As I see it's the only one left for the 1.0 milestone and there's already a PR opened on this

**Comment by lcobucci** [comment]
I've remove this from `v1.0` because it was already released without this feature. @mikeSimonson what should we do regarding this?

**Comment by mikeSimonson** [comment]
We should try to improve the documentation in general but also specifically regarding this.
