### ISSUE TITLE
tag migrations version

### ISSUE THREAD

**Issue by nysander** [doctrine/migrations#178]
is it possible to tag versions so I can use selected version of migrations not live master branch?

**Comment by nidup** [comment]
@beberlei @jwage @stof could you tag an alpha2 please ?

**Comment by BreiteSeite** [comment]
:+1:

**Comment by ecolinet** [comment]
+1

**Comment by mikeSimonson** [comment]
done.

There is an alpha3 now.
Please go test it and report bugs.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by nidup** [comment]
:+1:

**Comment by ecolinet** [comment]
thanks !

2015-03-23 8:34 GMT+01:00 Nicolas Dupont <notifications@github.com>:
