### ISSUE TITLE
Case Sensitivity in DiffCommand.php when using schema_filter(Oracle)

### ISSUE THREAD

**Issue by MSeven** [doctrine/migrations#179]
Basic setup Symfony 2.5 Project, Using Doctrine to access a Share database.

Consider a Oracle schema (DBSCHEMA) with multiple tables, of which we want to manage some using Doctrine Migrations. 

The tables we want to Manage are prefixed with a string eg. MIGTABLE1, MIGTABLE2.
There ofcourse are other tables are called diffrently XYSOMETABLE, ABSOMETABLE2

Do only allow access to the Migrationtabes, one would set a schema_filter like '~^MIG~' (note uppercase) which will properly filter all tables starting with MIG, and make all other tables inaccessible as intended in symfony.

Now, when Using the DiffCommand shell, the schema will Ignore ALL tables, and produce migrations removing MIGTABLE1 and MIGTABLE2.

Turns out this is an issue with the loop applying the schema_Filter rules in 
[DiffCommand.php Line 93](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/DiffCommand.php#L93)

the variable $tableName contains tables as lowercased string (e.g. dbschema.migtable1, dbschema.xysometable)  which is shortened to migtable1, xysometable (still lowercase).

Line 95 will apply the filter defined in schema_filter, which (usually) will look/Match for an Uppercase tablename.

Since "migtable1" will not match "~^MIG~", the tables are discarded from $toSchema.

Simply switching the schema_filter to lowercase "~^mig~" will make the migrations work, but also filter the tables when trying to access them inside the Symfony application.

The current Workaround is to use a regular extression that will match both upper and lowercase tablenames, which is quite unintuitive and (afaik.) not documented.

**Comment by mikeSimonson** [comment]
@MSeven To fix the issue that your table are filtered for the whole symfony application you just need to create 2 different connections and 2 different entity manager in the config one as default for symfony and the other one with the schema_filter for doctrine migration. You can the use the --em to use the filtered connection with doctrine migration.

@Ocramius Is there a reason to lowercase all the table name and not the schema filter rules ?

**Comment by Ocramius** [comment]
> Is there a reason

@mikeSimonson not really, it's just a side-effect: should be corrected.

**Comment by mikeSimonson** [comment]
What's the best way to correct that side effect ?

Make sure that the table name doesn't get lowercased or lowercase the schema_filter too ?

**Comment by deeky666** [comment]
@mikeSimonson the casing problem comes from `Schema::getTableNames()` which returns fullqualified, lowercased table names. I guess that method is not usable here. Maybe a `Schema::getTables()` and consecutive `$table->getName()` calls might fix the issue.
