### ISSUE TITLE
[feature] cumulative migration

### ISSUE THREAD

**Issue by ivan1986** [doctrine/migrations#180]
When long use migrations we get many small migrations sometimes revert some changes

Nice to see way to create one big migration from old cumulative to new (for example create it on new release)

current migrations

```
m01012000
m02012000
m03012000
m04012000
...
m01012010
```

new way

```
m01012000
m02012000
...
m31012000
c01022000
m01022000
...
c01012010
m02012010
```

and apply its - all cumulative and after last cumulative

**Comment by mikeSimonson** [comment]
@ivan1986 Sorry but I don't really understand that feature. What is the goal ?

**Comment by ivan1986** [comment]
@mikeSimonson this need for create one big file for migration to new wersion
auto create for reduce big list of migrations

**Comment by mikeSimonson** [comment]
It would concatenate all the up and all the down method from multiple migration in one right ?
This would be nice indeed.
Can you provide a PR for that ?

**Comment by mikeSimonson** [comment]
After some though I think that this solution makes more sense #310.
What do you think ?

**Comment by ivan1986** [comment]
@mikeSimonson 
No, it's just placing migration in folders
It can not grouped many small migrations in one

**Comment by mikeSimonson** [comment]
@ivan1986 
I don't really like the idea of having a piece of code that would modify another one losing all the context and documentation around that migration.

If you just want less file then maybe using the --writeSql option might be the simplest approach but again you loose all the context and the documentation.

**Comment by ivan1986** [comment]
@mikeSimonson 
not to change the other piece of code
you have 100 migrations that have been made in the development of the product at the ever-changing requirements, the implementation of these migrations takes 10-20 minutes, but in fact they create a well-established structure of the tables that were in the version 1.0, that you have developed two years ago.
Descendant there are 50 of migrations that are performed for 10 minutes and transferred to a table from version 1.0 to version 2.0, which was released six months ago and you are using another 10-20 migrations in the current master version that is developing in
I suggest creating migration to version 1 and version from 1 to version 2, and the removal of intermediate migrations entirely optional.

**Comment by mikeSimonson** [comment]
ok.

But I think that it's impossible to guarantee that an automatic process like that wouldn't loose data.
From what you describe, to me the only solution is to generate those migrations manually.

Otherwise it's impossible to guarantee the outcome.

What do you think @ivan1986 ?

**Comment by ivan1986** [comment]
what data? test data in developer database?
simple way to generate new cumulative migration is migrate down to latest cumulative migration and run migrate:diff

**Comment by DavidHavl** [comment]
This sounds more like a job for a separate build tool or a one time process tool, or a manual generation. 
And indeed one would likely loose all of the comments and documentation.

In git world it would be equivalent to saying lets suppress many git commits to one (rebase). Even though there may be a need for it in edge case scenarios I think it defeats the point of versioning.

**Comment by mikeSimonson** [comment]
Well if it's only for the schema, it looks like a hard feature to provide and it would probably be easier to do it by hand.

**Comment by DavidHavl** [comment]
Agree, this should not be part of this library IMHO.

**Comment by stof** [comment]
Well, there is a way to generate such migrations: get a database which is at version 1, and then run the diff command. This will give you the schema migration from v1 to v2, and it is much simpler than trying to parse old migrations to infer the old schema to build the migration.
Btw, be careful that a real migration involves migration data too, and you would have to redo all the work there in your big migration.

regarding the performance of running migrations, I suggest you to have a look at #323 which allows to improve the performance by 96%

**Comment by mikeSimonson** [comment]
@stof Yes, that's what I meant by "by hand".

I think that it's better to close this issue as that feature probably won't happen ? @ivan1986

**Comment by aromer** [comment]
I think there's a balance here. We can leave the consolidation of the migrations separately for a tool, or database dump, etc, but build a way to indicate the intent of an individual migration.

Example:
Version20161031104458.php
Version20161031104458_install.php

These two files would be functionally equivalent. The first one would be an incremental migration, and *_install would be a fresh consolidation of all the previous migrations. When running migrate() on an empty table, it would start with the most recent install migration, and then run all the incremental migrations after that.

**Comment by stof** [comment]
Well, running a different migration when the DB is empty is dangerous IMO, as it could have a different behavior, leading to WTF. Thus, it would require adding introspection at runtime to detect that the DB is empty, which takes time (and would harder if your DB also contains extra tables not meant to be handled by your migrations)

**Comment by stof** [comment]
thus, it would also make it harder to handle tracking of applied migrations, as the library would have to know which migrations are consolidated into your migration

**Comment by ivan1986** [comment]
@aromer 
It is not for direct production use.
But how we a develop app?
Vagrant or docker env for each developer.
Test envs for every build on CI server.
For all this envs run full migrations from zero database.

**Comment by stof** [comment]
@ivan1986 but if you have no guarantee that the migrated DB will be the same, nobody will agree using this on the CI server, as they want the DB to be the same than the prod one.

Btw, if you write migrations using SQL queries (which is what the ORM generates) instead of using the Schema instance, the migrations will run very fast.
On my work project (with 222 migrations currently), executing migrations from scratch takes 5s.

**Comment by aromer** [comment]
Yes, running a different migration could potentially have different behavior. But the same thing could apply for up() and down() as well. But that burden should be put on the developer/code generating the equivalent queries, not on the script executing them since the entire purpose of consolidating is to not have to run the individual migrations that would be necessary for that verification. There could be a separate helper script that could confirm that the output is equal.

Checking if the DB is empty isn't necessary. Existing functionality is to check if "migration_versions" exists. If it doesn't, it creates it and starts with the first migration. And would spit out a SQL error if the table is not empty. This is no different from running migration #1, the only difference is whether it's an incremental migration, or a consolidated one.

Tracking applied migrations could still be extremely simple. By asserting that a consolidated / fresh install migration is equivalent then the first migration version entered in the migrations table would be the consolidated migration that was run, and then only incremental migrations newer then that would be applied on top of it.

**Comment by stof** [comment]
But then, to decide which incremental migrations should run, it needs to detect whether they were before or after a consolidated one => lots of additional complexity.

And if we record the consolidated migration itself in the DB, it becomes worse if you want to migrate back to a point before the consolidation (reverting only *part* of it)

**Comment by aromer** [comment]
To be clear, what I'm proposing is a slightly different implementation then the original poster. The only consolidated migration that would ever be run in my proposal would be the newest consolidation/install which is the very first to be run in a fresh install with no dataset.

V1_0.php
V1_1.php
V2_0.php
V2_0_install.php
V2_1.php
V3_0.php
V3_0_install.php

Seems like most of the logic could be handled here:

Doctrine/DBAL/Migrations/Configuration::getMigrationsToExecute()

As long as there was a strict convention to specify which ones are equal it shouldn't be complex, for example using two different filenames with the same timestamp.

Example:
Version20161031104458.php
Version20161031104458_install.php

Even downgrades shouldn't be too hard to calculate. Although there is even a case to specifically not support downgrades. How often does someone do a fresh install of version 2.0 and want to downgrade to a 1.x version they never used? Often those forward migrations are irreversible anyways. There could also be a config flag to specific whether to use the consolidated or individual migrations when it's run.

**Comment by mikeSimonson** [comment]
I have the impression that there is a lot of mix-up in this feature request.

If you don't have data to migrate you don't need doctrine migration, you can just use doctrine:schema:update --force and you are set.

If you have data to migrate and you try to merge multiple migration in one big file you are settting yourself up for disaster when something will brake. Been there done that ...

**Comment by greg0ire** [comment]
I used to run migrations in my project b/c the team keeps forgetting to make them when they change the schema, making other parts of the team (me) mad at them. Also, this can happen when you have bundles that can change the schema (fos user bundle, for instance) and you update them without noticing that.

They then disabled it b/c the build was too long. I now have to do the merge described here b/c they keep forgetting making migrations…

> If you have data to migrate and you try to merge multiple migration in one big file you are setting yourself up for disaster when something will brake. Been there done that ...

If you have done this migration 6 months ago though, what is the point in keeping it? Migrations are useful if you want to rollback, but you're not going to do that 6 months later, are you?

My plan to do the cumulative file : 

1. Remove all migration files
2. Drop my schema
3. Truncate the migration versions table
4. Generate a new migration from the diff
5. Load the production database into dev
6. Truncate the migration versions table again
7. Insert the newly created version in the migration versions table
8. check that the migration diff is empty
9. deploy everywhere, and do 6 and 7 there.

I'll keep you posted on the results.

**Comment by aromer** [comment]
We just did something similar. We just launched version 4.0 of our platform. It was a big release in which we deprecated some older features. We used migrations to track schema changes, but we dropped several tables. We can rollback the schema, but since we deleted legacy data along with the tables (we did store a backup for the archives), there is no need to keep the migrations. So with the 4.0 release we also deleted all the old migrations (still tracked in git), and made a fresh migration with the entire schema for a fresh install of 4.0, which is equivalent to the aggregation of all the migrations before it.

**Comment by greg0ire** [comment]
> still tracked in git

That's key to avoid a disaster. My collegue finally cleaned the migrations, which means I can wrap this up. I added additional instructions above.

**Comment by lcobucci** [comment]
I've removed this from `v1.2` since it was already released without this feature. @mikeSimonson should we still implement it?

**Comment by mikeSimonson** [comment]
@lcobucci I don't think that it's worth the effort but if someone wants a stab at it ...

**Comment by jwage** [comment]
I think what is being described here is a "rollup" feature?

Basically, over time you accumulate many migrations that build up the schema one step at a time. If you rely on migrations to create your schema from version 0 to current for your tests to run against, then over time it can start to take a really long time to create your schema before your tests can run. You can either periodically rollup all your historical migrations in to 1 migration that just creates the whole schema and then make changes from there with new migrations. Or you can stop relying on the migrations to create your initial schema for tests or your "install". In my project, I decided to maintain a `schema.sql` and `data.sql` and just run that directly with mysql before my tests run. You do have to then create a migration and update the schema.sql but for me it was a decent tradeoff to keep the speed of functional tests fast.

**Comment by lcobucci** [comment]
@jwage it's definitely feasible I just wonder if this is a "must have" or a "nice to have" feature... 

I don't see consensus in the comments here and based on my experience I wouldn't use this kind of feature because for me it sounds just like squashing all commits in `master` because history got messy (kind of exaggerated, but that's my 2 cents 😄) .

**Comment by jwage** [comment]
I don't think it's necessary either. Especially since you can basically just do this yourself manually pretty easily.

**Comment by jwage** [comment]
I added more thoughts on this here #662
