### ISSUE TITLE
Usability improvements for migrations with addSql and parameters

### ISSUE THREAD

**Issue by gbirke** [doctrine/migrations#186]
The `addSql`method accepts parameters for creating inserting in a query. This is very useful for data migrations. However, the usability could be improved:

1) By adding an example to the docs that uses placeholders and a parameters array (or links to http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html where the placeholder syntax is explained)

2) By including them in the output of `--dry-run`

**Comment by mikeSimonson** [comment]
@gbirke @metalmini 
Can you explain what you mean by adding them in the output of --dry-run ?

**Comment by aaa2000** [comment]
I think that adding them in the output of --dry-run means:

`$this->addSql('INSERT INTO FOO VALUES(?)', [10]);`


`migrations:migrate --dry-run` should not only display like that 

`INSERT INTO FOO VALUES(?)`

but rather 

`INSERT INTO FOO VALUES(?) with parameters [10]`

But there will be problems with big parameters array. (With long text, binary value)

**Comment by mikeSimonson** [comment]
Well I would accept both the PR on the doc and the dry run improvements.
