### ISSUE TITLE
Change index names does nothing

### ISSUE THREAD

**Issue by Soullivaneuh** [doctrine/migrations#191]
If I change this index:

```php
/**
 * @ORM\Table(name="invoice", indexes={
 *     @ORM\Index(name="created_at_idx", columns={"created_at"}),
 * })
 */
```

To this:

```php
/**
 * @ORM\Table(name="invoice", indexes={
 *     @ORM\Index(name="created_at_index", columns={"created_at"}),
 * })
 */
```

And try to create a migrations: `./app/console doctrine:migrations:diff`, nothing happen.

Seems doctrine does not care about index name changing.

Is this normal?

**Comment by mikeSimonson** [comment]
@Soullivaneuh You need to report the bug to the doctrine orm bug tracker.

**Comment by Soullivaneuh** [comment]
@mikeSimonson Where is this bug tracker ?

**Comment by Soullivaneuh** [comment]
@mikeSimonson Where is this tracker ?

**Comment by mikeSimonson** [comment]
http://www.doctrine-project.org/jira/secure/Dashboard.jspa

**Comment by Soullivaneuh** [comment]
Thanks @mikeSimonson but I just tested on `2.4.6` and `2.4.7`, seems to be fixed! :+1:
