### ISSUE TITLE
Migrations up and down differ in case for a table name

### ISSUE THREAD

**Issue by khasinski** [doctrine/migrations#197]
I've changed one field in my model from not null to default null, generated a migration using diff and got:

    class Version20150105175136 extends AbstractMigration
    {
        public function up(Schema $schema)
        {
            // this up() migration is auto-generated, please modify it to your needs
            $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

            $this->addSql('ALTER TABLE badge ALTER company_id DROP NOT NULL');
        }

        public function down(Schema $schema)
        {
            // this down() migration is auto-generated, please modify it to your needs
            $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

            $this->addSql('ALTER TABLE Badge ALTER company_id SET NOT NULL');
        }
    }

Please note the name Badge and badge in up and down migrations. Is this a bug?

**Comment by stof** [comment]
This should be reported in the [issue tracker of the DBAL project](http://www.doctrine-project.org/jira/browse/DBAL), because the Migrations project is not responsible for computing the schema changes.

**Comment by khasinski** [comment]
I've put it on their bugtracker, it's available here: http://www.doctrine-project.org/jira/browse/DBAL-1107
