### ISSUE TITLE
DB2 Migrations Error - SQL0206N

### ISSUE THREAD

**Issue by blancoms** [doctrine/migrations#199]
[Doctrine\DBAL\Driver\IBMDB2\DB2Exception]                                                                                      
[IBM][CLI Driver][DB2/LINUXZ64] SQL0206N  "VERSION" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206 

Reason:
"Version" is a reserved word in DB2.

Quick solution:
You need to escape the "version" column name in the following files:
lib/Doctrine/DBAL/Migrations/Version.php
lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php

Note:
Single quotes ('version') doesn't work in all the queries. You should escape them like this \"version\"

**Comment by deeky666** [comment]
@blancoms this is a DBAL issue. Please open a ticket in [JIRA](http://www.doctrine-project.org/jira) and we will take care of it. Thanks.
@stof close please.
