### ISSUE TITLE
Clarification on the license in composer.json

### ISSUE THREAD

**Issue by valioDOTch** [doctrine/migrations#200]
I currently oversee the licenses used in our projects

I would like to ask you to clarify the license in composer.json in order to comply with the license identifiers as listed by SPDX
http://spdx.org/licenses/
i.e. replace line 7 in composer.json either with `"license": "LGPL-2.1",` or `"license": "LGPL-2.1+",`

Reasoning:
"LGPL" could imply any version of the license, some of which have certain (usually, but not always, minor) consequences for derivative works.
For details e.g. see http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
Given the files in this repository, it was not entirely clear to me whether you intended to apply solely 
"LGPL-2.1" or "LGPL-2.1+" (LGPL 2.1 or later) as this can only be decided by the copyright notice present within the files. The only copyright notices I found pointed to http://www.opensource.org/licenses/lgpl-license.php which could imply either interpretation, as this website lists LGPL 2.1 and 3.0 together.

**Comment by stof** [comment]
@beberlei any reason why this repository was not migrated to MIT at the same time than all other Doctrine repositories ?

**Comment by stof** [comment]
And regarding the license itself, it is LGPL 2.1. See the LICENSE file in the repo: https://github.com/doctrine/migrations/blob/96f838b4fa93693d19196c8e24ed5f1c3972ba87/LICENSE

**Comment by valioDOTch** [comment]
@stof The license file itself does not make it clear, wheter it is "LGPL 2.1" or "LGPL 2.1 or any later version"
Please read article 13 of the license (you just linked) in detail. Then you may understand what argument I made above. Solely putting this file in a repository does not declare by itself whether you intended to let the source to become "LGPL 2.1" or "LGPL 2.1 or any later version".

**Comment by jrobeson** [comment]
@valioDOTch : does the source have the (or any later version) text anywhere?

**Comment by jrobeson** [comment]
ah yes it has it in the license file itself.  https://github.com/doctrine/migrations/search?utf8=%E2%9C%93&q=or+any+later

**Comment by jrobeson** [comment]
i just submitted a PR to clarify it until the project is properly relicensed to MIT.

**Comment by valioDOTch** [comment]
thanks

**Comment by beberlei** [comment]
@stof we forgot to include migrations in the license switch. That means we cannot easily do it except asking all the contributors again.
