### ISSUE TITLE
Cannot generate PHAR

### ISSUE THREAD

**Issue by bizmate** [doctrine/migrations#208]
cloned the project,

change the phar.readonly option to Off in php.ini

run git submodule init and submodule update (this installed nothing)

running php package.php causes this error:

[vagrant@localhost doctrine-migrations]$ php package.php
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/v
ar/tl-www/doctrine-migrations/vendor/doctrine/dbal/lib): failed to open dir: No such file or directory' in /var/tl-www/d
octrine-migrations/package.php:37
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('/var/tl-www/doc...', 12288)
#1 /var/tl-www/doctrine-migrations/package.php(37): Phar->buildFromDirectory('/var/tl-www/doc...', '/Doctrine/')
#2 {main}
  thrown in /var/tl-www/doctrine-migrations/package.php on line 37

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/var/tl
-www/doctrine-migrations/vendor/doctrine/dbal/lib): failed to open dir: No such file or directory' in /var/tl-www/doctri
ne-migrations/package.php:37
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('/var/tl-www/doc...', 12288)
#1 /var/tl-www/doctrine-migrations/package.php(37): Phar->buildFromDirectory('/var/tl-www/doc...', '/Doctrine/')
#2 {main}
  thrown in /var/tl-www/doctrine-migrations/package.php on line 37

What can I do to fix this or where can the phar be downloaded?

**Comment by mikeSimonson** [comment]
Try ```composer install```

The Readme should be updated but there is is link on the top with a working phar.

**Comment by bizmate** [comment]
Thanks Mike
I created the PR to update the readme
