### ISSUE TITLE
"addSql" method name inconsistent between .phar & source

### ISSUE THREAD

**Issue by garethellis36** [doctrine/migrations#213]
Apologies if I'm missing something... but if you download the .phar linked from the project's Github page, the following code results in a method not missing exception.

Within a migration class up() method:
```
$this->addSql("some sql");
```

```
Fatal error: Call to undefined method DoctrineMigrations\VersionXXXX::addSql()
```

I did `var_dump(get_class_names($this))` and it revealed that the method name is `_addSql`.

This looks to be inconsistent vs. the source code and the documentation. Sorry if I am missing something...

**Comment by stof** [comment]
@garethellis36 the phar is totally outdated. Either don't use it, or build it again from the sources first. The phar link is not maintained (it even points to a github feature which has been shutdown)

**Comment by mikeSimonson** [comment]
I will try to update the phar for next week.

**Comment by stof** [comment]
@mikeSimonson the right way would be to ship the phar using github releases for each of our tags. So you would need to tag a release first for that.
Note that we should probably replace the phar generation to using [Box](http://box-project.org/) first, instead of maintaining our own code to build the phar

**Comment by mikeSimonson** [comment]
@stof That exactly all I plan to do :+1:

**Comment by garethellis36** [comment]
Thanks for clarification. I can submit a PR to update the readme if
necessary?

**Comment by mikeSimonson** [comment]
Wel I would prefer to do the work before the README gets updated but you can make a PR and I can ping you if you want when it's done.

**Comment by garethellis36** [comment]
How do I use without the .phar? Presumably something like this:

```
php migrations.php migrations:generate
```

What file do I point php to?

**Comment by mikeSimonson** [comment]
@garethellis36 The phar is updated as the Readme 

```php bin/doctrine-migrations.php migration:generate````
