### ISSUE TITLE
Cannot drop index 'site': needed in a foreign key constraint. Doctrine drops index before create

### ISSUE THREAD

**Issue by seyfer** [doctrine/migrations#221]
The problem is occurred when I generate migration for an entity on an existed database.
I'm add mapping from one table to table site. Generated migrations was like this

```
$this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9F694309E4 FOREIGN KEY (site) REFERENCES sites (id)');
 $this->addSql('DROP INDEX site ON request');
        $this->addSql('CREATE INDEX IDX_3B978F9F694309E4 ON request (site)');
       
```
I'm already have index `site` on site column before generation migration, and migration tries, as you can see, first drop old index and than add new. But

```                                                                                           
  [Doctrine\DBAL\Exception\DriverException]                                                          
  An exception occurred while executing 'DROP INDEX site ON request':                                
  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'site': needed in a foreign key constraint  
                                                                                                   
   [Doctrine\DBAL\Driver\PDOException]                                                                
  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'site': needed in a foreign key constraint 
```

If i change migration like that - all works.

```
$this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9F694309E4 FOREIGN KEY (site) REFERENCES sites (id)');
        $this->addSql('CREATE INDEX IDX_3B978F9F694309E4 ON request (site)');
        $this->addSql('DROP INDEX site ON request');
```

I think migration should drop old or duplicate indexes AFTER adding new, not before.

**Comment by mikeSimonson** [comment]
That's a doctrine orm issue.
Can you move it there ?

**Comment by stof** [comment]
@mikeSimonson probably a DBAL one (the schema comparison is in DBAL)

**Comment by seyfer** [comment]
So DBAL or ORM ?

**Comment by mikeSimonson** [comment]
@seyfer sorry it's DBAL

**Comment by seyfer** [comment]
I can't open issue in DBAL
https://github.com/doctrine/dbal

Issues closed there

**Comment by mikeSimonson** [comment]
The issue tracker is there http://www.doctrine-project.org/jira/browse/DBAL/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by seyfer** [comment]
@mikeSimonson - I made it
http://www.doctrine-project.org/jira/browse/DBAL-1177

**Comment by mikeSimonson** [comment]
@seyfer thanks
