### ISSUE TITLE
No schema difference detected when changing length of a text field

### ISSUE THREAD

**Issue by evsheffield** [doctrine/migrations#224]
I have a text field with a length specified that causes it to be chosen as `TINYTEXT` in MySQL.

```
/**  
 * @ORM\Column(name="message", type="text", length=255,  nullable=true)
 */
protected $message;
```

When I remove the "length" field in the annotation, [according to the documentation](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#id104) it should now be `LONGTEXT`, yet no difference is detected when I run `migrations:diff`.

**Comment by mikeSimonson** [comment]
As you accurately saw, it's a dbal issue not a migrations one.
Can you please move your bug report on the dbal bug tracker.
Thanks

**Comment by evsheffield** [comment]
@mikeSimonson Thanks for the quick response!

For anyone who stumbles upon this issue, here is a link to the issue on the dbal bug tracker.
http://www.doctrine-project.org/jira/browse/DBAL-1182
