### ISSUE TITLE
Setting field to null throws DBALException

### ISSUE THREAD

**Issue by albertsola** [doctrine/migrations#225]
I'm not sure if this is the place for that issue or if what I'm exposing here is a real issue or my fault.

I'm writting a migration to insert a null value and I found the following unexpected behavior.

My migration have the following code:

   $sql="INSERT INTO sme_task_template_trigger (status_change_final_status) VALUES (:finalStatus)";
    $params=array(
        'finalStatus' => null
    );
    $types=array(
        'finalStatus' => \PDO::PARAM_NULL
    );
    $this->addSql($sql, $params, $types);

This code raise the following exception:

  [Doctrine\DBAL\DBALException]                                                
  An exception occurred while executing 'INSERT INTO sme_task_template_trigger (statu  
  s_change_final_status) VALUES (:finalStatus)' with params [null]:            
  Value for :finalStatus not found in params array. Params array key should b  
  e "finalStatus"

But the following code works:

    $sql="INSERT INTO sme_task_template_trigger (status_change_final_status) VALUES (?)";
    $params=array(
        null
    );
    $types=array(
        \PDO::PARAM_NULL
    );
    $this->addSql($sql, $params, $types);

Thanks,

Albert

**Comment by mikeSimonson** [comment]
That's a dbal issue. You should report it on their bug tracker along with the version of dbal you are using.
I am not sure but I think the bug is in the documentation that is not super clear.
