### ISSUE TITLE
One of the latest commits breaks migrations with ZF2 and DoctrineModule!

### ISSUE THREAD

**Issue by seyfer** [doctrine/migrations#228]
I'm have updated migrations dev-master branch with composer

```
Updating doctrine/migrations dev-master (058a463 => 65978aa)
```

After that I'm always have error with migrations in console like this:

```
php public/index.php migrations:status
PHP Fatal error:  Class 'Application\Version20140623142428' not found in /var/www/domain.com/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php on line 113
PHP Stack trace:

```

But I have migrations configured with another namespace. Here is my doctrine config for migrations

```
'migrations_configuration' => [
            'orm_default' => [
                'directory' => 'data/DoctrineORMModule/Migrations/',
                'namespace' => 'DoctrineORMModule\Migrations',
                'table'     => 'migrations',
            ],
        ],
```

And part of existed migration code for example:

```
namespace DoctrineORMModule\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20140623142428 extends AbstractMigration
{
```

When I downgrade migrations commit with composer then all works again!

```
- Updating doctrine/migrations dev-master (65978aa => 058a463)
```

So, one of the latest changes breaks migrations with ZF2!

**Comment by seyfer** [comment]
My composer.json versions

```
"doctrine/common": "2.*",
    "doctrine/orm": "2.*",
    "doctrine/doctrine-module": "0.8.*",
    "doctrine/doctrine-orm-module": "0.8.*",
    "doctrine/migrations": "1.0.*@dev",
```

**Comment by seyfer** [comment]
I'm tried to change DoctrineModule version to dev-master but it still not work.

```
"doctrine/doctrine-module": "dev-master",
    "doctrine/doctrine-orm-module": "dev-master",
```

```
- Removing doctrine/doctrine-module (0.8.0)
  - Installing doctrine/doctrine-module (dev-master 856e1ef)
    Cloning 856e1efe08f8ff562f9c7b916dc361e900e8126e

  - Removing doctrine/doctrine-orm-module (0.8.0)
  - Installing doctrine/doctrine-orm-module (dev-master e81f86a)
    Cloning e81f86a96663d3117a894f427a72ce853b9e79fa

```

Still same error
```
Fatal error: Class 'Application\Version20140623142428' not found
```

Only way to make it work now for me is to fork migrations repo, check it out to latest working commit that i know `058a463` and install this version..

It's a very pity ..

**Comment by seyfer** [comment]
Now I walked up from https://github.com/doctrine/migrations/commit/058a4635ac9b80a5b1997df28a754e64b1425a1d to https://github.com/doctrine/migrations/commit/93a9369ea7846e8ae2e9303c94bb36dbcbb2009b commits and tried to do just migrations:status on each step

```
php public/index.php migrations:status
```

**Comment by seyfer** [comment]
Okay, it's all was because I have `migrations.xml` in my root project directory and it tries to overload my config from doctrine.local.php

WTF. Really, Doctrine contributors, WTF ?
I spent whole day to find out what happened. I made a research of migrations repo commits to find out how it works.

Why so NOT OBVIOUS behavior NOT DOCUMENTED anywhere !?

You really made me sad with my experience with using Doctrine guys.. :-1:

**Comment by pCoLaSD** [comment]
When we change the order of the configuration "lookup" in the getMigrationConfiguration() method in https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/AbstractCommand.php as follows:

1. from `--configuration` cli parameter
2. injected via di (`$this->configuration`)
3. fallback config files (`migrations.xml`, `migrations.yml`, `migrations.yaml`)

Everything should be fine, right?

**Comment by mikeSimonson** [comment]
Thanks for finding the offending commit.
FYI if you need a specific commit from an alpha tool you installed with composer, you can require it with ``` package-name : dev-master#commit-id```.

I will try to look at it as soon as possible.

**Comment by seyfer** [comment]
Logically it's fine. But it's not documented anywhere and I'm with all my experience with ZF2 and Doctrine was confused with this behavior.

Existed documentation say nothing about that behavior.
https://github.com/doctrine/DoctrineORMModule/blob/master/docs/migrations.md

How could developer know about this configuration overloads?

**Comment by seyfer** [comment]
```
injected via di ($this->configuration) - this is what the ZF2 module does
fallback config files (migrations.xml, migrations.yml, migrations.yaml)
```

I don't think last option work as fallback, because I have configuration in `doctrine.local.php` and also I have `migrations.xml` file. And configuration read from both this sources, not from first one, than second.

If I delete `migrations.xml` file, than it read only `doctrine.local.php`. But if migrations.xml exist - it tries to overload or compliment to `doctrine.local.php` configuration or overload it, as described in my errors example above.
