### ISSUE TITLE
Tag stable version

### ISSUE THREAD

**Issue by TomasVotruba** [doctrine/migrations#239]
What is blocking tagging stable version? I'd like to help to speed this up.
It would really help any packages depending on this one.

**Comment by mikeSimonson** [comment]
@TomasVotruba Just a few bugs that I want to close before it. It's close now. It will be there before the end of the summer in any case.

**Comment by chrisguitarguy** [comment]
@mikeSimonson Maybe there can be another `-alpha*` tag?

**Comment by TomasVotruba** [comment]
@mikeSimonson What are those bugs? Would care for helping out?

@chrisguitarguy That would not help. When your package depends on another package, that has no stable tag, you have to [include them both manually (see Silex example)](https://igor.io/2013/02/07/composer-stability-flags.html).

To be specific, I'd like to change [this multi-line installation](https://github.com/Zenify/DoctrineMigrations/#install) to just this:

```sh
composer require zenify/doctrine-migrations
```

**Comment by mikeSimonson** [comment]
@TomasVotruba Well I promise that I will make a bug report tomorrow for those I want fixed before 1.0

**Comment by mikeSimonson** [comment]
@TomasVotruba You can espacialy write tests to replicate this bug #61 .

**Comment by Pierstoval** [comment]
So, are we close now? :+1: :smiley:

**Comment by stof** [comment]
@mikeSimonson please put any issue blocking 1.0 in the dedicated milestone: https://github.com/doctrine/migrations/milestones/1.0

**Comment by mikeSimonson** [comment]
Really close, I am waiting until Friday for an answer on #261 .
If I don't get any anser by Friday I will merge the #300 and put out the last an RC.
If no issue are discovered in the following week it will become 1.0.

**Comment by mikeSimonson** [comment]
done.

https://github.com/doctrine/migrations/releases

**Comment by TomasVotruba** [comment]
:+1:
