### ISSUE TITLE
Data loss after up and down migration

### ISSUE THREAD

**Issue by raampje** [doctrine/migrations#242]
I have a SQL schema in which I want to change the name of the collumn "message" to "textWebsite" and add an extra collumn "facebookText". The code for the up migration looks promising:
```$this->addSql('ALTER TABLE NewsMessageTranslation ADD textFacebook LONGTEXT DEFAULT NULL, CHANGE message textWebsite LONGTEXT DEFAULT NULL');```
However the down migrations code contains the following code:
```$this->addSql('ALTER TABLE NewsMessageTranslation ADD message LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, DROP textWebsite, DROP textFacebook');```
In the down part the collumn "textWebsite" is DROPPED instead of altered. In this way after an up migration and a down migration all the data in the (original) collumn "message" is lost.

All the above code is automatically generated by doctrine migrations. I'm using 65978aa4e9ffca3bb632225ad8c6320077d80d85.

**Comment by mikeSimonson** [comment]
It's not doctrine migration that is generating the sql for those queries but the doctrine dbal.
Can you move your bug report to their tracker ? http://www.doctrine-project.org/jira/browse/DBAL/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel

Thanks @raampje

**Comment by stof** [comment]
Well, DBAL does what it can to alter the schema. However, when dropping 2 columns and adding 1, it may not know which one should be renamed.
The generated migration is **never** data-safe (well, in some case, it is, but you cannot assume it). This is precisely why the generated code has a comment telling you that you can change the generated migration too.
Migrating the schema automatically is doable. Migrating the data requires understanding the data, and DBAL cannot do that for you.
