### ISSUE TITLE
OrmSchemaProvider class has incorrect constructor argument

### ISSUE THREAD

**Issue by Tocacar** [doctrine/migrations#243]
This class has EntityManagerInterface as a constructor argument:

```
namespace Doctrine\DBAL\Migrations\Provider;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;

/**
 * A schema provider that uses the doctrine ORM to generate schemas.
 *
 * @since   1.0.0-alpha3
 */
final class OrmSchemaProvider implements SchemaProvider
{
    /**
     * @var     EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $em)
    {
        $this->entityManager = $em;
    }
```

...however, EntityManagerInterface doesn't exist, which breaks migrations - I get this error:

```
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                 
  Catchable Fatal Error: Argument 1 passed to Doctrine\DBAL\Migrations\Provider\OrmSchemaProvider::__construct() must be an instance of Doctrine\ORM\EntityManagerInterface, instance of E  
  ntityManager554e288eb8215_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager given, called in /path/to/my/app/vendor/doctrine/migrations/lib/Do  
  ctrine/DBAL/Migrations/Tools/Console/Command/DiffCommand.php on line 147 and defined   
```

**Comment by Tocacar** [comment]
I beg your pardon, it does indeed exist.  One must remember to upgrade the other bundle before making wild accusations :)  As you were...

**Comment by jarofgreen** [comment]
I have this problem. Which "other bundle" do you mean?

I have set my composer up following http://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html and updated but still get the error.

Thanks.

**Comment by Tocacar** [comment]
@jarofgreen Apologies, I was referring to the Doctrine ORM bundle.  You can see that the EntityManagerInterface class is now in that bundle here https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManagerInterface.php

**Comment by jarofgreen** [comment]
Thanks - got my issue sorted, I had an older composer.json that was loading an older version of the ORM.
