### ISSUE TITLE
Migration files in separate directories (diff/migrate commands)

### ISSUE THREAD

**Issue by velikanov** [doctrine/migrations#254]
Got an inconvenience with migrations storing.
Now I have one directory in which all migrations stored in plain list way.
It makes a pain when you have hundreds of migrations
I suggest to make for every migration a directory structure with this format: "Year/Month/Day/Migration".

The feature is ready, I just need to understand - is it wanted by community or not.
The converter of plain list way is included.
Feature allows you to store migration in Y/M/D way and the canonical way also.

Please, take a look at the screenshot:
![276101af6f](https://cloud.githubusercontent.com/assets/4798469/7745604/2a1108d0-ffb5-11e4-81d2-d793a353e40a.jpg)

**Comment by mikeSimonson** [comment]
The feature is already there. It has been added recently.

You will have to create the subfolders yourself but now, doctrine migrations should pick every migrations in the subfolders.

Can you check and maybe add a test to verify that it works with sub sub folder ?

Thanks @velikanov

**Comment by velikanov** [comment]
@mikeSimonson, yes, but I don't want to create subfolders manually

**Comment by arthas-eve** [comment]
:+1:

**Comment by germani** [comment]
+1

**Comment by webislife** [comment]
+1

**Comment by mikeSimonson** [comment]
How do you make it work ?
Did you added an option in the generate command to create the folder structure ?

The problem that you have to take into account is that users can name their migrations not using a datetime.

```yml
001User
002Product
....
```

**Comment by velikanov** [comment]
@mikeSimonson, sorry, I forgot to mention that it is all about diff/migrate commands
So, when I'm making "migrations:diff" I want to see automatically created migration file inside properly structured directory…
Then I can rename it to whatever I need

**Comment by mikeSimonson** [comment]
The migrate command shouldn't need any change.
Can you push your change in a PR ?

You can add that feature triggered in an option with migration:diff and migration:generate ?

**Comment by velikanov** [comment]
@mikeSimonson, sure, thanks

**Comment by SkLight** [comment]
:+1:

**Comment by Niku85ru** [comment]
:+1:

**Comment by mikeSimonson** [comment]
Well good to see that a lot of people want that feature

**Comment by velikanov** [comment]
yep, thank you all
@mikeSimonson, it will take some time for me, 'cause I did this on earlier version of DoctrineMigrations where "Version" was not exist, but I think there will be no trouble

**Comment by mikeSimonson** [comment]
see #310

**Comment by improvisio** [comment]
:+1:

**Comment by TheRatG** [comment]
:+1:
