### ISSUE TITLE
diff always generates CREATE SCHEMA commands in down migrations for PostgreSQL

### ISSUE THREAD

**Issue by eggyal** [doctrine/migrations#257]
Whenever I use `:diff` against a PostgreSQL backend, the generated `down` migrations always start with `CREATE SCHEMA`.

This not only causes `down` migrations to fail (because the schema already exists and hence that command raises an error), but also results in `:diff` generating migrations even where no differences exist (they contain that command alone).

**Comment by stof** [comment]
This should be reported to Doctrine DBAL. the Migrations project is not responsible for comparing Schema objects. It is provided by DBAL.

And btw, I used to see this in the past, but it does not do it anymore for me. but I don't know what changed.

**Comment by eggyal** [comment]
Ah, my apologies.  I will report it to Doctrine DBAL.
