### ISSUE TITLE
possible issue

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#259]
It looks like the globFinder and the RegexFinder don't register the migrations using the same logic regarding the version name ( class name ).

It looks like the globFinder remove the appended "Version" in the class name and the regex don't seems to.

Some tests would be welcome to verify that and check that it does not cause issues.

https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php#L49
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Finder/GlobFinder.php#L53

**Comment by chrisguitarguy** [comment]
Both use the same logic to get the class name: basename of the file without the `.php` extension.

- https://github.com/doctrine/migrations/blob/abb87d84ed21fd30c27bd3b52252a495a36d32fb/lib/Doctrine/DBAL/Migrations/Finder/GlobFinder.php#L52
- https://github.com/doctrine/migrations/blob/abb87d84ed21fd30c27bd3b52252a495a36d32fb/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php#L49

The version number for each just drops the `Version`. That happens with substr in `GlobFinder` and uses the `RegexIterator` itself in `RecursiveRegexFinder`.

- https://github.com/doctrine/migrations/blob/abb87d84ed21fd30c27bd3b52252a495a36d32fb/lib/Doctrine/DBAL/Migrations/Finder/GlobFinder.php#L53
- https://github.com/doctrine/migrations/blob/abb87d84ed21fd30c27bd3b52252a495a36d32fb/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php#L47

A possible difference is that the `GlobFinder` looks for files that start with `Version` in a given directory. The regex finder just cares that the filename ends with Version followed by 1 to 255 characters and a `.php`.

The tests for both look in the same directory: https://github.com/doctrine/migrations/tree/abb87d84ed21fd30c27bd3b52252a495a36d32fb/tests/Doctrine/DBAL/Migrations/Tests/Finder

**Comment by mikeSimonson** [comment]
@chrisguitarguy You are right, thanks.
