### ISSUE TITLE
Comparator

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#260]
Right now the app decide the order in which the migration must be run using a non strict comparator.

As long as someone name is migration only using datetime or only using desctriptive name prefixed by a number, all is well.

If if someone mix both the result is going to be unpredictable.

There should be a warning if the user is trying to do so and I would like a unique place to put the code that compare 2 versions.

Any advice ?

**Comment by mikeSimonson** [comment]
The comparisons or ordering happens in a lot of places : 

https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L303
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L673
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L681
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L87
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L134
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L138

**Comment by chrisguitarguy** [comment]
For what it's worth, I don't think datetimes or any magic comparison should be used at all.

Migrations should be built in a tree. When you generate a migration it points to the previous migration's version number (via a class constant or method) that allows the migrations library to build a tree of migrations.

```php
// Version001.php
class Version001
{
   const PREV = null;

   // up, down, etc
}

// Version002.php
class Version001
{
  const PREV = '001';

  // up, down, etc
}


// etc.
```

When the library loads the migrations from the directory, it can look at the previous version and build up a chain of migrations to run in order. Usually this tree is just a linked list, but in the cases were two developers created a migration from a single parent (eg. two people working separately) the migration library could prompt the user about possible conflicts and suggest merges or simply do nothing if two branches are desired.

Check out how Alembic, a Python migrations library, [works with what it calls branches](http://alembic.readthedocs.org/en/latest/branches.html).

Something like this would better fix the datetime vs arbitrary version conflicts, IMO.

**Comment by mikeSimonson** [comment]
I would like to avoid that as much as possible.

IMO (right now) the order of the file in a file explorer should be the order of execution.
Otherwise it becomes a mess to wrap your mind around it.

**Comment by chrisguitarguy** [comment]
Fair enough, it's definitely a big change.

How about just letting `Version` objects compare themselves:

```php
$version->directionTo($otherVersion);

$version->isLowerThan($otherVersion);

$verison->isHigherThan($otherVersion);
```

Where `$otherVersion` could be a Version object itself or a string.

**Comment by mikeSimonson** [comment]
it's not different than how it works now.

The only edge case were it's broken right now is if you have migration that are datetime or prefix by a number and migration that start with a letter in the same "migrations".

That case is broken because there is an implicit conversion by the current comparator ( > or <= ).

I think that people should be warned if they make something like that because it's probably going to be hard to guarantee the order in that case or a mixed case.

But it does not mean that we can't implement your solution with the previous property.
If that property is not there then the default behaviour would be to make sure that we are not making implicit conversion when comparing and use one peace of code that does the same comparaison everywhere.

**Comment by beberlei** [comment]
@chrisguitarguy Your approach is not deterministic, when several migrations point to the same previous version for example, say because of a merge. So its the same problem as with dates.

**Comment by chrisguitarguy** [comment]
@beberlei yeah, that's true. At the same time, when there's an explicit tree the migration tool itself can provide utilities for merging or reordering to make sure everything is okay and abort in the case of somethings that's completely undoable.

I'm not sure if it's a good idea or not, but I saw it done in alembic and thought it might be worth pitching.

**Comment by mikeSimonson** [comment]
@chrisguitarguy my problem with migrations order that is not deterministic is that I have (nearly) never had a case where the order wasn't crucial and in most of those cases it's impossible for the tool to know why to order it in an order instead of another. Especially true when you migrate data and there are foreign keys.

**Comment by chrisguitarguy** [comment]
Right. The advantage of the tree idea is that it makes those relationships explicit and not based on file creation time or version numbers/names. But you still get non-deterministic bits when branches happen -- since the tool wouldn't have any idea about the order in which those children should be run. Those points would have to be resolved manually or with the assistance of the tool itself. That resolution could be super simple (another "migration" class that just gives the array of children in order) or could involve rewriting things.

Maybe the answer is really simple: don't allow non-numeric versions for 1.0 and error out if one is found, keep everything else the same. In other words, force folks to generate migration files with `migrations:generate` or `migrations:diff`.

When/if that needs to change in 2.0 the way forward should be easy due to the numeric only constraint.

**Comment by mikeSimonson** [comment]
Well my problem with that is that it's allowed now and I know people use it. I don't won't to change that before 1.0.
So now I am left finding an acceptable way to have both for 1.0
