### ISSUE TITLE
composer install fails, as dev-master got renamed "1.0.x-dev"

### ISSUE THREAD

**Issue by kaystrobach** [doctrine/migrations#261]
as you renamed the dev-master to "1.0.x-dev" you broke a lot of dependencies ...

please add a

```
replace: {
    "doctrine/migrations": "dev-master"
}
```

to your composer.json or give us back dev-master ...

**Comment by mikeSimonson** [comment]
How do you trigger the problem ?

dev-master is still there https://github.com/doctrine/migrations/blob/master/composer.json#L38

**Comment by stof** [comment]
@kaystrobach you should never use ``dev-master`` directly but the branch alias though, as you are actually asking for +INF as dependency when depending on dev-master

**Comment by kaystrobach** [comment]
i tried to do a composer update on a TYPO3/Flow project.

```
composer update --prefer-source
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - typo3/flow 2.3.3 requires doctrine/migrations dev-master -> no matching package found.
    - typo3/flow 2.3.3 requires doctrine/migrations dev-master -> no matching package found.
    - Installation request for typo3/flow 2.3.3 -> satisfiable by typo3/flow[2.3.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by kaystrobach** [comment]
@stof i will tell that the typo3/flow developers, sadly flow depends on it and doctrine/orm seems to have a conflict with the dev version

**Comment by stof** [comment]
@kaystrobach your issue is just a stability issue IMO: your project probably uses stable as minimum dependency, which means that ``dev-master`` cannot be installed when asked by a dependency unless your root project whitelists dev versions of this package.

**Comment by kaystrobach** [comment]
i have set / unset (so that should not be a problem)
```
"minimum-stability": "dev"
```
and it worked until yesterday ...

**Comment by mikeSimonson** [comment]
Weird the last change is from 3 day ago and doesn't touch the branch alias.

@kaystrobach 
Can you post your complete composer.json ?

**Comment by kaystrobach** [comment]
there are plenty packages included:

```
{
	"name": "typo3/flow-base-distribution",
	"description" : "TYPO3 Flow Base Distribution",
	"license": "LGPL-3.0+",
	"config": {
		"vendor-dir": "Packages/Libraries",
		"bin-dir": "bin",
		"preferred-install": "dist"
	},
	"require": {
		"typo3/flow": "2.3.3",
		"typo3/fluid": "2.3.3",
		"doctrine/migrations": "@dev",
		"typo3/swiftmailer": "@dev",
		"kaystrobach/menu": "@dev",
		"kaystrobach/phpoffice": "dev-master",
		"phpoffice/phpword": "dev-master",
		"kaystrobach/custom": "dev-master",
		"kaystrobach/pdf": "@dev",
		"kaystrobach/documents": "@dev",
		"kaystrobach/gitlab": "@dev",
		"mpdf/mpdf": "@dev",
		"kaystrobach/backup": "0.0.1.*",
		"kaystrobach/wysiwyg": "@dev",
		"kaystrobach/visualsearch": "@dev"
	},
	"require-dev": {
		"typo3/kickstart": "dev-master",
		"typo3/buildessentials": "2.3",
		"kaystrobach/development-tools": "@dev",
		"sandstorm/phpprofiler": "1.1.*",
		"mikey179/vfsstream": "1.4.*",
		"phpunit/phpunit": "4.5.*",
		"typo3/surf": "dev-master#d9b3bae7763ccc85b7ab66a6697da5118e87405a",
		"flowpack/behat": "dev-master",
		"typo3-ci/TYPO3Flow": "~2.3"
	},
	"suggest": {
		"ext-pdo_sqlite": "For running functional tests out-of-the-box this is required"
	},
	"scripts": {
		"post-update-cmd": "TYPO3\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
		"post-install-cmd": "TYPO3\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
		"post-package-update":"TYPO3\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall",
		"post-package-install":"TYPO3\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall"
	}
}
```

**Comment by mikeSimonson** [comment]
Using the current typo3 flow 3 composer.json the install works.
https://git.typo3.org/Flow/Distributions/Base.git/blob/refs/heads/3.0:/composer.json

**Comment by kaystrobach** [comment]
i know, but 3.0 is quite different to 2.3 and an update will take some time ... 

i still wonder why it broke from one day to another ...

**Comment by mikeSimonson** [comment]
your problem is that typo3/flow require doctrine/orm 2.3* and doctrine/migrations require doctrine/orm 2.4

**Comment by kaystrobach** [comment]
ok, thank you, have pushed that message to the FLOW devs in sync with that discussion :) thank you for your help and patience ...

**Comment by aertmann** [comment]
Hey there. From what I can gather the cause is that the dev-master branch on [Packagist](https://packagist.org/packages/doctrine/migrations) was removed and/or aliaset "dev-master / 1.0.x-dev". This is breaking for projects that depend on that branch, which I would assume could be quite a lot of projects considering it's been versioned as unstable for years and there's still no stable version yet. I would suggest that you reconsider that change to keep it more compatible with existing projects and instead of forcing people to use 1.0.x like this, make them do that themselves. Thank you :)

**Comment by mikeSimonson** [comment]
if you need to avoid the dependency to the orm2.4, you can stick to v1.0.0-alpha3.
It's just before that change.

**Comment by kdambekalns** [comment]
@mikeSimonson So, 1.0.0 will require ORM 2.4, do I get that right?

Oh, and the info on packagist contradicts itself: 
![doctrine_migrations_-_packagist](https://cloud.githubusercontent.com/assets/95873/7882571/2d678fb2-060f-11e5-8d1a-2d7e6521ec16.png)

**Comment by mikeSimonson** [comment]
I don't know exactly what happened there, but as you see the dev-master which is below was published on the 20/01/2014 0742fc7167a4deedaabc8639849a3e71082999f1 .

It seems like this commit has been tagged with a 1.0 tag and then 4 commit later there is another 1.0 branch 0742fc7167a4deedaabc8639849a3e71082999f1 .

Maybe the simplest is to rename the dev-master / 1.0.x-dev to dev-master / 2.0.x-dev to avoid conflict like those. but is really worth it knowing that you will have code that's old and bugged ?

**Comment by kdambekalns** [comment]
Right now this is really causing issues. I pinned the required doctrine/migrations to a version not yet conflicting with doctrine/orm 2.3. A first ``composer update`` works fine, but further updates result in

```
  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for typo3/flow 2.3.* -> satisfiable by typo3/flow[2.3.4].
      - doctrine/migrations 1.0.x-dev conflicts with doctrine/orm[v2.3.6].
      - typo3/flow 2.3.4 requires doctrine/orm 2.3.* -> satisfiable by doctrine/orm[v2.3.6].
      - Installation request for doctrine/migrations 1.0.x-dev#f623eff82515f55d18199706851895ced831cba0 -> satisfiable by doctrine/migrations[1.0.x-dev].
```

It seems the dependency solver of composer looks at the 1.0.x-dev dependencies, not the pinned hash.

**Comment by kdambekalns** [comment]
And about old and buggy code - we used dev-master for ages now, and it has not been broken. At least it worked. And now we have releases out there that cannot be updated - and updating them to doctrine/orm 2.4 is not feasible.

**Comment by mikeSimonson** [comment]
You should require ```dev-master#f623eff82515f55d18199706851895ced831cba0```

Because you didn't saw the bugs don't mean they didn't existed.

For now, I need a better solution than the current one for that 1.0.0-dev double version issue

**Comment by kdambekalns** [comment]
> You should require dev-master#f623eff82515f55d18199706851895ced831cba0

Won't help, we'll switch to alpha3 instead. See composer/composer#4082

> Because you didn't saw the bugs don't mean they didn't existed.

Sure, but as I said, we never had issues so far, and cannot simply update ORM on all branches.

BTW: Thanks for having picked up versioning of migrations at all! Highly appreciated.

**Comment by Maltronic** [comment]
Unless this can be resolved quickly it might be an idea to update the README.markdown as the current [installation instructions](https://github.com/doctrine/migrations/blob/master/README.markdown#using-composer) will fail for most people:

```
$ composer require doctrine/migrations

  [InvalidArgumentException]
  Could not find package doctrine/migrations at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by mikeSimonson** [comment]
@kaystrobach @kdambekalns .

Sorry for the delay, I made a PR #300 that is supposed to fix your issue to stay compatible with the orm 2.4.
Can you confirm that it works ?
Thanks

**Comment by mikeSimonson** [comment]
ping @kaystrobach @kdambekalns

**Comment by kaystrobach** [comment]
@mikeSimonson, the FLOW team (e.g. @kdambekalns ) released a new version of their framework, which contains the new tagged version of migrations, so atleast for me it was solved :smile:

**Comment by mikeSimonson** [comment]
I need to find a way where I can make sure that the ~200 package that relies on doctrine migrations don't brake.

**Comment by kaystrobach** [comment]
maybe you can use an older version of FLOW Distribution:

https://git.typo3.org/Flow/Distributions/Base.git/ version 2.2.2 or earlier

**Comment by kdambekalns** [comment]
I'll check, hopefully tomorrow…
