### ISSUE TITLE
Call of "setMigrationConfiguration" has no any effect

### ISSUE THREAD

**Issue by Koc** [doctrine/migrations#266]
```php
$doctrineConfiguration = new Doctrine\DBAL\Migrations\Configuration\Configuration($app['db']);
$doctrineConfiguration->setMigrationsNamespace('Pinboard\\DoctrineMigrations');
$doctrineConfiguration->setMigrationsDirectory(__DIR__ . '/src/Pinboard/DoctrineMigrations');
$doctrineConfiguration->registerMigrationsFromDirectory(__DIR__ . '/src/Pinboard/DoctrineMigrations');

$doctrineCommands = array(
    'ExecuteCommand',
    'GenerateCommand',
    'MigrateCommand',
    'StatusCommand',
    'VersionCommand',
);

foreach($doctrineCommands as $commandName) {
    $fullCommandName = 'Doctrine\\DBAL\\Migrations\\Tools\\Console\\Command\\' . $commandName;
    $command = new $fullCommandName();
    $command->setMigrationConfiguration($doctrineConfiguration);

    $console->add($command);
}
```
Produces an error
```
You have to specify a --db-configuration file or pass a Database Connection as a dependency to the Migrations.
```

But it works on previous versions

**Comment by mikeSimonson** [comment]
@Koc Can you provide more information.
What previous version ?
What's in $app['db'] ?

etc

**Comment by Koc** [comment]
this is project based on Silex. `$app['db']` is DBAL Connection object. Previous version - version before latest refactoring in `AbstractCommand` class.

**Comment by mikeSimonson** [comment]
This one 9aabe0ab6171c601ec4cb69ce5421b49e5f7fa6b
or this one 7a4e9c78c2f31cb3d653a200b5992d2178ce5102

**Comment by Koc** [comment]
```
        "doctrine/migrations": "dev-master#48b958213d5ce5be22be591f999f67428f947df1",
```
works fine for me

**Comment by Koc** [comment]
https://github.com/doctrine/migrations/commit/fc4fcc868821f0767866a0c770b3e81a38849315

```
 + $configHelper = new ConfigurationHelper($this->getConnection($input), $this->configuration); // getConnection throws exception
```

**Comment by mikeSimonson** [comment]
nothing after that ?

**Comment by mikeSimonson** [comment]
What's the exception thown ?

**Comment by Koc** [comment]
```
You have to specify a --db-configuration file or pass a Database Connection as a dependency to the Migrations.
```

**Comment by mikeSimonson** [comment]
Probably your dbal connection has an issue.

Can you ```var_dump($app['db'])``` ?

**Comment by Koc** [comment]
If my connection has issue - why it works on previous version?)

```
class Doctrine\DBAL\Connection#76 (13) {
  protected $_conn =>
  NULL
  protected $_config =>
  class Doctrine\DBAL\Configuration#67 (1) {
    protected $_attributes =>
    array(2) {
      'sqlLogger' =>
      class Pinboard\Logger\DbalLogger#68 (3) {
```

**Comment by Koc** [comment]
see https://github.com/doctrine/migrations/commit/fc4fcc868821f0767866a0c770b3e81a38849315#commitcomment-11669117

**Comment by mikeSimonson** [comment]
I think I found the problem but I just don't understand how it could have worked before.
You are sure that it works before that commit ?

**Comment by Koc** [comment]
Yes, I'm sure that it works perfectly on
```
        "doctrine/migrations": "dev-master#48b958213d5ce5be22be591f999f67428f947df1",
```

**Comment by mikeSimonson** [comment]
One thing that I think should fix it is to call 
```php
$helperSet = new \Symfony\Component\Console\Helper\HelperSet();
$helperSet->set(new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($app['db']->getConnection()));
$console->setHelperSet($helperSet);
```
Can you try that before your foreach ?

**Comment by mikeSimonson** [comment]
The weird part about your bug is that it has not changed in the next commit and the part of the code that changed is run after the code that triggered the exception.

Can you post the name of the command for which it fails and the full stack trace?

**Comment by mikeSimonson** [comment]
If you could make a test case that work in 48b958213d5ce5be22be591f999f67428f947df1 and fail after it would be perfect for me?

**Comment by mikeSimonson** [comment]
Does this PR fix your issue @Koc ?

**Comment by mikeSimonson** [comment]
ping @Koc

**Comment by Koc** [comment]
@mikeSimonson yes, this PR fixes the problem.

**Comment by mikeSimonson** [comment]
@Koc Thanks I even found a way to tests this case.

**Comment by Koc** [comment]
Thank you for the fix
