### ISSUE TITLE
choosing the infrastructure for a phar update command.

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#270]
There are various implementation of the phar update command available.
Such as 
- https://github.com/herrera-io/php-phar-update
- https://github.com/box-project/amend (integrate the first one in symfony console)
- https://github.com/padraic/phar-updater

We need to pick one taking into account the guarantee they offer from the security and from the support point of view.
Don't hesitate to add some if they might fit in.

We also need to discuss the minimum infrastructure we need to setup so that the update is as safe as possible.

In both those solution you need a file that contain some form of signature (sha1) to verify the phar content. Right now the easiest would be to ship those file in the github release I suppose as it support https.

Here are some posts on the subject.
- http://blog.astrumfutura.com/2015/03/securely-distributing-phars-pitfalls-and-solutions/
- http://moquet.net/blog/distributing-php-cli/

I don't really like the fact that if I sign the phar it cannot run without the pubkey file next to it. Is there something that can be done around that ?

**Comment by stof** [comment]
@padraic's solution takes the security into account (it is exactly the reason why it was written).

and yes, I agree about using github releases to ship them.

**Comment by jwage** [comment]
@mikeSimonson @stof is this still legit? 2.0 material?

**Comment by Majkl578** [comment]
cc @theofidry

**Comment by stof** [comment]
should we even keep shipping doctrine/migrations as a phar ?

**Comment by MatthiasKuehneEllerhold** [comment]
Signed PHARS have the advantage of being self-contained installables that do not bloat your autoloaded classes in production. You could even use PHIVE (https://github.com/phar-io/phive/) to securely install it and remove it from your composer.json.

**Comment by stof** [comment]
thus, the main dependency of doctrine/migrations is DBAL, and you are already likely to have it in your project anyway
