### ISSUE TITLE
onDelete="..." Change Not Recognized 

### ISSUE THREAD

**Issue by bmeynell** [doctrine/migrations#275]
#### Scenario

  * DB column is `DEFAULT NULL` and has a constraint of `ON DELETE CASCADE`
  * DB and Entity schema are in sync
  * Entity field definition is changed from `onDelete="CASCADE"` to `onDelete="SET NULL"`.
  * `doctrine:migrations:diff` and `doctrine:schema:validate` do not recognize the change.

**Comment by mikeSimonson** [comment]
Hi, that bug is a docrine Dbal bug, can you please make a bug report on their bug tracker.
http://www.doctrine-project.org/jira/browse/DBAL/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

Thanks @bmeynell
