### ISSUE TITLE
New regex pattern for migrations filename is greedy for "version" string

### ISSUE THREAD

**Issue by matks** [doctrine/migrations#276]
[Here is the line related to the issue.](https://github.com/matks/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php#L30)

I have a migration filename "Version1_reset_versions".
The old regex pattern was:
`const PATTERN = '/Version\d{14}\.php$/i'; `
And it captures "1_reset_versions" as the migration version.

The new regex pattern `const PATTERN = '#^.+Version(.{1,255})\.php$#i'; ` captures 's' as it is greedy and select the 2nd 'version' string. Consequently, my Symfony2 application assumes this 's' migration is a new one and it should be executed.

In order to ensure the string matched "Version" to be the 1st of the whole string, I suggest the following:
- insert a \ such as `const PATTERN = '#\\^.+Version(.{1,255})\.php$#i'; `
- however it might create issues on Windows filesystems as \ is not the directory separator for windows
- maybe replace the const by a private function getRegexPattern as such :

```
private function getRegexPattern() {
    return sprintf('#%s^.+Version(.{1,255})\.php$#i', DIRECTORY_SEPARATOR);
}
```

**Comment by giero** [comment]
In our project we have some directories connected with concrete migrations (for custom files like *.csv or php classes). And that directory name is same as migration class name - looks like this:

http://www.tiikoni.com/tis/view/?id=3bf223a

With this new pattern RecursiveRegexFinder marks classes inside those directories as migrations ... but it shouldn't. So maybe:
```const PATTERN = '#^.+Version([^/\\\\]{1,255})\.php$#i';```
? (backslash has to be escaped twice)

**Comment by mikeSimonson** [comment]
Would that work on windows too ?
```const PATTERN = '#^.+Version([^/\\\\]{1,255})\.php$#i';```

**Comment by mikeSimonson** [comment]
I updated the PR. Do you have windows ? if so can you try to run the tests and confirm that it works.
Thanks for your help @giero, next time don't hesitate to make a PR of your own, I will gladly merge it.

**Comment by mikeSimonson** [comment]
I updated that PR again, can you check the result for your use case ?
Thanks @giero @matks

**Comment by giero** [comment]
Works fine - thx for fast response :)
BTW - You don't have to escape / character - [^/\\\\] is fine :)

Or even you can try:
```php
private function getPattern()
{
    return sprintf('#^.+\\%sVersion[^\\%s]{1,255}\\.php$#i', DIRECTORY_SEPARATOR, DIRECTORY_SEPARATOR);
}
```
However have to check how it works on Windows.

**Comment by mikeSimonson** [comment]
That version is much more readable. Can you confirm for windows ?

**Comment by giero** [comment]
Checked on Win and all tests passed.

**Comment by mikeSimonson** [comment]
thanks @giero
