### ISSUE TITLE
fix a test that is not passing on windows

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#281]
https://github.com/doctrine/migrations/blob/master/tests/Doctrine/DBAL/Migrations/Tests/Tools/Console/Helper/ConfigurationHelperTest.php#L72

This test seems to fail on windows.

Can someone confirm and if confirmed fix/investigate it ?

**Comment by grubolsch** [comment]
I will take this.

**Comment by grubolsch** [comment]
Found it - not the most sexy bug - in windows the message got a \n - I put the test trough trim()

**Comment by grubolsch** [comment]
THis can be closed.
