### ISSUE TITLE
Removing duplicated code

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#283]
see https://scrutinizer-ci.com/g/doctrine/migrations/issues/master/files/lib/Doctrine/DBAL/Migrations/Configuration/XmlConfiguration.php?orderField=path&order=asc#inspectioncomment-949681381

**Comment by stof** [comment]
This is a false positive IMO. It is not actually duplicated. One path deals with SimpleXmlElement and the other one with array
