### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#284]
see https://scrutinizer-ci.com/g/doctrine/migrations/issues/master/files/lib/Doctrine/DBAL/Migrations/Migration.php?orderField=path&order=asc#inspectioncomment-949681385

**Comment by stof** [comment]
Is it really worth it though ?

**Comment by mikeSimonson** [comment]
That's a good question.

What argument do you have against it ?

**Comment by stof** [comment]
Well, it is 3 LOC. Is it really worth the additional complexity needed to move the code in a reusable location ?

**Comment by stof** [comment]
Actually, there is a solution: move the writing to files to separate classes and have the Version class exposing a method to dump its SQL to string only.

**Comment by mikeSimonson** [comment]
There is more similar code in the method  than shown on the report.
Le 24 juin 2015 18:02, "Christophe Coevoet" <notifications@github.com> a
écrit :

**Comment by mikeSimonson** [comment]
Interesting idea indeed
