### ISSUE TITLE
Test for AbstractMigration

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#285]
The following method are not tested in the [AbstractMigration](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php).

* [getDescription](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php#L99)
* [warnIf](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php#L110)
* [abortIf](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php#L129)
* [write](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php#L175)
* [throwIrreversibleMigrationException](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/AbstractMigration.php#L180)

**Comment by rvdbogerd** [comment]
Mine mine mine!

**Comment by mikeSimonson** [comment]
There are 2 cases left.

Caling
* warnIf with an empty message
* throwIrreversibleMigrationException with an empty message

**Comment by rvdbogerd** [comment]
@mikeSimonson Please close this issue, as you already added the missing tests in commit https://github.com/doctrine/migrations/commit/ef21fe13cf13b87e015937c3174690ccfea3064e

**Comment by mikeSimonson** [comment]
@rvdbogerd Thanks
