### ISSUE TITLE
Add tests for Migration

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#287]
The following method are not tested in the [Migration](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php).

* [getSql](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L65)
* [writeSqlFile](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L78)

**Comment by gabrielsomoza** [comment]
Doing this
