### ISSUE TITLE
add Tests for Version

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#288]
The following method are not tested in the [Version](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php).

* [addSql](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L166)
* [writeSqlFile](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L193)
* [Execute](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L237)
* [getExecutionState](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L353)
* [outputQueryTime](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L367)

**Comment by diewom** [comment]
I will complete this issue

**Comment by mikeSimonson** [comment]
There are only 2 tests left to do.

One need to test that an error message is outputed if a migration result in no sql query being run.

The other need to tests the behaviour when the migration throw an exception.
