### ISSUE TITLE
Big scary warning when there are actually no migrations to execute.

### ISSUE THREAD

**Issue by tchalvak** [doctrine/migrations#306]
Often when I run:

```
php app/console doctrine:migrations:migrate
```

I get this:

```
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y

No migrations to execute.
```

I think it would aid usability if the command did a pre-check for 0 migrations to run and just reported that first, so that the WARNING would be a special case certainly requiring extra scrutiny.

```
php app/console doctrine:migrations:migrate

No migrations to execute.
```

**Comment by mikeSimonson** [comment]
It would be nicer indeed, but that functionality in mixed up in the migrate function now.
You could try to refactor it out though.

**Comment by tchalvak** [comment]
Hmmm, let me see if I can figure out where it is and how it'd be refactored out.
