### ISSUE TITLE
Support of PHP >=5.3.2

### ISSUE THREAD

**Issue by robertfausk** [doctrine/migrations#308]
As of https://github.com/doctrine/migrations/commit/0e60856a10e8b510daa612fe25f6245aece77e68 PHP 5.3.2 support was skipped.

It seems it's only skipped because of the array definition in some test classes.

What about not dropping support for PHP 5.3 (until some features of PHP >=5.4 are really needed)?
I think many people still depends on it.

**Comment by mikeSimonson** [comment]
@robertfausk Why should I bother supporting an outdated and unsupported version of PHP ?

**Comment by robertfausk** [comment]
@mikeSimonson Yeah. I know it's outdated and not supported anymore. But here are some reasons why you should bother:

1. Because many sites still depends on PHP 5.3 and they won't be able to use doctrine/migrations in future.
see: http://w3techs.com/technologies/details/pl-php/5/all
"Version 5.3 is used by 40.2% of all the websites who use PHP version 5." (W3Techs.com, 13 July 2015)

2. There is no feature in this library which really relies on features of PHP 5.4 or higher.
3. You have very low impact to ensure compatibility.

**Comment by mikeSimonson** [comment]
Well I would use that article
<http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html> from
Antony Ferrara to not depend on 5.3.
The problem with your logic is that then eveyone has the impression that
it's okay to stay with outdated and unpatched version of PHP.
It's not.

**Comment by robertfausk** [comment]
Yes. According to the article you posted you're right for large frameworks like wordpress, codeigniter, zend, symfony (e.g. symfony 2.7 which depends on PHP 5.3 is supported until 2018 http://symfony.com/doc/current/contributing/community/releases.html#schedule) etc.

I'm totally with you to upgrade the minimum supported PHP version IF there are PHP features you're in need of.
As for myself I wouldn't upgrade the minimum supported PHP version of my lib if just for the use of short array syntax.

Unfortunately there are companies out there which still relies on PHP 5.3 like the one I'm working at ;) and I think we are not alone out there.
We plan to upgrade to a new PHP version in Q3 2015 but thats not now...
Furthermore we are using this lib for our CI and deployment process and there is no possibility to use a PHP 5.3 compatible version than using an own fork.

What about adding a 5.3 compatitiblity branch?

If you still don't agree feel free to close this issue and according pr. I will pragmatically use my own fork then until we upgrade our PHP version and then probably switch back to this repository.

**Comment by mikeSimonson** [comment]
if you want to stay on php 5.3, you can use the v1.0.0alpha3 tag.

**Comment by TomasVotruba** [comment]
@mikeSimonson I agree with you. Supporting unsupported version will self-affirm impression it's ok and normal to do that.


I would move to PHP 5.5 soon. [Security fixes support for PHP 5.4 will end in 1 month](http://php.net/supported-versions.php).

@robertfausk

> they won't be able to use doctrine/migrations in future.

You can use (older) current tags to do that.

Recommendation: always try `composer install package/name`, before creating such issues. There are often older versions supporting older PHP. If you don't need functionality of newer PHP, you probably don't need new features (it goes along).
