### ISSUE TITLE
Unneeded sequence generation statements in down method

### ISSUE THREAD

**Issue by greg0ire** [doctrine/migrations#315]
When generating a new migration, the `down` method contains statements for sequence creation (I'm using postgres). The sequences already exist.

For example, here is an excerpt of a migration I just generated with the `diff` command. What is really strange is that the only change I made to the schema was adding a new entity to it (no deletion at all). One sequence is generated for every entity in the project.

```php
$this->addSql('CREATE SEQUENCE my_project_admin_entity_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_contact_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_contract_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_image_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_information_sending_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_library_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_library_offer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_newsletter_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_offer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_prospect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_registration_request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE SEQUENCE my_project_subscriber_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
```

**Comment by mikeSimonson** [comment]
Hi,

The generation of the SQL is not a responsibility of doctrine migrations.
It's done by the DBAL library, can you post your bug report on the DBAL bug tracker.
http://www.doctrine-project.org/jira/browse/DBAL

Thanks

**Comment by greg0ire** [comment]
My version of the dbal library is quite old (because we are working on symfony LTS), so I think I'll try to upgrade first. Thanks a lot, sorry for the noise.

**Comment by stof** [comment]
@greg0ire Symfony LTS is totally compatible with the latest DBAL version (especially given that Symfony itself does not deal with DBAL at all)

**Comment by greg0ire** [comment]
Upgrading the DBAL does the trick, thanks @mikeSimonson and @stof
