### ISSUE TITLE
Issues since "short array" commit

### ISSUE THREAD

**Issue by Molkobain** [doctrine/migrations#325]
Hi everyone,

We can't use doctrine-migrations anymore since [the commit](https://github.com/doctrine/migrations/commit/50a6e18c95ff617325229a4a649d65c1a11445bc) that changed all the ```"array()" to "[]"```.

A synthax error happens in
```vendor/doctrine-migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/DiffCommand.php on line 120``` (PHP Parse error:  syntax error, unexpected '[')

I think it's because we are running PHP 5.3.10 and this synthax only came with PHP 5.4. Would it be possible to get back to the old synthax in order to keep retro-compatiblity ?

Regards,
Guillaume

**Comment by stof** [comment]
The min supported version of this library is PHP 5.4

**Comment by Molkobain** [comment]
Hi stof, where are the requirements specified ?

**Comment by mikeSimonson** [comment]
In the [composer.json](https://github.com/doctrine/migrations/blob/master/composer.json#L13).

Please upgrade your PHP version. It's really easy, the one you are running is not supported anymore and has security vulnerabilities.

**Comment by Molkobain** [comment]
Ok, thanks for the tip.
