### ISSUE TITLE
Migrations should log when particular migration was executed

### ISSUE THREAD

**Issue by bostjan** [doctrine/migrations#331]
This is just a general suggestion, fishing for comments:)

Executed migrations are logged in database, in specified table. But nothing is logged about WHEN particular migration was executed.

I think this would be small but convenient addition to otherwise excellent software.

Please comment.

b.

**Comment by mikeSimonson** [comment]
@bostjan Well I agree but I would like the advice of others. @stof ?

**Comment by stof** [comment]
well, the hard part here is that currently, we just detect whether the migration table exists and we create it when it is not. But we would also have to check whether it is the uptodate one or the old one and create the necessary fields if it is old. We need to find an efficient way to do this as it will run at the beginning of each command.

Otherwise, this seems like a convenient feature.

**Comment by bostjan** [comment]
@mikeSimonson @stof : So, if I am picking up the vibe correctly, it boils down to this question: if I provide a pull request with implementation, will it not go to waste, provided that new code does not totally suck? :)

**Comment by bostjan** [comment]
Another question: datetime field would be preferable?
And another: using UTC (gmdate) would be preferable, but this issue is not yet resolved, right? https://github.com/doctrine/migrations/issues/330

b.

**Comment by mikeSimonson** [comment]
It won't go to waste, but I am wondering if an approach were:
If the datetime field is not there it's not used and if it's there it's used ?

What do you think @stof ?

**Comment by stof** [comment]
@mikeSimonson the issue is that this means that existing projects will never benefit from this feature. And it makes the read query harder as we would not be able to select fields explicitly

**Comment by bostjan** [comment]
@stof you mean those existing projects that do not upgrade doctrine+migrations?

**Comment by stof** [comment]
@bostjan if the suggestion of @mikeSimonson is applied, updating the library is not enough, if the migration table already exists:

> If the datetime field is not there it's not used and if it's there it's used

**Comment by jwage** [comment]
Couldn't we offer a convenient way to migrate the table and add the new column for the datetime?
