### ISSUE TITLE
When replacing autoincrement primary key with string-based one, autoincrement field must be removed first

### ISSUE THREAD

**Issue by bostjan** [doctrine/migrations#332]
This is what doctrine generates:
        $this->addSql('ALTER TABLE Domain DROP PRIMARY KEY'); <-- FAILS
        $this->addSql('ALTER TABLE Domain DROP id');
        $this->addSql('ALTER TABLE Domain ADD PRIMARY KEY (domain)');

What it should generate instead is this:
NEW:$this->addSql('ALTER TABLE Domain CHANGE `id` `id` INT(11) NOT NULL;'); <--- REMOVES A_I
        $this->addSql('ALTER TABLE Domain DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE Domain DROP id');
        $this->addSql('ALTER TABLE Domain ADD PRIMARY KEY (domain)');

Maybe this is by design, just reporting inconvenience.

b.

**Comment by stof** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](http://www.doctrine-project.org/jira/browse/DBAL).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

**Comment by bostjan** [comment]
Ups, I am terribly sorry about this misplaced bug. Thanks for the pointer, Christophe.

http://www.doctrine-project.org/jira/browse/DBAL-1279
