### ISSUE TITLE
Array as PHP5.6

### ISSUE THREAD

**Issue by calincc** [doctrine/migrations#346]
Arrays are defined as PHP5.6 way using [] instead of array() which leads to fatal errors on servers running older versions of PHP. Furthermore, I'm not able to find any old release of doctrine migrations compatible with older PHP versions.

**Comment by mikeSimonson** [comment]
@calincc The [] notation was added in php 5.4 not 5.6. http://php.net/manual/en/migration54.new-features.php

Furthermore php 5.4 will not be supported anymore in less than a month.
The last version of doctrine migrations that support 5.3 is the alpha3 but given the easiness of the migration to 5.6, you have no excuse to stay on unsupported versions.

**Comment by calincc** [comment]
My mistake about PHP version, it is 5.4 not 5.6. Anyway, considering the fact that not all developers choose what PHP version have on the server and that 31.4% of PHP websites run on PHP 5.3 according to <a href="http://w3techs.com/technologies/details/pl-php/5.3/all">w3techs</a>, I still consider this is a major issue.

**Comment by chrisguitarguy** [comment]
This was already discussed in #308

**Comment by mikeSimonson** [comment]
@calincc Because 31.4% of hosting provider are irresponsible, I don't need to be irresponsible too.

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html
