### ISSUE TITLE
Recursive regex finder doesn't allow for multiple namespaces

### ISSUE THREAD

**Issue by liquorvicar** [doctrine/migrations#348]
This may be a feature rather than a bug per se but it confused the hell of out of me for a while. If you pass a namespace into the RecursiveRegexFinder, then all classes that it finds will be prefixed with that namespace. In practice this doesn't currently cause any issues as the files are included at the point they are identified in the file system so the classes should always be loaded.

If you don't pass in a namespace, the classes get added to the global namespace.

It's a bit annoying stylistically as to keep compatibility with the PSRs I'd like to namespace migrations in different folders properly.

Could we perhaps grab the namespace from the file (if there is one) if no namespace is passed in?

**Comment by mikeSimonson** [comment]
What would be your use case for that and won't it add to many different behaviour ?

**Comment by liquorvicar** [comment]
No real use case at the moment (as I said it works fine); it just bothers me that the migration classes don't follow PSR-compatible namespaces if you use multiple dirs. It did cause me some headaches when trying to fix something else as what worked in my app in vagrant didn't work in the tests. In the app the migration classes are loaded fine as the file is required so the class is loaded. In the tests it couldn't find all the migration classes.

I think the behaviour should be fairly straightforward and should retain BC, i.e.
- if you pass a namespace in then it uses that,
- otherwise, if you pass in null, it tries to get the namespace from the migration file itself
- if it can't get the namespace, it uses the global namespace

It would mean a change to the bundle to allow setting the namespace to null in the config but otherwise should work ok.

**Comment by mikeSimonson** [comment]
@liquorvicar How do you get the namespace from the file itself ?

**Comment by liquorvicar** [comment]
@mikeSimonson grep/preg etc Unless there's a clever way in php to get the meta info of the last class loaded/compiled etc

**Comment by chrisguitarguy** [comment]
@mikeSimonson I think the best approach here would be to not define the namespace in configuration. Instead, recursively search the directory (or directories) and find all files that match the pattern and include them. Then [`get_declared_classes`](http://php.net/manual/en/function.get-declared-classes.php) and check if the classes are in one of the directories. This is how some of the [doctrine persistence stuff works](https://github.com/doctrine/common/blob/773c56e51fc26ae07a47146fae31b320dd6cada3/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php#L193).

**Comment by jwage** [comment]
I would be open to accepting this change for 2.0 if someone wants to implement it. I would also be open to implementing it myself but frankly I don't understand :) If someone can explain better please do.

**Comment by jwage** [comment]
@chrisguitarguy is going to take a stab at implementing this.
