### ISSUE TITLE
Skipped migration is marked as migrated

### ISSUE THREAD

**Issue by leopro** [doctrine/migrations#349]
Hi,

I need to write a migration that I want skip for now, so I used the AbstractMigration::skipIf() method.
Even so the migration is always marked as executed (and the "migration_versions" table is updated). 

The cause is https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L329

Unless that is a desired behaviour, I can open a PR with the fix.

**Comment by mikeSimonson** [comment]
@leopro Hi,

Well, what is your use case to write a migration that you migrate but that you want skipped ?

**Comment by leopro** [comment]
Hi @mikeSimonson 

We are going to deploy a new feature in two step. 
First step will be backwards compatible. The second will not. 
We have a switch on the app conf (to move from first to second step) but the second step requires that migration.

I solved throwing a generic exception inside the migration based on a conf parameter.
Anyway, I'm missing the point to have a skip method that does not skip properly.

**Comment by mikeSimonson** [comment]
@leopro I have no idea how this feature was supposed to be used in the first place. Will try to ask to have a better understanding of what it's supposed to do but it looks like it's not really consistent.

On the other hand in your case the it makes more sense to have 3 migrations and to first migrate up until the BC one and then the 2 next.

No need for an if stmt here

**Comment by leopro** [comment]
Hi @mikeSimonson 

I'm not talking about an if statement. My idea is to remove the whole block (rows 326-333).
But maybe I'm misunderstanding the meaning of "skip".

Also having a skip that does not mark the migration as migrated, can help on another behaviour: in fact could be very useful have the chance to apply migrations pre/post deploy.

BTW in my scenario I have just one migration, then the proposed solution can't work.

**Comment by mikeSimonson** [comment]
@leopro Well then why isn't your migration splitted in 3 as it does apparently 3 differents stuff.

I don't get how you would use the skip method for a pre/post deploy. Can you give an example.

Do you know that there is pre/post(up|down) methods ?

**Comment by leopro** [comment]
@mikeSimonson 

Never mind about my use case, probably I can't explain it well.

About pre/post.
I'd like to extend the console command adding a new option "foo" (we already have extended the commands).
Then based on "foo" run some migrations before deploy the new code and some other migrations after that.

Anyway what I'm still not understanding is what "skip" means for you.

**Comment by mikeSimonson** [comment]
@leopro About skip, I have never used it, so I try to understand what it was supposed to mean.

About your pre/post, I suggest that you make your own migration command that will call doctrine migration with different configurations based on your foo param. That way your command will stay small and clean.
