### ISSUE TITLE
Release file for version 1.0 is missing composer.json

### ISSUE THREAD

**Issue by mficzel** [doctrine/migrations#355]
The release file on github for the version 1.0 are incomplete. (https://github.com/doctrine/migrations/archive/v1.0.0.tar.gz). The worst problem is that they are missing the composer.json file and so break composer-setups. If the installation is done with `composer install --prefer-source` everything is fine as before.

**Comment by stof** [comment]
composer does not read the composer.json from inside the archive

**Comment by mficzel** [comment]
I tested on 2 machines and the installed package missed the "composer.json"-file after installation. With composer install --prefer-source it worked. I cannot say for sure that this is not a composer issue but the result is broken.

**Comment by stof** [comment]
@mficzel and not having the composer.json in the archive is **perfectly fine**. composer will **never** read this file from the archive it downloads. It gets the metadata from Packagist

**Comment by mficzel** [comment]
So maybe packagist has the issue ... weird ... i will try to verify that.

**Comment by stof** [comment]
@mficzel what is the issue you have (the fact that there is no composer.json in the vendor folder for the package is not an issue, given that composer does not need it).

**Comment by mficzel** [comment]
I think something was wrong with packagist. Now i get the correct packages again. Sorry for bothering you.

**Comment by mikeSimonson** [comment]
@mficzel no problem, I learned some stuff :p

**Comment by kdambekalns** [comment]
I still think this is an issue - not for composer (using Packagist), but still… see my comment on https://github.com/doctrine/migrations/commit/3a787de7c4a64460436dc2eb2e3cde8920d5fadd
