### ISSUE TITLE
migrations:migrate 0 fails to run

### ISSUE THREAD

**Issue by przemoli** [doctrine/migrations#359]
Using doctrine migrations symfony bundle, but I think its migrations issue:

```shell
doctrine:migrations:migrate --dry-run 0
                                                              
                    Application Migrations                    
                                                              

Unknown version: 0
```
Docks says that its proper way to revert migrations. You specify one of previous migrations.

**Comment by przemoli** [comment]
Workaround doctrine migrations:execute --down NUMBER_FOR_CURRENT_MIGRATION

**Comment by stof** [comment]
@przemoli note that your workaround is not equivalent. You will revert only the last migration (which is the same than ``doctrine:migrations:migrate prev`` btw).

**Comment by przemoli** [comment]
Hmm, for me it was.

I had only single test migration. Did not checked if bug persists when migratind down from one migration to another.

**Comment by stof** [comment]
@przemoli if you have a single migration, reverting everything is indeed equivalent to reverting the last one. But it is not true in the generic case, and so it could confuse people reading this later.

**Comment by mikeSimonson** [comment]
@przemoli --dry-run is to test one migration file

As for the 0 the documenation has been corrected but still needs to be deployed.
@stof can you deploy it in the symfony documentation.
