### ISSUE TITLE
migrations:status --show-version shows all executed migrations under "executed unavailable"

### ISSUE THREAD

**Issue by flarelt** [doctrine/migrations#361]
**Run:**
   doctrine:migrations:status --show-version

**Result:**
"Available Migration Versions" and "Previously Executed Unavailable Migration Versions" lists contain same migration numbers. Available migration versions are shown under both lists.

**Expected result:**
"Previously Executed Unavailable Migration Versions" should contain only migrations that are executed but no longer available.

**Fix:** https://github.com/doctrine/migrations/pull/360

**Comment by mikeSimonson** [comment]
Thanks for the report @flarelt see the PR for the comments.

**Comment by mikeSimonson** [comment]
@flarelt it's fixed and in the last release.
