### ISSUE TITLE
Phar missing for 1.1.0 release

### ISSUE THREAD

**Issue by vincentlepot** [doctrine/migrations#363]
I think you forgot to add the phar for downloads in the 1.1.0 release.

This link is referenced in the README, and I believe this can save people time, not rebuilding it from source.

**Comment by mikeSimonson** [comment]
@vincentlepot thanks for the report. I didn't do the release and I totally forgot to check that.

**Comment by mikeSimonson** [comment]
done

**Comment by mikeSimonson** [comment]
done

**Comment by vincentlepot** [comment]
Thanks! @mikeSimonson

**Comment by stof** [comment]
yeah sorry. I forgot the phar when releasing.
