### ISSUE TITLE
Fulltext index on unique column ignored 

### ISSUE THREAD

**Issue by csasarak** [doctrine/migrations#382]
I'm working on a MariaDB database with a table with a name which is set to be unique on the table. I also want a fulltext index which is supported with the flags variable in Doctrine annotations as described [here](http://www.doctrine-project.org/jira/browse/DDC-3014). The problem is that when I try to generate a migration (or even create the schema) Doctrine ignores the fact that the fulltext index is different than the index it would create for the unique constraint and doesn't bother making the fulltext index. 

The main reason I want to use fulltext rather than a normal index is because MariaDB can return a [relevance](https://mariadb.com/kb/en/mariadb/fulltext-index-overview/#relevance) score for any matches, unlike using SQL's "LIKE". This can be worked around by adding a 'where' clause to the options parameter to the effect of "where id is not null", which is always true but convinces Doctrine that this index is different than the uniqueness index. 

An example entity of what I'm describing might look like this:
```php
/**
 * 
 *
 * @ORM\Table("fieldname", 
    uniqueConstraints={@ORM\UniqueConstraint(name="name", columns={"name"})},  
    indexes={@ORM\Index(name="fulltext_index", 
                        columns={"name"},
                        flags={"fulltext"})})
 * @ORM\Entity
 */
class ExampleEntity {
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
}
```

I'm willing to dive in and try to make Doctrine migrations (or is it the ORM that's the problem?) aware of the fact that if there's a flags variable on such an index annotation then it should create the index. I'm aware my use case is probably pretty idiosyncratic. So first I wanted to make sure that this wasn't purposeful and that it makes sense to consider this a bug that's worth fixing.

**Comment by mikeSimonson** [comment]
Hi,

I think that it's a dbal issue as it's what doctrine migration use to generate the sql.
You should report it on their bug tracker. http://www.doctrine-project.org/jira/browse/DBAL

Thanks for the report @csasarak

**Comment by beberlei** [comment]
Indeed, The problem is that DBAL tries to detect overindexing when generating schemas and removes the indexes with less options. I think this algorithm ignores the index flags feature that we added later.

**Comment by csasarak** [comment]
Thank you both! I'll submit it to DBAL's issue tracker.
