### ISSUE TITLE
Tag/Release is missing to support SF3

### ISSUE THREAD

**Issue by Ravetracer** [doctrine/migrations#384]
Hi there,

I just wanted to install doctrine/migrations bundle for using in Symfony v3.0.0, but the tag/release is still missing. Could you please add it?

Regards,
Christian

**Comment by mikeSimonson** [comment]
It's in the works but the yaml library 3.0 seems to break some test.

**Comment by Ravetracer** [comment]
Ah, ok. Thank you for the information!

**Comment by kamazee** [comment]
Tests seem to pass with symfony/yaml at version 3.0.0.
Has the problem been fixed?

**Comment by mikeSimonson** [comment]
the yaml issue has been fixed by https://github.com/doctrine/migrations/commit/af3cce7d2e490ead821fcbdb54b4772b4913ee1d but there is still another issue that I willl fix tomorrow.

**Comment by kamazee** [comment]
@mikeSimonson thanks!
Feel free to share the details if you need a hand!

**Comment by mikeSimonson** [comment]
it's done
