### ISSUE TITLE
(mssql) Problem with method addColumn when i need to set default in existing table with data

### ISSUE THREAD

**Issue by inferno1992** [doctrine/migrations#392]
When i use code $schema->getTable('users')->addColumn('sex' , 'integer')->setDefault(0)
Doctrine built two Queries: 
1. Alter table...
and second
2. Add constraint

Migrations throws errow on first query.

Error shows up only when i have data in table users.

I found solution, adding custom SQLServer2012Platform but there is a lot of private method that i need to copy.

A simillar problem happend when a try drop column with constraint.

**Comment by mikeSimonson** [comment]
This bug is about dbal. Can you post the bug report there https://github.com/doctrine/dbal/issues?

Thanks @inferno1992

**Comment by inferno1992** [comment]
Yes, thx
