### ISSUE TITLE
[proposal] it should handle multi statement SQL gracefully

### ISSUE THREAD

**Issue by docteurklein** [doctrine/migrations#427]
Currently, if I pass a multi statement sql query, and that one of the statements (except first) is wrong (error),  the migration still thinks everything is well.

A potential solution would be to use PDO::nextRowSet() to detect failures in any statement.

PS: using mysql driver.

**Comment by mikeSimonson** [comment]
Hi @docteurklein,
Passing multiple query in the same addSql is not supported.
It should fail and it does fail with every other drivers.
Sadly there is no reasonable way for us to check for that.
I would recommend to use the mysqli driver.

**Comment by acasademont** [comment]
Hi @mikeSimonson is this a problem of the mysqlnd driver?

**Comment by mikeSimonson** [comment]
@acasademont It's a PDO bug to allow mutli sql stmts to be passed in one call. It has nothing to do with mysql mysqli or mysqlnd. There is no sane way for us to detect that and prevent it.
