### ISSUE TITLE
Disabling foreign keys check

### ISSUE THREAD

**Issue by kaligrafy** [doctrine/migrations#43]
Would it be possible to add these before and after diff commands:

SET FOREIGN_KEY_CHECKS=0;

SET FOREIGN_KEY_CHECKS=1;

because when we change primary keys, executing version will return a mysql error on foreign keys integrity.

**Comment by razcakappa** [comment]
@kaligrafy Can i know which options should pass to `php bin/console doctrine:schema:update` for set `SET FOREIGN_KEY_CHECKS=0;`

**Comment by quazardous** [comment]
Hi,

I'm working with pretty big innodb tables and I need partitions more than foreign keys.

So I would love to be able to explicitly disable foreign key check/generation with a cool annotation...

@stof should I report a new issue ?

**Comment by stof** [comment]
This should be a feature request in DBAL (and maybe another one for the ORM dependign on the desired API). doctrine/migrations is **not** responsible for generating the SQL when generating a migration. It uses whatever the DBAL schema comparator generates.

**Comment by inceddy** [comment]
One might try the following:

```php
$migrationSubscriber = new class implements Doctrine\Common\EventSubscriber {
  public function getSubscribedEvents() : array
  {
    return [
      Doctrine\Migrations\Events::onMigrationsMigrating,
      Doctrine\Migrations\Events::onMigrationsMigrated
    ];
  }

  public function onMigrationsMigrating(Doctrine\Migrations\Event\MigrationsEventArgs $args) : void
  {
    if ($args->isDryRun()) {
      return;
    }

    echo "Disable foreign key check\n";
    $args->getConnection()->executeQuery("SET FOREIGN_KEY_CHECKS=0;");
  }

  public function onMigrationsMigrated(Doctrine\Migrations\Event\MigrationsEventArgs $args) : void
  {
    if ($args->isDryRun()) {
      return;
    }

    echo "Enable foreign key check\n";
    $args->getConnection()->executeQuery("SET FOREIGN_KEY_CHECKS=1;");
  }
};

$connection->getEventManager()->addEventSubscriber(new $migrationSubscriber());
```

**Comment by aronbeal** [comment]
Needed to circumvent this issue for local fixture rebuilding for a project recently, and I've added https://github.com/aronbeal/doctrine-foreign-key-checks as a custom doctrine command to toggle foreign key checks.    It does have the advantage that it can work in isolation, but it is not a viable workaround for many cases - the setting must be set globally to persist between sessions, which means that `SUPER` privilege is required.  For our use (local development), we're able to grant that, so the solution works.   

Offered without warranty, feel free to use or repurpose if it helps any Symfony user's use case here
