### ISSUE TITLE
./migrations migrations:diff

### ISSUE THREAD

**Issue by lferro9000** [doctrine/migrations#438]
Migrations diff fails to generate new version from the models.

http://doctrine-orm.readthedocs.org/projects/doctrine-migrations/en/latest/reference/generating_migrations.html

The command states that a new version is generated with the commands required to update the database, however, the command fails with a message like:

    vendor/bin/doctrine-migrations 'migrations:diff'
    Loading configuration from file: migrations.xml

      [Doctrine\DBAL\Schema\SchemaException]               
      The table with name 'database.tablename' already exists.  
 
This defeats the purpose of changing the structure on the models and use this command to generate the upgrade difference as a version (as the command description implies).

Am i doing or assuming something wrong? 

Note: The current configuration is able to upgrade / downgrade existing migrations, just not able to generate a new migration by using the diff command.

**Comment by mikeSimonson** [comment]
@lferro9000 This should indeed works.

What's your version of doctrine migrations ? ``migrations --version``
Can you validate your entity mapping?

Thanks

**Comment by mikeSimonson** [comment]
Closing for lack of informations.
