### ISSUE TITLE
doctrine:migration:diff on a postgresql database generate "CREATE SCHEMA public" on the down method

### ISSUE THREAD

**Issue by josensanchez** [doctrine/migrations#441]
I'm not using the public schema, so every table is in others schemas.
 i.e:

app.fos_user
data.somtable
gis.postgis_tables

but it doesn't mean that the schema public does not exist. It exist already.

performing the doctrine:migration:diff generate the creation of the public schema

this happens even with the database up to date: It generate an empty up method and only

`$this->addSql('CREATE SCHEMA public');`

in the down method.

probably it's a doctrine issue and most probably is that it's related to

https://github.com/doctrine/doctrine2/issues/4777

but it's supposed to be solved. Before reopen it I want to be sure that its not related to this project.

I'm using doctrine-migrations 1.1.1 for symfony 3.0

**Comment by chrisguitarguy** [comment]
This is an issue with DBAL's Schema API, not the ORM. That's why that issue was closed -- without any feedback on why :(

Looks like it's still a bug in DBAL (not in migrations itself) https://github.com/doctrine/dbal/issues/1110

**Comment by mikeSimonson** [comment]
It is indeed a DBAL issue.

Thanks @chrisguitarguy @josensanchez
