### ISSUE TITLE
PHP 5.6 not supported?

### ISSUE THREAD

**Issue by benboit** [doctrine/migrations#442]
Im not able to install the most version version of the package using composer running PHP 5.6. Is this probably a mistake in the composer dependencies?

**Comment by mikeSimonson** [comment]
What is the error message from composer ?
Does it fail if you try to run ``composer require doctrine/migrations`` inside a new empty folder ? (After a ``composer init``)

**Comment by benboit** [comment]
It says my PHP Version doesnt meet the requirements. From what i saw the required Version in composer.json might be configured wrong. Isnt | supposed to mean Or?

**Comment by mikeSimonson** [comment]
@benboit Can you clone the repo on your machine and edit the composer.json by replacing the php version requirement to ``"php": "^5.5||^7.0",``. And then run composer install ?

**Comment by benboit** [comment]
In an empty folder this works. But when im in my project it wont. Any idea?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/migrations v1.4.0 -> satisfiable by doctrine/migrations[v1.4.0].
    - doctrine/migrations v1.4.0 requires php ^5.5|^7.0 -> your PHP version (5.6.17-0+deb8u1) overriden by "config.platform.php" version (5.4) does not satisfy that requirement.

**Comment by chrisguitarguy** [comment]
> overriden by "config.platform.php" version (5.4) does not satisfy that requirement.

Do you have [platform](https://getcomposer.org/doc/06-config.md#platform) in your composer config section?

````json
{
  "config": {
    "platform": {"php": "5.4"}
  }
}
```

Or something like that?

**Comment by benboit** [comment]
Yep, sorry. Seems to be my fault (the base technology distributed this composer.json).

Nevermind ;)
