### ISSUE TITLE
[Bug] Doctrine migration migrate with no migration

### ISSUE THREAD

**Issue by noniagriconomie** [doctrine/migrations#445]
Hi,

I just wanted to know why the command ```doctrine:migration:migrate``` throws an Exception ```(Could not find any migrations to execute.)```

In a bash script it cause the whole script to stop, why not just output an error or log ?

Is there a good reason?

Many thanks for the answer :)

**Comment by mikeSimonson** [comment]
It's a dev tool. We want to know about issue sooner than later.
If you want to do provisioning you can use the --allow-no-migration option.
Then it won't throw an exception.

**Comment by noniagriconomie** [comment]
@mikeSimonson ty for your answer
I have updated the and now have this option
many thanks :)
