### ISSUE TITLE
how can i register enum as string in doctrine migrations file ? 

### ISSUE THREAD

**Issue by jl91** [doctrine/migrations#455]
i have configured doctrine migrations, but, i have one trouble. When i try to use 

php doctrine-migrations.phar migration:migrate --db-configuration ./migration/init.php --configuration ./migration/migrations.xml

if my db has no column with enum type it's ok, but, if no, it thown an exception: 

[Doctrine\DBAL\DBALException]                                                                    
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

I always solve this exception in another projects with :

$platform = $em->getConnection()->getDatabasePlatform();
$platform->registerDoctrineTypeMapping('enum', 'string');

But i don't see where i have to register that configs in doctrine-migration.phar

Someone can help me ?

**Comment by mikeSimonson** [comment]
In a way you answered your question.
You configured that connection to add the enum mapping.
Now you just need to tell doctrine migration to use that connection with the ``--db-configuration`` command line option.

**Comment by jl91** [comment]
a create my own cli.php with that configurations , but, even if i run . php ./cli.php migration:migrate  --configuration migrations.xml the application doesnt reconize the 

$connection->getDatabasePlatform()
    ->registerDoctrineTypeMapping('enum', 'string');

`
require_once(__DIR__ . '/../vendor/autoload.php');
use Symfony\Component\Console;
use Doctrine\DBAL\Migrations\MigrationsVersion;
use Doctrine\DBAL\Migrations\Tools\Console\Command as MigrationsCommand;
use Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper;

if (file_exists('migrations-db.php')) {
    $params = include './migrations-db.php';
    if (!is_array($params)) {
        throw new \InvalidArgumentException('The connection file has to return an array.');
    }
    $connection = \Doctrine\DBAL\DriverManager::getConnection($params);
} else {
    throw new \InvalidArgumentException('Missing "migrations-db.php" file. Alternatively use --db-configuration.');
}

$connection->getDatabasePlatform()
    ->registerDoctrineTypeMapping('enum', 'string');

$helperSet = new Console\Helper\HelperSet();
$helperSet->set(new Console\Helper\QuestionHelper(), 'dialog');
$helperSet->set(new ConnectionHelper($connection), 'connection');

// Instantiate console application
$cli = new Console\Application('Doctrine Migrations', MigrationsVersion::VERSION());
$cli->setCatchExceptions(true);

$cli->setHelperSet($helperSet);

// Add Migrations commands
$commands = array();
$commands[] = new MigrationsCommand\ExecuteCommand();
$commands[] = new MigrationsCommand\GenerateCommand();
$commands[] = new MigrationsCommand\LatestCommand();
$commands[] = new MigrationsCommand\MigrateCommand();
$commands[] = new MigrationsCommand\StatusCommand();
$commands[] = new MigrationsCommand\VersionCommand();

// remove the "migrations:" prefix on each command name
foreach ($commands as $command) {
    $command->setName(str_replace('migration:', '', $command->getName()));
}
$cli->addCommands($commands);


// Run!
$cli->run();`

**Comment by jl91** [comment]
I fixed that. I just rename my "migrations-db.php" to any other name, and instantiate my new cli with the connection like in this up code.
