### ISSUE TITLE
Feature Request:  Add timestamp to migration table

### ISSUE THREAD

**Issue by wshafer** [doctrine/migrations#459]
Hey Guys,

Quick feature request. It would be nice to know when a particular migration ran. A time stamp added to the versions table would be nice.

Use Case: We had a migration that ran which deleted a needed column for reporting. Unfortunately I don't know when the migration actually ran to try and recover the data from backups.

Thanks in advance,
Westin

**Comment by JHGitty** [comment]
:+1: +1

**Comment by kilhage** [comment]
:+1:

**Comment by stof** [comment]
Duplicate of https://github.com/doctrine/migrations/issues/331
