### ISSUE TITLE
Prevent duplicate DROP FOREIGN KEY

### ISSUE THREAD

**Issue by JHGitty** [doctrine/migrations#460]
I have often seen that the generated migration script tries to do the same SQL query multiple times, for example:

```
$this->addSql('ALTER TABLE news_newsletter_mailing DROP FOREIGN KEY FK_FB48B08B22DB1917');
```

I cannot give you any working example how to regenerate it but I have seen this multiple times in different applications. The script itself works fine until it tries to run the same SQL query again in the same migration script:

```
Migration 20160509214556 failed during Execution. Error An exception occurred while executing 'ALTER TABLE news_newsletter_mailing DROP FOREIGN KEY FK_FB48B08B22DB1917':
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'FK_FB48B08B22DB1917'; check that column/key exists
```

There must be any issue that result into duplicate SQL queries for ``DROP FOREIGN KEY`` in the generated migration code.

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue @JHGitty
