### ISSUE TITLE
RENAME TABLE instead of re-creation

### ISSUE THREAD

**Issue by JHGitty** [doctrine/migrations#461]
If I change the table name it will result into ``DROP TABLE`` and ``CREATE TABLE`` sql queries. This will result into a data-loss. It would be better to use the ``RENAME TABLE`` feature.

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

I think that the fundamental issue here is the fact that anyway the comparator has no way of knowing if you deleted a table and created a new one fairly similar or if you renamed it. Hence it will always consider the delete and create method as it's the only safe assumption he can make.
The auto generated sql can only be a draft for your migration code.
