### ISSUE TITLE
Invalid foreign keys in the down() method.

### ISSUE THREAD

**Issue by piotr-s-skygate** [doctrine/migrations#465]
After running doctrine:migrations:diff for a particular database schema, I obtain the following in my migration file:

public function up(Schema $schema)
...       
$this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_983D1F3EFE54D947');
$this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_983D1F3EA76ED395');
$this->addSql('DROP INDEX idx_983d1f3ea76ed395 ON user_group');
$this->addSql('CREATE INDEX IDX_81305A8A76ED395 ON user_group (user_id)');
$this->addSql('DROP INDEX idx_983d1f3efe54d947 ON user_group');
$this->addSql('CREATE INDEX IDX_81305A8FE54D947 ON user_group (group_id)');
$this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_983D1F3EFE54D947 FOREIGN KEY (group_id) REFERENCES group (id)');
$this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_983D1F3EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');

...
public function down(Schema $schema)
...
$this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_81305A8A76ED395');
$this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_81305A8FE54D947');
$this->addSql('DROP INDEX idx_81305a8a76ed395 ON user_group');
$this->addSql('CREATE INDEX IDX_983D1F3EA76ED395 ON user_group (user_id)');
$this->addSql('DROP INDEX idx_81305a8fe54d947 ON user_group');
$this->addSql('CREATE INDEX IDX_983D1F3EFE54D947 ON user_group (group_id)');
$this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_81305A8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
$this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_81305A8FE54D947 FOREIGN KEY (group_id) REFERENCES group (id)');

Running `doctrine:migrations:execute migration_nr` is ok. However `doctrine:migrations:execute migration_nr --down` throws the following error:

Migration migration_nr failed during Execution. Error An exception occurred while executing 'ALTER TABLE user_group DROP FOREIGN KEY FK_81305A8A76ED395':

SQLSTATE[HY000]: General error: 1025 Error on rename of './my_project/user_group' to './my_project/#sql2-1d9-bc' (errno: 152)

When I change manually the foreign keys in the down() method, by replacing in the first two lines FK_81305A8A76ED395 into FK_983D1F3EFE54D947, it works.

I suppose the generated foreign keys in the down() method are invalid.

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.

**Comment by piotr-s-skygate** [comment]
Thanks.
I reported it on https://github.com/doctrine/dbal/issues/2406 .
