### ISSUE TITLE
--write-sql creates broken sql files on postgresql

### ISSUE THREAD

**Issue by rommsen** [doctrine/migrations#466]
It writes comments about the migration into the sql file (see [here](https://github.com/doctrine/migrations/blob/0d0ff5da10c5d30846da32060bd9e357abf70a05/lib/Doctrine/DBAL/Migrations/Migration.php#L95)). Unfortunately it uses the # character which is only a comment in Mysql but not in Postgresql (here it is an [operator](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-SPECIAL-CHARS)).

Because of this we have to transform the file each time before we can actually use it.

I think changing it to `/* */` or `-- ` would be the best way because this is pretty standard among the different vendors. (e.g.: [postgresql](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS), [mysql](http://dev.mysql.com/doc/refman/5.7/en/comments.html), [oracle](https://docs.oracle.com/cd/B14117_01/server.101/b10759/sql_elements006.htm))

**Comment by stof** [comment]
It should indeed use ``-- `` which is the standard comment marker in SQL
