### ISSUE TITLE
Weird behavior with command doctrine:migrations:migrate

### ISSUE THREAD

**Issue by BboyKeen** [doctrine/migrations#467]
I noticed using the migrate command without argument that DoctrineMigrations assumes that all migrations below the latest migration should be executed.

Sometimes it results in migrating older versions than the current one which often ends with a schema conflict.
Is this really the expected behavior ? If so, in which case would it be used ?

**Comment by stof** [comment]
this is expected. Migrations are meant to be built on top of each other.

If you want to execute a single migration, use ``doctrine:migrations:execute``

**Comment by BboyKeen** [comment]
I understand your point but let's say I'm currently developing a new feature :
-  I've used the schema:update command to sync at first my database with my model
- I've inserted the last migration version in the database

Some older migrations files bringing a part of the same changes introduced by the schema:update are currently present in the DoctrineMigrations folder and I decide to write new migrations on top of these one.

What would be the good way to easily test them in dev if I can't assume that Doctrine will only try to migrate from the current version in database ?
Don't know if my workflow is the good one or if there is a better way to do this.

**Comment by mikeSimonson** [comment]
By using doctrine:shema:update you are basicly saying that your don't care about the data already in the database. If you don't want to migrate data why using doctrine migrations in the first place.

**Comment by BboyKeen** [comment]
Not at all.
In dev, I don't care about data because test data is introduced by fixtures.
But my migrations will then be used to migrate my schema in production, so I have to test somewhere that the migrations ends well when I migrate from the same schema as the schema in production, right ?
If there is a better way to handle this, I'll be glad to hear about it :)

**Comment by chrisguitarguy** [comment]
On dev, do your thing and use `doctrine:schema:update` and such until you're done making schema changes. Then, when you're ready...

1. `git checkout master` (or whatever your default branch is) 
1. Run `doctrine:schema:update` to drop the changes you made
1. `git checkout the_feature_branch`
1. Run `doctrine:migrations:diff` to generate your migration and commit it
1. Run `doctrine:migrations:migrate` to execute migration you just created

Your workflow can remain around the nice and easy `doctrine:schema:update` stuff you're used to, but really if you want to use migrations you have to buy into them more fully. Run them on your dev machine and run them on your staging/prod database the same way.

Whether or not this is a good idea is questionable, but I've used it a few times before. Generally I try to do everything but the database schema, then once my code has settled into what it will be, I can make configure the schema and create a migration and run it just once before moving onto integration/acceptance testing.

**Comment by mikeSimonson** [comment]
You only make migration for version that are in production somewhere already.
Otherwise you don't need them.
As soon as you have a migration you can't use ```doctrine:schema:update``` anymore.

**Comment by BboyKeen** [comment]
It was the point I didn't understand. I will follow the workflow suggested by chrisguitarguy. 
Thanks for taking the time @chrisguitarguy and @mikeSimonson. It's clearer now.
