### ISSUE TITLE
Percona toolkit pt-online-schema-change integration

### ISSUE THREAD

**Issue by rossmotley** [doctrine/migrations#468]
Hi,

A really handy feature for us would be the integration of [Percona Toolkit](https://www.percona.com/doc/percona-toolkit/)'s [pt-online-schema-change](https://www.percona.com/doc/percona-toolkit/2.2/pt-online-schema-change.html) in some way. It's a great tool for executing migrations on large tables without blocking access to them, currently we're using the tool manually for migrations which need it.

It would be great if we could do something like this in our up/down methods:

``` php
$command = PerconaCommand::create("ADD new_field INT(10) DEFAULT NULL", "huge_table");

$this->addCommand($command);
```

Would this be useful for others?

Thanks,

Ross

There's a similar tool for ruby here: https://github.com/svarks/percona-migrations

**Comment by mikeSimonson** [comment]
That would be perfect.

**Comment by chrisguitarguy** [comment]
Maybe a solution here is to provide some way to hook into migrations and perform actions. Keep the core of the migrations library pretty simple, but let others extend it with whatever they like.

A simple set of events would probably be sufficient and there's already an event emitter provided by DBAL (`Connection::getEventManager`). Using that would also make the event listeners pretty easy to integrate with Symfony -- just tag things with `doctrine.event_{listener,subscriber}` in the container. There's probably something similar in the various other frameworks.

**Comment by chrisguitarguy** [comment]
@rossmotley I made a small example of how something like this might work -- not with `pt-online-schema-change`, but with a more generic "run a cli command" type thing.

https://github.com/chrisguitarguy/cli-migrations-example

The basic gist is you [extend a custom migration base class](https://github.com/chrisguitarguy/cli-migrations-example/blob/f4a3fa89c728060c31604c76d0f377b11c1d5deb/migrations/Version00000000000001.php#L9) that would let you `addCommand` in the `up` and `down` methods. And an event listener would [hook in](https://github.com/chrisguitarguy/cli-migrations-example/blob/f4a3fa89c728060c31604c76d0f377b11c1d5deb/cli-config.php#L11) and [run those commands](https://github.com/chrisguitarguy/cli-migrations-example/blob/f4a3fa89c728060c31604c76d0f377b11c1d5deb/src/CliMigrationListener.php#L23-L40) after the version has been executed.

![screen shot 2017-03-11 at 2 43 44 pm](https://cloud.githubusercontent.com/assets/1010392/23826385/30f66e30-0669-11e7-92e6-415a19591306.png)

**Comment by rossmotley** [comment]
@chrisguitarguy - that looks really interesting! 

One thing I noticed, It looks like if the command fails it will throw an exception, but that maybe the migration version will not be rolled back because the transaction has been committed before then.

I think that could be resolved with a new new event which would happen during the "EXEC" stage in  
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L290

Apart from that, it looks like this would work well for us. Were you thinking of creating a new repo for it? I might be able to spend a bit of time on it.

**Comment by chrisguitarguy** [comment]
> I  think that could be resolved with a new new event which would happen during the "EXEC" stage in

Or by moving the executed event before the commit. I think that probably makes more sense: if any event listeners fail, the migration as a whole should fail.

**Comment by chrisguitarguy** [comment]
Circling back to this (because I find myself doing issue triage):

> One thing I noticed, It looks like if the command fails it will throw an exception, but that maybe the migration version will not be rolled back because the transaction has been committed before then.

I suspect that SQL + pt-* commands shouldn't happen in the same migration? That could be enforced by whatever implementing library comes into play for this.

Since we have events officially now that 1.6 is out, then issue can probably be closed.

**Comment by alcaeus** [comment]
I'll take your word for it, @chrisguitarguy: closing. Thanks for following up! ❤️
