### ISSUE TITLE
Loading configuration from migrations.php failed

### ISSUE THREAD

**Issue by odan** [doctrine/migrations#469]
I have to load the configuration from a PHP file: migrations.php

```php
return array(
    'name' => 'Doctrine Migrations',
    'migrations_namespace' => 'DoctrineMigrations',
    'table_name' => 'doctrine_migrations',
    'migrations_directory' => realpath(__DIR__ . '/../Migration'),
    'migrations' => array()
);
```

**Error message**

 [InvalidArgumentException]
  You have to specify a --db-configuration file or pass a Database Connection as a dependency to the Migrations.

**Expected behavior**
Loading configuration from file: migrations.php

**Bugfix**

I've found the bug here on line 80:
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Helper/ConfigurationHelper.php

By adding 'migrations.php' to the array the configuration is loading succesfully from a php file.
```php
$defaultConfig = [
    'migrations.xml',
    'migrations.yml',
    'migrations.yaml',
    'migrations.json',
    'migrations.php'
];
```

**Comment by mikeSimonson** [comment]
Can you add a test for that behavior ?
