### ISSUE TITLE
Support for PHP5.6 

### ISSUE THREAD

**Issue by moacirosa** [doctrine/migrations#473]
Hello Everybody,

I'm making use of `doctrine/migrations` through `doctrine/doctrine-migrations-bundle` dependency. Checking `composer.json` and its _require_ section we'll have:

```json
"require": {
    "php": "^5.5|^7.0",
    "doctrine/dbal": "~2.2",
    "symfony/yaml": "~2.3|~3.0",
    "symfony/console": "~2.3|~3.0",
    "ocramius/proxy-manager": "^1.0|^2.0"
}
```

This way for PHP versions until **5.5** it will install `ocramius/proxy-manager:^1.0`. For greater versions, which obviously include PHP5.6, it will install `ocramius/proxy-manager:^2.0` [which makes use of new PHP7 features](https://github.com/Ocramius/ProxyManager/blob/2.0.2/src/ProxyManager/Autoloader/Autoloader.php).

Considering that Ubuntu:14.04 is the last release which receives **PHP5.5** through `apt-get install` make use of Ubuntu releases like 15.04, 15.10 means receive PHP5.6+ (Ubuntu 16.04LTS already receives PHP7). So my question (finally) is if is that possible support PHP5.6 for scenarios (using some similar _pipe_ approach) where you need more time for testing possible issues with major PHP7 upgrade?

**Comment by stof** [comment]
why will it install ``ocramius/proxy-manager:^2.0`` for 5.6 ? this does not make sense. ocramius/proxy-manager defines a requirement on ``php: ^7.0``, so composer won't select it for PHP 5.6. It will select ``ocramius/proxy-manager`` 1.x

**Comment by stof** [comment]
hmm, reading your post again, I suspect that you don't understand what ``|`` means for Composer

**Comment by moacirosa** [comment]
Yeah... It seems you're right... I'll check it better because after running `$ composer require doctrine/doctrine-migrations-bundle "^1.0"` as suggested in [DoctrineMigrationsBundle](http://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html) documentation I've got issues with PHP7 missing features. Thought it was the source.

Anyway... Thanks for quick feedback

**Comment by mikeSimonson** [comment]
Well that was quick
