### ISSUE TITLE
UUID odd behaviour

### ISSUE THREAD

**Issue by fmonts** [doctrine/migrations#474]
I have the following situation

    class Site
    {
        /**
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         * @ORM\Column(type="integer")
         */
        private $id;
    

        //other fields...
    }

And I want to add a uuid (I don't want to expose the real id, for obvious reasons). So I added:

    /**
     * @ORM\Column
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $uuid;

The odd thing is that when I run `doctrine:schema:update` or `doctrine:migrations:diff`, I get the following output:

    ALTER TABLE sites ADD uuid VARCHAR(255) NOT NULL, CHANGE id id INT NOT NULL;

In other words, the existing `id` column loses its AUTO_INCREMENT, and that breaks a lot of existing relations with other entities...
(also but lesser important, VARCHAR(255) doesn't seem the best choice for such a fixed length value)

The expected behaviour is:
     - add a unique key on the uuid, and leave the AI on the id

**Comment by mikeSimonson** [comment]
Hi @fmonts,

Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.

**Comment by stof** [comment]
``varchar(255)`` is because you have not specified the column type, and so it defaults to ``string``. Use ``@ORM\Column(type="guid")``

**Comment by fmonts** [comment]
@stof yes thank you, I used ramsey/uuid-doctrine to make binary(16) fields
