### ISSUE TITLE
Legacy Docs

### ISSUE THREAD

**Issue by jl91** [doctrine/migrations#481]
Doctrine migration docs have a problem, if you are using a new version of symphony console greater than 2.4 ~ 3.0 (i don't remeber exactly what is the correct version) you should change some classes in this part of docs : http://doctrine-orm.readthedocs.io/en/latest/reference/tools.html#adding-own-commands
say that you must use "`Symfony\Component\Console\Helper\Application`" but in the new versions of symphony console that class was moved to another namespace, change it to : `Symfony\Component\Console\Application`.

Another observation is that in this part of docs : http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/introduction.html#use-as-supplement  the docs say that you should use `\Symfony\Component\Console\Helper\DialogHelper` class, but, that class doesn't exists anymore in the new versions of symphony console, so, you just want to trade that with:  `Symfony\Component\Console\Helper\QuestionHelper as DialogHelper`;
That's all.

**Comment by stof** [comment]
the application class has *never* been inside the ``Helper`` subnamespace. It is just a mistake in the doc, which should get fixed.

**Comment by mikeSimonson** [comment]
Fixed in https://github.com/doctrine/migrations-documentation/commit/a656eaac97725668c771a50bf93f06dd6bc9c86c and https://github.com/doctrine/doctrine2/pull/6113

You might have to wait for the documentation to be updated on the servers.
