### ISSUE TITLE
[ Question ] Queries order

### ISSUE THREAD

**Issue by lplume** [doctrine/migrations#486]
Hello,

i was wondering if someone could help me out to understand how migrations "understand" the order of the query to be executed.

Thanks,

- Mauro

**Comment by mikeSimonson** [comment]
First query to be sent is the first query to be run, why ?

**Comment by mikeSimonson** [comment]
If you talk about the order of the migrations then it's an alphabetical order of the class name.

**Comment by lplume** [comment]
Im sorry, my lack of english. How migration decides the order? An example: first, tables creation; then FKs definition. How to solve the order?

**Comment by stof** [comment]
this project does not decides on the order. When using the ``diff`` command, the order is coming from the DBAL project (as it is the one generating the SQL queries)

**Comment by lplume** [comment]
@stof thanks a lot for the answer.
