### ISSUE TITLE
Make FK hashes dependent on table + column name

### ISSUE THREAD

**Issue by martixy** [doctrine/migrations#488]
I've noticed that when you generate a migration, the FK name is some kind of hash(a hexadecimal value), that's dependent on the column name.

But since FKs are, in a sense, "global" for the database, if you have 2 associations in different tables, but with the same column names, you end up with a name collision, i.e. `(errno: 121 "Duplicate key on write or update")`
This results in annoying errors during migration, which leaves the DB in a messy state, which you then you have to go and manually fix.

**Would it be possible to have hash generation depend of table AND column name?**

Another potentially useful feature would be atomic migrations, where a failure reverts all previous changes. Not sure if DBs and which support this for schema changes, but even without DB support it should be possible to pair statements and use the corresponding down statement on error.

**Comment by stof** [comment]
doctrine/migrations is not responsible for naming foreign keys. It is not even responsible for generating the SQL (this is DBAL's job).

Foreign key names are coming from the code providing the Schema, which is generally the ORM. This is where the issue should be reported (some maintainers are common between the projects, but most ORM maintainers are not involved in doctrine/migrations).
There is nothing doctrine/migrations can do here.

Atomic migrations are already supported in this library when the DB supports DDL statements in transactions (for instance, Postgresql supports it).
Pairing down statements with up statements would require rewriting the library from scratch, as well as rewriting entirely the DBAL schema comparator generating the SQL to have a chance to do it. And this will probably make the library much harder to use. So I don't think this will happen.

I'm closing this issue as it is the wrong issue tracker for it.
