### ISSUE TITLE
Doctrine does not generate default value for postgres boolean

### ISSUE THREAD

**Issue by idchlife** [doctrine/migrations#490]
I have this in annotations

        /**
        * @ORM\Column(type="boolean", options={"default" = false})
        *
        * @var bool
        */
        private $wipesOtherChoices = false;

And this is what I have in database (migrations file contains empty migrations, without sql)

![image](https://cloud.githubusercontent.com/assets/4563032/18642986/b42ace90-7eab-11e6-8051-e285c8d4f212.png)

**Comment by stof** [comment]
should be reported to the DBAL project, as it is the one generating the SQL. doctrine/migrations just uses whatever SQL queries are generated by DBAL
