### ISSUE TITLE
The commands try to create the migrations table event if it exists

### ISSUE THREAD

**Issue by mishal** [doctrine/migrations#491]
While I execute the command:

```
$ ./doctrine-migrations status
```

The exception is thrown:

```
 [Doctrine\DBAL\Exception\TableExistsException]
  An exception occurred while executing 'CREATE TABLE _migration (version VARCHAR(255) NOT NULL, PRIMARY KEY(version))':
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "_migration" already exists

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "_migration" already exists

  [PDOException]
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "_migration" already exists
```

The problem is because the migrations db table existence is not detected when its name is ignored by DBAL's filterSchemaAssetsExpression.

The existence of the table is checked by SchemaManager's method tablesExist() resp. listTableNames() which honors the regular expression for assets filtering.

The solution is to reset the regular expression before the existence check.

**Comment by mikeSimonson** [comment]
@mishal Why are you ignoring the migration table in the first place ?

**Comment by mishal** [comment]
We simply prefix all "system" tables with underscore

**Comment by mishal** [comment]
See http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables

**Comment by mikeSimonson** [comment]
@mishal I know that documentation.

But in that case the solution is to create another connection that doesn't ignore the _migration table and pass that connection for the doctrine migrations.

**Comment by mishal** [comment]
We don't use Symfony and this is not a transparent solution for us...

The doctrine commands /orm, dbal, migrations, data fixtures/ share the same connection which is configured in `cli-config.php`...

**Comment by mikeSimonson** [comment]
I am sorry but this isn't an issue with doctrine migration. This is an issue with your setup.
