### ISSUE TITLE
Using traits

### ISSUE THREAD

**Issue by nicolaskern** [doctrine/migrations#493]
Hi,

When using traits (useful when my entity already extends a class, and when I have fields in common with other entities), they are not taken in account when generating migrations.
Is it a problem, is it normal, do I need to write some annotations?

Best,
Nicolas

**Comment by stof** [comment]
Doctrine migrations will use the SQL generated for the schema provided by the ORM metadata tool. If these fields are not taken into account, you should ask this to the ORM team.

and you indeed have to specify the mapping for these fields, like for any other field.

**Comment by nicolaskern** [comment]
Yes, I write my mapping as I would do for any other field, but I just discovered I need to clean my cache for Doctrine to know the new mapping.
So indeed I think this might be an ORM metadata problem...

**Comment by mikeSimonson** [comment]
Closing as it isn't a migration issue.
