### ISSUE TITLE
Problem with diff and column with custom collation

### ISSUE THREAD

**Issue by MassiveHiggsField** [doctrine/migrations#495]
Used versions:

- doctrine/orm v2.5.4 
- doctrine/migrations 1.4.1 

Entity:

    use Doctrine\ORM\Mapping as ORM;
    /**
     * @ORM\Table(name="Contest")
     * @ORM\Entity
     */
    class Contest
    {
        /**
         * @var string
         *
         * @ORM\Column(name="id", type="string", length=32, nullable=false, options={"collation":"utf8_unicode_ci"})
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="IDENTITY")
         */
        private $id;
    }

Current table:

    CREATE TABLE `Contest` (
      `id` int(11) NOT NULL AUTO_INCREMENT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci 

Migration generated from diff:

    class Version20161014011453 extends AbstractMigration
    {
        /**
         * @param Schema $schema
         */
        public function up(Schema $schema)
        {
            // this up() migration is auto-generated, please modify it to your needs
            $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
            $this->addSql('ALTER TABLE Contest CHANGE id id VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci');
        }
    
        /**
         * @param Schema $schema
         */
        public function down(Schema $schema)
        {
            // this down() migration is auto-generated, please modify it to your needs
            $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
            $this->addSql('ALTER TABLE Contest CHANGE id id VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci');
        }
    }

So up() and down() do the same thing and if i execute this migration and rerun diff, it will generate the same migration again. 

Any help appreciated.

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.
