### ISSUE TITLE
Executing migrations with auto commit off

### ISSUE THREAD

**Issue by heneke** [doctrine/migrations#496]
If auto commit is disabled for the underlying dbal connection, migrations are never committed because the connection is already in nesting level 1. Each transactional migration starts a new transaction running in nesting level 2 (committed at the end, returning to level 1), but there is no commit for level 1 after all migrations are executed.

**Comment by mikeSimonson** [comment]
If the user pass a connection where the auto-commit has been set to off it's his responsibility to commit or not the transactions after the migration.

**Comment by heneke** [comment]
If the command line tools are framework configured with auto-commit off, migrations are essentially useless (because there is no way to commit the outer transaction).

**Comment by mikeSimonson** [comment]
@chrisguitarguy is working on a PR that would fix that
