### ISSUE TITLE
migrations:diff thorws DBALException::noColumnsSpecifiedForTable when using multiple schema

### ISSUE THREAD

**Issue by andrzejdziekonski** [doctrine/migrations#498]
I am working with MSSQL database and i want some entity tables to be in different db schema (to manage db permissions in MSSQL). There was no problem with creating the tables (using 'schema' argument in Orm\Table) and migration worked as intended: all tables were created in the pointed db schemas. However, when i try to add some changes to my entities and i use diff command there is: 
```
  [Doctrine\DBAL\DBALException]             
  No columns specified for table MyTableName
```
Any idea how could i manage this?

**Comment by mikeSimonson** [comment]
@andrzejdziekonski If you manage to make a failing test case then maybe I can help you but I don't know what triggered the exception.
