### ISSUE TITLE
Configurating proxy target directory?

### ISSUE THREAD

**Issue by uestla** [doctrine/migrations#511]
Is it possible to set proxy target dir? Now it seems impossible when running migration command.

Here's the flow:

1. [MigrateCommand](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php#L139) calls `$migration->migrate( ... )`
2. this calls [$configuration->getMigrationsToExecute( ... )](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Migration.php#L149)
3. that [loads migration versions](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L776)
4. which then [creates `Version` objects](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L416) with no 4th argument specified
5. that means that [default proxy configuration](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L120) is then instantiated
6. which uses [LazyLoadingValueHolderFactory](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Provider/LazySchemaDiffProvider.php#L46) as a `proxyFactory`
7. back to `Version` object - in its `execute()` method, it tries to [createFromSchema()](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L277) using the already mentioned [LazySchemaDiffProvider::createToSchema()](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Provider/LazySchemaDiffProvider.php#L58)
8. this calls @Ocramius ' [LazyLoadingValueHolderFactory::createProxy()](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php#L40)
9. that cascades to [AbstractBaseFactory::generateProxy()](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Factory/AbstractBaseFactory.php#L71)
10. this follows with [`generateProxyClass`](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Factory/AbstractBaseFactory.php#L88) -> [`$configuration->getProxyAutoloader`](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Factory/AbstractBaseFactory.php#L129)
11. as I've shown in step 5., default configuration is used and therefore [Autoloader](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Configuration.php#L95) object is the proxy autoloader here
12. it also directly instantiates [`FileLocator`](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Configuration.php#L96) and passes `$proxiesTargetDir` to its constructor
13. the value is taken from default configuration, hence it returns [sys_get_temp_dir()](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/Configuration.php#L118)

And in that last `sys_get_temp_dir()` lies the root of my problem...

`open_basedir` is set on my hosting environment, thus this causes in [`realpath()`](https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/FileLocator/FileLocator.php#L45) call:

```
Warning: realpath() [function.realpath]: open_basedir restriction in effect.
```

Which is logical, since system temp dir is not part of `open_basedir` path...

Has anyone ever dealt with this? Is there some easy way to simply just set the proxy target dir?

**Comment by Ocramius** [comment]
> Has anyone ever dealt with this? Is there some easy way to simply just set the proxy target dir?

Yep, generally I'd say that `sys_get_temp_dir()` should just give you a writable path. If that isn't working, then *A LOOOOOT* of stuff may break. Therefore, the first thing to fix is that.

If you cannot do that, then you can set the config before creating the [`LazySchemaDiffProvider`](https://github.com/doctrine/migrations/blob/e46858e487cba3df09ed3305612b0179da2fe8cf/lib/Doctrine/DBAL/Migrations/Provider/LazySchemaDiffProvider.php#L42-L49).

**Comment by mikeSimonson** [comment]
The fourth parameter (optional) of the the Version class is the [schemaDiffProvider](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L105).

If you want to pass your own, you have to create your version of the [Configuration class](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L105) and override the behaviour of the register migration method so that it pass your DiffProvider.

Then depending on your framework or app env you need to look at how to set that configuration class.
