### ISSUE TITLE
Change to migration sorting in 1.5.0 breaks some existing projects

### ISSUE THREAD

**Issue by trappar** [doctrine/migrations#516]
This commit: https://github.com/doctrine/migrations/commit/dbb7dcd4b76bc3a6e77f3ba2a8dccbc0fce0bd60

Fixing this issue: https://github.com/doctrine/migrations/issues/457

Caused the an irreversible corruption of the *production* database at the company I work at. Luckily we had a backup and were able to manually recover the majority of our lost data.

I'm still not entirely sure I understand what happened but as of 1.5.0 during our normal deployment, which includes running `console doctrine:migrations:migrate -n` (DoctrineMigrationsBundle), this library somehow decided to revert virtually every migration we've ever run.

Here's what our migrations directory looked like, I'm sure you can spot the sorting issue...

<img width="220" alt="screen shot 2017-03-14 at 4 32 28 pm" src="https://cloud.githubusercontent.com/assets/525726/23926859/dbfd2cb2-08d3-11e7-9245-11f54f769723.png">

As of 1.5.0 "Version9" became the latest migration. I just don't understand how exactly that resulted in reverting all other migrations.

Now I won't pretend this wasn't mainly my fault. I should have tested running migrations after updating the dependency and before deploying. We probably shouldn't have ever had these non-standard named migrations. I just saw that it was a minor version update and didn't really think twice about it. Not holding it against you guys, but you probably need to add a update guide for 1.4.1 -> 1.5.0 to indicate that this may be an issue. Really.. 1.5.0 should probably be version 2.0.0 because of this. It's a pretty massive BC break, and there's no way to determine who it might affect.

I'm also a bit confused as to why the migrations table in the database doesn't track if a migration has run or not, or doesn't use that information to determine which migrations need to run. That "Version9" migration had definitely already been run and was in the migration_versions table.

**Comment by chrisguitarguy** [comment]
Doesn't really seem like this is something that's going to be fixed, so what's the path forward here? Documentation? Upgrade guide? Configuration option to enable legacy sorting?

Happy to do the work here, but just need some direction.

**Comment by alcaeus** [comment]
This is not good - sorry this corrupted your database @trappar.

> I just don't understand how exactly that resulted in reverting all other migrations.

I'm not entirely sure either, I'd have to investigate what's going on. As for the version naming, I assume you used to have `Version1`, `Version2` and so on before switching to the `VersionYYYYMMDD...` scheme?

@chrisguitarguy yeah, not sure if we can or should fix this using code, especially given that this 10-month old issue is the only report of problems we got so far. I believe we should add it do the documentation and suggest how to prevent it.

**Comment by chrisguitarguy** [comment]
Too a pass a documenting this [here](https://github.com/doctrine/migrations-documentation/pull/24).
