### ISSUE TITLE
Migrate process with already existing version table

### ISSUE THREAD

**Issue by Mortagus** [doctrine/migrations#517]
Hello everyone,

I'm confronting a problematic situation : 
- I'm building my development environment from scratch.
- my database is rebuild with structure and data. 
- the database contains the "migration_version" table with 6 version numbers of already executed migrations.

Here is the problem: when I call the `doctrine:migrations:status` command, the current version is `0` instead of the last number within the table.

Why is there no synchronisation between the command and the rows present into the table ?
How can I synchronise doctrine with the database content ?

**Comment by chrisguitarguy** [comment]
Can we see your migrations configuration? (`migrations.yml` or whatever format used).

**Comment by Mortagus** [comment]
I'm sorry, I completely forget to close this issue.

The problem was the database connection: the script was connected to an empty database, so the table `migration_version` was there but empty so the migration script was not the problem ;-).

Sorry again, I found that solution a week ago.
