### ISSUE TITLE
Dry run creates migration_versions table

### ISSUE THREAD

**Issue by tehplague** [doctrine/migrations#521]
Currently the `--dry-run` parameter does not prevent Doctrine Migrations from creating the migration_versions table. This is especially awful when combining `--dry-run` with `--write-sql` to test the initial setup.

This is because the `\Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand` first loads the list of already executed migrations before it checks if a dry run should be performed.

I'd opt for altering the order of the two tasks.

**Comment by stof** [comment]
well, a dry-run needs to check the list of executed migrations too, as having migrations which are already executed affects the output of the dry-run.

**Comment by tehplague** [comment]
Agreed, but then the check should assume the list to be empty if migration_version is absent instead of silently creating that table. That means, the process of checking and creating migration_versions should be separated (currently both operations happen unconditionally inside the same function).

**Comment by mikeSimonson** [comment]
@tehplague PR is welcome to improve that.

**Comment by chrisguitarguy** [comment]
This was done in #588, maybe it can be closed? Or is it waiting on an official release?

**Comment by alcaeus** [comment]
Looks like it hasn’t been released yet. @mikeSimonson what’s the status in a release, shall we do one?
