### ISSUE TITLE
Multiple Entity Managers Prefix Creation Inconsistent

### ISSUE THREAD

**Issue by smcjones** [doctrine/migrations#522]
Is it possible to have an improvement so that either by default, or when some option (or even just --em) is passed, generated SQL has a prefix?

For legacy apps and multi-tenant designs, it is very time consuming to manually add a prefix to certain schemas. If there is a way to ensure this happens already, please accept my apologies and point me in the right direction.

I notice that on table creation and table drop, generally the schema is already added. However, when an index is added/removed, the schema is not prefixed. 

I am using a MySQL database.

**Comment by chrisguitarguy** [comment]
[This might help](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/sql-table-prefixes.html).

You can implement an event listener to add the prefix and then tell each individual entity manager about the listener. Seems like something better left out of the migrations library itself.

**Comment by smcjones** [comment]
Thanks. Took me a while to track down the right listener, and this is a bit hack-ish, but managed with this:

    public function onSchemaAlterTable(SchemaAlterTableEventArgs $eventArgs)
    {
        $tablediff = $eventArgs->getTableDiff();
        $tablediff->fromTable = new Table(
            $this->prefix . '.' . $tablediff->name,
            $tablediff->fromTable->getColumns(),
            $tablediff->fromTable->getIndexes(),
            $tablediff->fromTable->getForeignKeys(),
            0,
            $tablediff->fromTable->getOptions()
        );
       $ref = new \ReflectionClass($eventArgs);
    }
