### ISSUE TITLE
Diff throws exception when meeting an unexpected Primary Key

### ISSUE THREAD

**Issue by trickeyone** [doctrine/migrations#526]
We have a legacy data structure that used Active Directory. We've been making the slow trudge to a proper relational schema. As of 1.5.0, we were previously at 1.1.0 and recently upgraded, when we run `migrate:diff` and a table has an unexpected primary key (i.e. a ManyToMany that has a `id` field instead of the join columns as the Primary Key) we get an exception along the lines of `SchemaException("There is no column with name "id" on table...")`. After researching, I see that this is tied to doctrine/dbal#2501 issue and seems to be fairly far spread.

I'm betting there isn't much that can be done here since the SchemaTool is used to generate the SQL statements, but thought it should be tracked, if nothing else.

**Comment by chrisguitarguy** [comment]
Looks like https://github.com/doctrine/dbal/issues/2501 is fixed, and this one can probably be closed as well.

**Comment by mikeSimonson** [comment]
As the underlying issue in dbal has been fixed, I am closing this again.
Feel free to open again if the problem persist.
