### ISSUE TITLE
--db-configuration was ignored when framework has another config

### ISSUE THREAD

**Issue by KnechtRootRecht232** [doctrine/migrations#540]
i wan't to overwrite my doctrine-config from ZF2, which is in doctrine.local.php.
but my db-config file is ignored when in cli the parameter --db-configuration is passed.

parsing of my custom db-file works, even when i simulate an notice or error this works, but the connection-settings where ignored:

config/doctrine-cli.php
```
return array[
'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
    'host' => 'localhost',
    'port' => 3306,
    'user' => '****',
    'password' => '****',
    'charset' => 'utf8',
    'dbname' => 'db_local',
    'driverOptions' => [
        1002 => 'SET NAMES utf8'
    ]
]
```
```
php vendor/doctrine-module migrations:migrate --db-configuration=config/doctrine-cli.php
Loading configuration from the integration code of your framework (setter).
                                                                    
                    Doctrine Database Migrations                    
                                                                    

```

**Comment by mikeSimonson** [comment]
Debug interactively and watch if the [code is looking in the right folder.](https://github.com/doctrine/migrations/blob/17f61e9181af4c13457471e16465548034cd8f55/lib/Doctrine/DBAL/Migrations/Configuration/Connection/Loader/ArrayConnectionConfigurationLoader.php#L47)

What version are you using ?

**Comment by KnechtRootRecht232** [comment]
> Debug interactively and watch if the code is looking in the right folder.

i have debuged it interactively and the file exists, forced parse-errors or debug-output was successfull.

**Comment by KnechtRootRecht232** [comment]
in a previus release i see in the code a fix for that, but this isn't present any more:
```
if(db-configruation)
....
else {
do the normal check if the config from framework is set.
}
```

**Comment by jwage** [comment]
@KnechtRootRecht232 Is this still an issue?

**Comment by KnechtRootRecht232** [comment]
@jwage i don't know,  i have used it not longer with a seperated cli-config file.
