### ISSUE TITLE
Tag latest PHP 7.0 compatible release

### ISSUE THREAD

**Issue by Jontsa** [doctrine/migrations#543]
Current dev-master requires PHP 7.1. This interferes with composer update when using PHP 7.0 and if you want to use more recent version than 1.5.0 from 2016. Changing requirement to         `"doctrine/migrations": "dev-master#b82d683019fea695119b1972b07be77378186aff"`gives error:

```
  Problem 1
    - doctrine/migrations dev-master requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/migrations dev-master requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/migrations dev-master#b82d683019fea695119b1972b07be77378186aff -> satisfiable by doctrine/migrations[dev-master].
```

Can you tag the latest release that is PHP 7.0 compatible so those of us still not blessed with 7.1 can lock that version in composer.json :)

**Comment by florentchaboud** [comment]
+1

**Comment by stof** [comment]
The `#b82d683019fea695119b1972b07be77378186aff` locking in composer is an installer-level hack. This will not work properly to get metadata. You should just never use it.

**Comment by florentchaboud** [comment]
Well I used the v1.4.0 tag to solve the problem. It's not the latest version but it does the job !

**Comment by stof** [comment]
btw, requiring `dev-master` is a bad idea anyway. You should always prefer stable releases

**Comment by florentchaboud** [comment]
You're right, and actually v1.5.0 is also compatible with php 7.0.

**Comment by Majkl578** [comment]
If you're interested in using dev versions (you've been warned), use `^1.5@dev` constraint -- this should pick 1.6.x-dev alias for dev-master. Also composer wouldn't install 7.1-only version if you have only 7.0.

**Comment by Jontsa** [comment]
> btw, requiring dev-master is a bad idea anyway. You should always prefer stable releases

Of course but I would have preferred a more recent version than one from last year. Minor releases every now and then would be nice ;)

> If you're interested in using dev versions (you've been warned), use ^1.5@dev constraint

This fixed my issue. :+1: I will bumb to next stable release when it arrives. Thanks to everyone.

**Comment by Jontsa** [comment]
Spoke too soon. "^1.5@dev" constraint does not download commit more recent than c81147c. So I guess I'm stuck with that.
