### ISSUE TITLE
doctrine schema diff generates continues diff with json fields in 1.7

### ISSUE THREAD

**Issue by BunnyHolder** [doctrine/migrations#546]
doctrine schema diff generates continues diff with json fields in 1.7

**Comment by mikeSimonson** [comment]
Hi @BunnyHolder,

Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.

**Comment by lcobucci** [comment]
Just for reference, it might be related to https://github.com/doctrine/dbal/pull/2855
