### ISSUE TITLE
Rename Foreign Key 

### ISSUE THREAD

**Issue by lecneri** [doctrine/migrations#548]
Hi, 

I got this table which I noticed that I made a typo mistake and I'm trying to fix it through migration, so here what I've done:

1. Drop old foreign key

2. Drop old index

3. Add new index 

4. Add new foreign key as follow

```
$t = $schema->getTable("table");
$t->addForeignKeyConstraint("other_table",
         array("other_table_id"), array("id"),
         array(), "my_index_name"
      );
```
Everything is fine until step 4. It just doesn't create the foreign key with the given name, it just gets the same old key name with the typo error.
Is this supposed to happen?

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.
