### ISSUE TITLE
alter column that is a foreign key

### ISSUE THREAD

**Issue by lecneri** [doctrine/migrations#550]
I got this error when trying to change a column in mysql that is a foreign key

> 
> [Doctrine\DBAL\Exception\DriverException]
>   An exception occurred while executing 'ALTER TABLE cliente ADD apagado_em D
>   ATETIME DEFAULT NULL, CHANGE id_segmento id_segmento INT UNSIGNED NOT NULL'
>   :
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'id_segmento': us
>   ed in a foreign key constraint 'fk_cliente_has_segmento'
> 

since the FK is the problem before I've changed the script to alter the table and drop the index and FK, then alter the column and finally recreate index and FK. 

But the migrations ignores the index drop and recreation, thus I keep with the problem of not being able to alter the column.

**Comment by mikeSimonson** [comment]
How are you removing those indexes and foreign keys ?

**Comment by lecneri** [comment]
Hi @mikeSimonson,

It's been a while and I solved my issue by creating a separated migration, one to drop index and FK and other to make changes to the column. But answering your question, I dropped the index and FK this way:

`php
$t = $schema->getTable("cliente");
$t->dropIndex("fk_cliente_has_segmento");
$t->removeForeignKey("fk_cliente_has_segmento");
`

**Comment by mikeSimonson** [comment]
Where you also using $this->addSql in the same migration ?

**Comment by lecneri** [comment]
No, I avoid using it because usually it tends to turn migrations platform dependent.

**Comment by mikeSimonson** [comment]
Then I am not sure what happened.

Thanks for the bug report anyway
