### ISSUE TITLE
Generate migrations always delete index

### ISSUE THREAD

**Issue by cduran433** [doctrine/migrations#552]
Hello,

I have defined in my entity this annotations:

>   @ORM\Table(name="article_ar", indexes={
>       @ORM\Index(name="idx_position", columns={"position"}),
>       @ORM\Index(name="idx_home_position", columns={"home_position"}),
>       @ORM\Index(name="select_index", columns={"publication_date", "enabled"}),
>       @ORM\Index(name="idx_list_cms", columns={"author_id", "home_position"})
>    })
>   @ORM\Entity (repositoryClass="Application\By433\NewsBundle\Entity\ArticleArabicRepository")
>   @UniqueEntity("slug")

Index are created in database except idx_list_cms, but when I executed diff to generate the new file. The migration file is deleting all index that are already created.

        $this->addSql('DROP INDEX idx_position ON article_ar');
        $this->addSql('DROP INDEX select_index ON article_ar');
        $this->addSql('DROP INDEX idx_home_position ON article_ar');

Someone knows what is happening?

**Comment by stof** [comment]
Please report this to the DBAL project. Generating the queries for the schema changes is implemented by DBAL, not by the migration project.

The issue may be a bug either in the DBAL layer or in the ORM layer.

**Comment by cduran433** [comment]
Ok, Thank you!
