### ISSUE TITLE
Providing a value to the --write-sql for a migrate command leads to an error

### ISSUE THREAD

**Issue by rawroland** [doctrine/migrations#554]
## Expected Behavior
Running the *migrations:migrate* command with the option *--write-sql* and a path outputs the generated file in the path:
`bin/console migrations:migrate --write-sql=sql_migrations`
File is created in the folder `sql_migrations`

## Current Behavior
Running the *migrations:migrate* command with the option *--write-sql* and a path produces the error: *The "--write-sql" option does not accept a value.* 

## Possible Solution
A possible fix could be setting the `InputOption` to `VALUE_OPTIONAL` in _MigrateCommand.php_. I would be ready to create a pull request with this fix if it is correct.

**Comment by mikeSimonson** [comment]
@rawroland Thanks for the bug report. A fix would be welcome. Can you also look if that feature is tested ? Because if it is, it means that the test is broken. If it's not, can you try adding one ?

Thanks

**Comment by mikeSimonson** [comment]
#562
