### ISSUE TITLE
Wrong down migration for PostgreSQL

### ISSUE THREAD

**Issue by enumag** [doctrine/migrations#556]
Normally (on MySQL) if there is no changes in the mapping the diff command simply doesn't do anything and writes `No changes detected in your mapping information.`

For PostgreSQL this does not work correctly. Even if there are no mapping changes the diff command still generates a migration like this:

```php
<?php

namespace App\Doctrine\Version;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20171004073510 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
    }
}
```

The `$this->addSql('CREATE SCHEMA public');` is there always regardless of whether there are mapping changes or not. And of course it causes all down migrations to be non-functional because the schema already exists so I have to manually delete it from all migrations.

How can I fix this? I don't mind sending a pull request, I'm just not sure how is this supposed to work.

**Comment by stof** [comment]
This is an issue in DBAL itself: https://github.com/doctrine/dbal/issues/1188
So I'm closing this issue here.

Btw, to avoid forgetting to remove this broken query, I added a test in my project to make the CI red if you don't remove it:

```php
namespace Incenteev\Tests;

class MigrationsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider provideMigrationFiles
     */
    public function testNoSchemaCreation($migrationFile)
    {
        $this->assertNotContains('CREATE SCHEMA', file_get_contents($migrationFile), 'The migration must not create a schema', true);
    }

    public static function provideMigrationFiles()
    {
        foreach (glob(__DIR__.'/../../app/DoctrineMigrations/*') as $file) {
            yield basename($file) => array($file);
        }
    }
}
```

**Comment by enumag** [comment]
@stof Thanks I'll follow that issue then.
