### ISSUE TITLE
Passing "prev" or "next" to migrate command not working

### ISSUE THREAD

**Issue by trickeyone** [doctrine/migrations#557]
When executing `migrations:migrate` and passing a version parameter of "next" isn't working as expected. If there are migrations that have been executed out of chronological order, the "next" available version is not executed and the "Already at latest version." message is displayed.

i.e.
Migration Versions:
Version1
Version2
Version3
Version4
Version5

* Previous feature releases have Version1 and Version2.
* Subsequent release has Version4 and Version5.
* The release with Version3 isn't released until after Version5.
When executing `migrations:migrate next`, Version3 will not be executed and the "Already at latest version." message will be displayed.
However, executing `migrations:migrate` will execute the Version3 migration.

This is a disconnect in functionality. Executing with the "next" parameter should execute whichever version is next available, not just after the last-executed version's number. Having migrations out of chronological order was supported in previous versions and it doesn't make sense to disallow executing the migrations singularly with the "next" parameter.

**Comment by mikeSimonson** [comment]
Well this is maybe more an issue of documentation.

Running migrate next is supposed to only run one migration, the next in order (that's why there is prev too). And in your case there isn't any. Does it work if you run latest ?
Using migration will make sure that all the available migrations have been run. Up to the end if you don't specify a target or up to target that you specified.

**Comment by jwage** [comment]
Currently as it is coded today, the `next` behavior just grabs the next migration, even if it is one that has been migrated. It seems like this functionality should get the next unexecuted migration?

**Comment by goetas** [comment]
v3.x addresses this. 

`next} is the next not executed migration, and `prev` is the last executed migration.
Refs at https://github.com/doctrine/migrations/blob/f92df454c8a424e0517c4f5658c21ed73020f7ae/lib/Doctrine/Migrations/Version/DefaultAliasResolver.php#L85 and https://github.com/doctrine/migrations/blob/f92df454c8a424e0517c4f5658c21ed73020f7ae/lib/Doctrine/Migrations/Version/DefaultAliasResolver.php#L79
