### ISSUE TITLE
Column order doesn't match order of properties in the entity class in "diff" command

### ISSUE THREAD

**Issue by aik099** [doctrine/migrations#558]
I have an entity, where each property has `@ORM\Column(...)` annotation. When `diff` command is executed the first time, then columns in created table are ordered exactly as properties in the entity class.

When I add property between 2 other properties, then next `diff` run is adding column at the end of the table and not according to property position in the entity class.

Is this (not to preserve order of columns in table) expected behavior or a bug?

P.S.
I know that placing columns in specific position in the table is likely to work for MySQL only.

**Comment by aik099** [comment]
Even in `CREATE TABLE` statement entity class properties with `@ORM\ManyToOne` annotation (or any relation annotation) instead of `@ORM\Column` annotation are added at the end of the table.

**Comment by mikeSimonson** [comment]
As far as I know, it was never a goal to keep the order the same. Also this issue is related to the schema diff generation which is done by the dbal not by doctrine migrations.

**Comment by aik099** [comment]
> As far as I know, it was never a goal to keep the order the same.
From the point of view of the ORM the class is still the same if the properties order change.

Makes sense, thank you.
