### ISSUE TITLE
$table->renameColumn() drops the column

### ISSUE THREAD

**Issue by dinamic** [doctrine/migrations#57]
In one of my migration scripts I needed to rename the column and tried to use the renameColumn() method.

Unfortunately, this did not worked - it only dropped it.

Looking at the code of the method, there's definitely something missing:

```
    /**
     * Rename Column
     *
     * @param string $oldColumnName
     * @param string $newColumnName
     * @return Table
     */
    public function renameColumn($oldColumnName, $newColumnName)
    {
        $column = $this->getColumn($oldColumnName);
        $this->dropColumn($oldColumnName);

        $column->_setName($newColumnName);
        return $this;
    }
```

**Comment by ScreamingDev** [comment]
Trololo. Removed for almost 3 years now. How about a `::getColumn('foo')->rename('bar')` or at least some hint in the error message how to cover this now, @dinamic ?

**Comment by Tofandel** [comment]
Still no way to rename a column, we can only drop and recreate using `Schema`

Looking at how `ColumnDiff` is generated in the comparator, the diff can in fact detect if a column is renamed
https://github.com/doctrine/dbal/blob/3.6.x/src/Schema/Comparator.php#L366

But then using `Schema->getTable` there is no way to mark a column to be renamed
