### ISSUE TITLE
Move yaml from require to dev-require

### ISSUE THREAD

**Issue by prisis** [doctrine/migrations#573]
Are you okay if i make a pr to change the yaml requirement to a optional on?

Not everyone use yaml for configuration.

**Comment by mikeSimonson** [comment]
I am not to sure how to deal with that kind of optional dependency. I will look at what the options are.

**Comment by prisis** [comment]
Only some if checks missing, a composer suggestion and a doc info about how to add yaml back; is a simple composer req.

**Comment by chrisguitarguy** [comment]
Probably throwing a nice exception indicating that `symfony/yaml` has to be installed in `YamlConfiguration` too. Here's an [example in symfony](https://github.com/symfony/symfony/blob/e04b4f4a1b6830e3bad7b484db81915efed14813/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L601-L603).
