### ISSUE TITLE
Phar archive for 1.6.x releases

### ISSUE THREAD

**Issue by Gemorroj** [doctrine/migrations#574]
Need create `phar` archive for 1.6.x releases.
Latest `phar` archive is 1.5.0 version.

**Comment by alcaeus** [comment]
I forgot to generate those when releasing the last two releases. I'll see to add them to the releases later today.

**Comment by alcaeus** [comment]
Looks like it will take longer than expected. Both my machines error out when running the `build-phar.sh` script:
```
PHP Fatal error:  Uncaught ErrorException: proc_open(): unable to create pipe Too many open files in phar:///Users/alcaeus/Code/doctrine/migrations/box.phar/src/vendors/symfony/console/Application.php:978
```

I'd say if you need the phar quickly, your best bet is to clone the branch and generate it yourself for now.

@mikeSimonson could you help out with the phar generation? Not sure why it fails for me.

**Comment by Gemorroj** [comment]
@alcaeus Yes, I've done the phar archive on your own. There were no problems.
php 7.1.11, windows 7 x64

**Comment by Gemorroj** [comment]
@alcaeus https://github.com/box-project/box2/issues/126
i think neep upgrade box2 version

**Comment by alcaeus** [comment]
Thanks for the pointers, I’ll give it a shot.

**Comment by alcaeus** [comment]
Same issue as before, just later in the build process. I'll see if I can find a different build system that works.

**Comment by mikeSimonson** [comment]
@Gemorroj Done

@alcaeus This looks like a very random windows issue

**Comment by alcaeus** [comment]
Thanks @mikeSimonson! In this case, don't blame Windows - it's MacOS ;)
