### ISSUE TITLE
Database backup before new migrations

### ISSUE THREAD

**Issue by wuethrich44** [doctrine/migrations#576]
I always feel a little bit uneasy when I run a migration on my prod server so most of the time I take a database backup before I execute new migrations.

Currently I'm solving this with a custom script and `mysqldump` but I could provide a PR which would add a new command line option for the backup.

```
bin/console doctrine:migrations:migrate --backup-path=/var/backups/database
```

Is this out of scope or what do you think about this feature?

**Comment by lcobucci** [comment]
@wuethrich44 IMO this is out of the scope of this library, but let's see what @mikeSimonson thinks about it.

**Comment by alcaeus** [comment]
I tend to agree. A regular backup should be part of your SLA and deployment strategy, regardless of migrations. Depending on the need it would make sense to add hook points so you can trigger a backup and have migrations wait for it, but I wouldn't want to add that complexity here.

**Comment by mikeSimonson** [comment]
I vote out of scope too. You can create your own migrations tool that pass the responsibility of the migration to doctrine migrations and does a backup just before to call it.
