### ISSUE TITLE
Critical Data Insert / Update Method

### ISSUE THREAD

**Issue by henryhayes** [doctrine/migrations#591]
This is not a bug as such. We need a way to inject initial data.

`Doctrine\DBAL\Migrations\AbstractMigration\AbstractMigration::postUp` is not suitable as it is called after the SQL preparation. See line 294 and 297. This means that if `$this->addSql()` is called after `$this->executeRegisteredSql()`, the query is never prepared or executed.

So I propose a method in the `Doctrine\DBAL\Migrations\AbstractMigration` class which is responsible for INSERTing or UPDAT(E)ing critical data immediately after the changes / updates are made to the database.

Any suggestions welcome before I start on a potential solution.

**Comment by mikeSimonson** [comment]
The solution I use for now, is to always separate in different migrations the schema change and the data import/update.
