### ISSUE TITLE
Possibility to make the whole migrate command transactional

### ISSUE THREAD

**Issue by stof** [doctrine/migrations#594]
Currently, each migration gets wrapped in a transaction, ensuring that we don't execute half of the migration in case of failure (for platforms supporting to put DDL statements in a transaction, which is the case of PostgreSQL but was not the case of MySQL last time I used it).
However, if you have multiple unexecuted migrations, it could be useful to ask the `migrations:migrate` command to wrap the whole execution in a transaction, so that the whole execution of the command is atomic. My use case is to be able to have a all-or-nothing migration during a deployment process, even in case multiple features shipping a DB migrations are deployed in the same deployment rather than multiple ones.

What do you think about this feature ?

**Comment by PowerKiKi** [comment]
[Atomic DDL](https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html) just landed in the brand new  MySQL 8. Unfortunately it seems it is [not supported in MariaDB](https://mariadb.com/kb/en/library/start-transaction/#ddl-statements) yet. But that would still be awesome to support it in this project.

**Comment by stof** [comment]
Atomic DDL still does not allow to perform DDL statements in a transaction involving other SQL statements (which is almost always required as soon as your migrations apply on a non-empty database)

**Comment by lcobucci** [comment]
@stof I think that it's useful and it could be set in the configuration file for the project, so the user can specify the granularity level of the transaction.

**Comment by jwage** [comment]
@stof Do you think it is best to make this an option on the `migrate` command or a configuration option? Or both?

**Comment by Majkl578** [comment]
Info about support by other vendors: https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis

**Comment by stof** [comment]
@jwage I would like to be able to provide this in the configuration, to avoid having to tell each of our devs to use it in the CLI. but I'm fine if it available in both places.

**Comment by stof** [comment]
Note that DBAL already has a platform API to know whether the platform supports transactional DDL. And doctrine/migrations already uses this API to wrap each migration in a transaction when supported.
This feature request is about being able to switch between `transaction per migration` to `single transaction per run` (and it would stay on `no transaction` when unsupported, like today)

**Comment by PowerKiKi** [comment]
I would rather have no configuration at all and always use the highest level of atomicity as possible. This would be consistent with existing behavior, less things to implement, and you would still be able to execute a single migration with the `migrations:execute`command should you need to have a partially migrated db.
