### ISSUE TITLE
Scrutinizer reports wrong coding standard patches

### ISSUE THREAD

**Issue by stof** [doctrine/migrations#596]
Scrutinizer is not configured for the Doctrine coding standards, and so removes spaces around `!` in its suggested patches.
The scrutinizer config should be updated with the right CS, or the CS checks should be disabled. Checking with the wrong config is worse than not checking.

**Comment by Majkl578** [comment]
I'll try to fix it as part of #590, should be easy to set external CS ruleset: https://scrutinizer-ci.com/docs/tools/php/code-sniffer/

**Comment by Majkl578** [comment]
This should now be fixed (disabled) in master.
