### ISSUE TITLE
Diff is not working if options are set directly in Type::getSQLDeclaration()

### ISSUE THREAD

**Issue by mvorisek** [doctrine/migrations#601]
I created a custom BooleanType with the following method:
```
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform) {
        return $platform->getBooleanTypeDeclarationSQL($fieldDeclaration) . ' UNSIGNED';
    }
```

The issue is that the diff keeps altering the table as it thinks no unsigned type option should be presented.

I think there are two solutions:
a) Parse the options from Type::getSQLDeclaration() method as from the standard table definition
b) The type will implement method like "makeDefaultColumnOptions" which can every custom type override and add all options this way

**Comment by mikeSimonson** [comment]
What is an unsigned boolean ?

**Comment by mvorisek** [comment]
MySQL has no boolean data type. It has only TINYINT data type. So I wanted to restrict this data type to UNSIGNED one to prevent at least negative values.

**Comment by stof** [comment]
this is related to DBAL IMO, as it is the project implementing the Schema diffing.

and yes, creating custom type definitions might confuse the differ.

**Comment by mvorisek** [comment]
Issue moved to Doctrine/dbal https://github.com/doctrine/dbal/issues/3021
