### ISSUE TITLE
Default values on foreign key columns

### ISSUE THREAD

**Issue by hcomnetworkers** [doctrine/migrations#602]
When changing an id field of one of our tables to use a default 0 (to set the id via trigger), we've noticed that a foreign key column receives the same default value as the referenced column in a diff. 

Intended change: `ALTER TABLE table_a CHANGE id id INT DEFAULT 0;`
Not intended change: `ALTER TABLE table_b CHANGE a_id a_id INT DEFAULT 0;`

This breaks the "nullability" of these foreign keys because they can no longer be inserted with NULL. Foreign keys should never receive a default value, no matter what the referenced column is. It makes no sense.

Database: MySQL 5.7

**Comment by chrisguitarguy** [comment]
This is an issue for [the DBAL](https://github.com/doctrine/dbal) -- all the schema and schema diffing code resides there. Migrations just uses it.

**Comment by jwage** [comment]
Closing here. You can create an issue in doctrine/dbal for this.
