### ISSUE TITLE
[feature] Generate NOT NULL columns as a sequence of queries with updating existing rows

### ISSUE THREAD

**Issue by finwe** [doctrine/migrations#603]
In current version, `NOT NULL` column is generated as a single SQL query.

    $this->addSql('ALTER TABLE curriculum ADD help BOOLEAN NOT NULL');

This inevitably ends with SQL error `column "help" contains null values` when there are items present in the `curriculum` table.

It would help a lot if the migration in this case were generated as a serie of queries:

    $this->addSql('ALTER TABLE curriculum ADD help BOOLEAN NOT NULL');
    // $this->addSql('UPDATE curriculum SET help = \'f\''); // prefill? Or use a placeholder?
    $this->addSql('ALTER TABLE curriculum ALTER COLUMN help SET NOT NULL');

I guess this involves DBAL to some extent but do not think it is a sole concern of DBAL as it does not care about existing data. But Migrations surely should.

I'd be happy to give this some time if the feature is found helpful but do not really know how to grasp this.

**Comment by jwage** [comment]
Hi @finwe, Thanks for creating the issue and explaining your thoughts. I have thought about this before too. I came to the conclusion that this is not something that we can consistently and reliably do. It is up to the developer to properly migrate their data when making schema changes.

**Comment by jwage** [comment]
@stof Good thought. That makes sense. I think this would require a change to the DBAL then if we wanted it to behave this way.

**Comment by stof** [comment]
yeah, probably

**Comment by SenseException** [comment]
Because of #3856 I want to ask my questions here where the discussion already started.

Wouldn't it be a way with less queries if the first query introduces a default value? I'm not familiar with all supported databases, but if they all do support setting existing null-values to a default value, we could do this with just two queries.

**Comment by goetas** [comment]
I personally don't like to rely too much on generated migrations, they are nice and gives you good starting point, but in most of the cases I customize them with specific optimizations supported by the underlying database.

Having two queries could help in some cases, but I know that as example Mariadb 10.1 does not handle at scale well this situation (there is a special syntax 'alter table online...')

**Comment by finwe** [comment]
@SenseException Default value set in database does not make much sense, because when the default value is set in database, all new items (crated in the future) have that default value and you might not notice this in the application (not setting the value in the application will never fail). That's usually not what you want.
