### ISSUE TITLE
Could migrations:diff also generate data migration?

### ISSUE THREAD

**Issue by rkeet** [doctrine/migrations#604]
A small brainfart went off today when testing around with migrations:

Could `./vendor/bin/doctrine-module migrations:diff` also generate the data migration code?

Currently it creates the up and down scripts and focuses purely on the data structure, which makes sense (and thank you, saves a lot of work!). 

A bit of refactoring today got me thinking though, by default what it does is perfect, but could it not check if columns deleted from A match columns added in B? And, if yes, create a data migration script as well?

Consider the following up script (leaving out corresponding down as it's just in reverse):

    public function up(Schema $schema)
    {
        // $this->abortIf(...);

        $this->addSql('ALTER TABLE secret_table_B ADD order_import_enabled TINYINT(1) NOT NULL');
        // What if there was a generated migration script here?
        $this->addSql('ALTER TABLE secret_table_A DROP order_import_enabled');
    }

In this case the script concerns a single table/entity. The DROP from A matches the ADD to B. If/when these conditions are met (same columns dropped from one and added to another), a question could be asked, such as "Are you migrating data from A to B? y/N". No is the default so no action would be taken without user permission. In the case of "y", the data migration code could be placed in place of the comment in the example up script above.

**Comment by jwage** [comment]
Hi @rkeet, this is not something I think we should support. It would work in a very narrow amount of cases. The responsibility of migrating data is up to the developer. Thanks!
