### ISSUE TITLE
--write-sql with no value is not working

### ISSUE THREAD

**Issue by podorozhny** [doctrine/migrations#605]
Hello.

`migrations:migrate --write-sql` will try to execute migrations instead of write SQL to default path, because here is no default InputOption value (NULL is default value, actually):

https://github.com/doctrine/migrations/blob/6eff53d2bf750192b45b736d4f86905a7e07799b/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php#L29

`$input->getOption('write-sql')` will always return NULL when path not specified. 
https://github.com/doctrine/migrations/blob/6eff53d2bf750192b45b736d4f86905a7e07799b/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php#L116

**Comment by podorozhny** [comment]
Short example of how symfony console component actually works:

```
➜  console git:(master) ✗ php test.php foobar                                                                               ✱
NULL
➜  console git:(master) ✗ php test.php foobar --write-sql                                                                   ✱
NULL
➜  console git:(master) ✗ php test.php foobar --write-sql=/tmp/migration.sql                                                ✱
string(18) "/tmp/migration.sql"
```

_test.php:_
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

final class FoobarCommand extends Command
{
    protected function configure(): void
    {
        $this->setName('foobar');
        $this->addOption('write-sql', null, InputOption::VALUE_OPTIONAL, '...');
    }

    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        var_dump($input->getOption('write-sql'));
    }
}

$application = new Application();
$application->add(new FoobarCommand());
$application->run();
```

**Comment by stof** [comment]
`InputOption::VALUE_OPTIONAL` is tricky to use.

https://github.com/doctrine/migrations/pull/562 was broken.

**Comment by podorozhny** [comment]
https://github.com/doctrine/migrations/pull/606

**Comment by podorozhny** [comment]
Uhh, looks like we can not just set default value for this option and moreover symfony console does not allow us to know whether the flag was explicitly specified or not.

**Comment by jwage** [comment]
The `--write-sql` option will allow you to specify a value for where to write the sql file to in 2.0 via this PR #666
