### ISSUE TITLE
Create branches for supported versions

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#614]
Can we create branches for the versions we currently support? This is so that I can show versions on the website and point to the correct branch. I do not mind doing this myself but I wanted to get  feedback from someone first and find out what versions we support.

**Comment by mikeSimonson** [comment]
What versions do we want to support ?

**Comment by lcobucci** [comment]
Shouldn't we release 1.7 then?

**Comment by jwage** [comment]
Sure. I started a 2.0 branch locally that I can push up tomorrow and once we are ready we can merge 2.0 branch to master and keep working on it there.

**Comment by jwage** [comment]
I created a `1.6` from the `1.6.2` tag and I created a `1.7` branch from master. This is in preparation for merging #617 to master so we can continue working on 2.0 in master.
