### ISSUE TITLE
Move migrations out of the DBAL namespace

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#620]

**Comment by stof** [comment]
What was the reasonning for this BC break ? Migrations are tied to DBAL anyway.

**Comment by lcobucci** [comment]
@stof my understanding is that migrations is not a subcomponent of DBAL, it simply depends on DBAL. So it does make sense to have it in its own namespace.

**Comment by stof** [comment]
but this makes the migration to v2 much harder, for no real benefit IMO. I would not argue about the `Doctrine\Migrations` namespace for a new project, but I don't think the cost of this BC break is worth it.

**Comment by jwage** [comment]
@stof I agree, but since people use migrations more as a tool, not a library, the only change they have to make is in one use statement in their migration classes, right?

**Comment by stof** [comment]
If it is actually the only needed change, I'm fine with that (and we could even provide a deprecated class with the old name extending the new one, tomake the migration even easier (old migrations would keep working with a deprecation warning)
