### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#623]
In order to change the license on this project, we have to get the approval of every past contributor. At the time of writing this we have had 107 contributors.

If you are reading this and you are a contributor on the below list, please reply to this GitHub issue with the following text:

```
I, @username, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.
```

- [x] @PapsOu
- [x] @DavidHavl 
- [x] @jkrcma 
- [x] @ErikSaunier 
- [x] @tavy315
- [x] @meckhardt
- [x] @shawndellysse
- [x] @rjmunro
- [x] @craigmarvelley
- [x] @mikeSimonson 
- [x] @dt-creasis
- [x] @pezia
- [x] @AolEvanFribourg
- [x] @Ocramius
- [x] @radekhubner 
- [x] @simensen 
- [x] @hype-
- [x] @robinvdvleuten
- [x] @alOneh
- [x] @jrobeson
- [x] @korstiaan
- [x] @sheridan-dev
- [x] @Padam87
- [x] @antonbabenko 
- [x] @m00t
- [x] @craue
- [x] @c960657
- [x] @aderuwe
- [x] @arnaud-lb 
- [x] @aaa2000
- [x] @tombevers
- [x] @maxim-oleinik
- [x] @gsomoza
- [x] @ReenExe
- [x] @iVariable
- [x] @ErikTrapman
- [x] @vershnik 
- [x] @aivus
- [x] @syzygymsu
- [x] @jwage
- [x] @Majkl578
- [x] @fabpot
- [x] @rybakit
- [x] @beberlei
- [x] @localheinz
- [x] @TomasVotruba
- [x] @rcatlin
- [x] @neeckeloo
- [x] @alcaeus 
- [x] @ornicar
- [x] @Nyholm
- [x] @asgrim
- [x] @stof
- [x] @lsmith77
- [x] @lcobucci
- [x] @mantiz
- [x] @shieldo
- [x] @Jean85
- [x] @Safranil 
- [x] @egircys
- [x] @kriswallsmith
- [x] @drefixs
- [x] @farzadghanei
- [x] @diewom
- [x] @greg0ire
- [x] @carusogabriel 
- [x] @mpdude
- [x] @kkamkou
- [x] @jalliot
- [x] @tifabien
- [x] @bamarni
- [x] @thanosp
- [x] @cassiosantos
- [x] @pborreli
- [x] @mlocati
- [x] @bountin
- [x] @itised
- [x] @chrisguitarguy 
- [x] @weaverryan
- [x] @schmittjoh
- [x] @burci
- [x] @liquorvicar
- [x] @xosofox
- [x] @smatyas
- [x] @tvlooy
- [x] @Aliance 
- [x] @r0b1n
- [x] @kander
- [x] @Seldaek
- [x] @jeromegamez
- [x] @BreiteSeite
- [x] @funivan
- [x] @eko
- [x] @schroedan
- [x] @rodnaph
- [x] @kimhemsoe
- [x] @denderello
- [x] @michaelperrin
- [x] @mrtorrent
- [x] @sergiughf
- [x] @abacaphiliac
- [x] @tobiasstadler
- [x] @guilhermeblanco
- [x] @Soullivaneuh

Don't need approval from these people?

- [ ] @bizmate - changes are trivial and have been mostly committed over ([commits](https://github.com/doctrine/migrations/commits?author=bizmate))
- [ ] @louiscytc - changes trivial enough to not require approval? ([commits](https://github.com/doctrine/migrations/commits?author=louiscytc))

**Comment by jwage** [comment]
I, @jwage, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by fabpot** [comment]
I, @fabpot, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Majkl578** [comment]
I, @Majkl578 approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by localheinz** [comment]
I, @localheinz, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by rybakit** [comment]
I, @rybakit, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by aivus** [comment]
I, @aivus, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by beberlei** [comment]
I, @beberlei, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by syzygymsu** [comment]
I, @syzygymsu, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by TomasVotruba** [comment]
I, @tomasvotruba, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by neeckeloo** [comment]
I, @neeckeloo, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Nyholm** [comment]
I, @nyholm, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by asgrim** [comment]
I, @asgrim, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by alcaeus** [comment]
I, @alcaeus, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by ornicar** [comment]
I, @ornicar, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by stof** [comment]
I, @stof, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by lsmith77** [comment]
I, @lsmith77 approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by lcobucci** [comment]
I, @lcobucci, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by shieldo** [comment]
I, @shieldo, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Jean85** [comment]
I, @Jean85, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by egircys** [comment]
I, @egircys, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Safranil** [comment]
I, @Safranil, approve changing the doctrine/migrations project from the
license LGPL-2.1 to MIT effective immediately.

Le sam. 5 mai 2018 à 19:04, Jonathan H. Wage <notifications@github.com> a
écrit :

**Comment by greg0ire** [comment]
I, @greg0ire, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

Amen.

**Comment by diewom** [comment]
I, @diewom, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by drefixs** [comment]
I, @drefixs, approve changing the doctrine/migrations project from the
license LGPL-2.1 to MIT effective immediately.

**Comment by kriswallsmith** [comment]
I, @kriswallsmith, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by carusogabriel** [comment]
I, @carusogabriel, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by bamarni** [comment]
I, @bamarni, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by thanosp** [comment]
I, @thanosp, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by mpdude** [comment]
I, @mpdude, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by mpdude** [comment]
@jwage Heads up: I only noticed this by chance, although my name is on the list above. It‘s not printed in bold, though, so maybe GH has a limit of how many ppl you can @-mention in a single comment?

**Comment by jwage** [comment]
@mpdude yes, max number of mentions. I am moving the checked ones down to the bottom so it will notify the people who have not approved yet.

**Comment by jalliot** [comment]
I, @jalliot, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by tifabien** [comment]
I, @tifabien, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by itised** [comment]
I, @itised, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by mlocati** [comment]
I, @mlocati, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by pborreli** [comment]
I, @pborreli, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by bountin** [comment]
I, @bountin, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately

**Comment by chrisguitarguy** [comment]
I, @chrisguitarguy, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by schmittjoh** [comment]
@schmittjoh, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by burci** [comment]
I, @burci, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by xosofox** [comment]
I, @xosofox, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by liquorvicar** [comment]
I, @liquorvicar, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by smatyas** [comment]
I, @smatyas, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by tvlooy** [comment]
I, @tvlooy, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Aliance** [comment]
I, @Aliance, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by r0b1n** [comment]
I, @r0b1n, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by kander** [comment]
I, @kander, approve changing the doctrine/migrations project from the
license LGPL-2.1 to MIT effective immediately.

Op zo 6 mei 2018 om 10:04 schreef Roman Vyakhirev <notifications@github.com>

**Comment by Seldaek** [comment]
I, @Seldaek, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by jeromegamez** [comment]
I, @jeromegamez, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by BreiteSeite** [comment]
I, @BreiteSeite, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by funivan** [comment]
I, @funivan, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by eko** [comment]
I, @eko, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by rodnaph** [comment]
I, @rodnaph, approve changing the doctrine/migrations project from the
license LGPL-2.1 to MIT effective immediately.

**Comment by kimhemsoe** [comment]
I, @kimhemsoe, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by abacaphiliac** [comment]
I, @abacaphiliac, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by vershnik** [comment]
I, @vershnik, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by tobiasstadler** [comment]
I, @tobiasstadler, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by denderello** [comment]
I, @denderello, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by sergiughf** [comment]
I, @sergiughf, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by michaelperrin** [comment]
I, @michaelperrin, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by guilhermeblanco** [comment]
I, @guilhermeblanco, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by iVariable** [comment]
I, @iVariable, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by c960657** [comment]
I, @c960657, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by tombevers** [comment]
I, @tombevers, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by aaa2000** [comment]
I, @aaa2000, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by korstiaan** [comment]
I, @korstiaan, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by ErikTrapman** [comment]
I, @ErikTrapman, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by maxim-oleinik** [comment]
I, @maxim-oleinik, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by MatthiasKuehneEllerhold** [comment]
I, @MatthiasKuehneEllerhold, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by robinvdvleuten** [comment]
I, @robinvdvleuten, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by craue** [comment]
I, @craue, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by antonbabenko** [comment]
I, @antonbabenko, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by gsomoza** [comment]
I, @gsomoza, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by sheridan-dev** [comment]
I, @sheridan-dev, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by arnaud-lb** [comment]
I, @arnaud-lb, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by m00t** [comment]
I, @m00t, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by jrobeson** [comment]
I, @jrobeson, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by hype-** [comment]
I, @hype-, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Padam87** [comment]
I, @Padam87, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by ReenExe** [comment]
I, @ReenExe, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by aderuwe** [comment]
I, @aderuwe, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by simensen** [comment]
I, @simensen, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by AolEvanFribourg** [comment]
I, @AolEvanFribourg, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by radekhubner** [comment]
I, @radekhubner, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by pezia** [comment]
I, @pezia, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by dt-creasis** [comment]
I, @dt-creasis, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by craigmarvelley** [comment]
I, @craigmarvelley, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by mikeSimonson** [comment]
I, @mikeSimonson, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by shawndellysse** [comment]
I, @shawndellysse, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by tavy315** [comment]
I, @tavy315, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by jkrcma** [comment]
I, @jkrcma, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by PapsOu** [comment]
I, @PapsOu, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by ErikSaunier** [comment]
I, @ErikSaunier, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Soullivaneuh** [comment]
I, @Soullivaneuh, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

Not needed, but at lest it's done. :+1:

**Comment by DavidHavl** [comment]
I, @DavidHavl, approve changing the doctrine/migrations project from the license LGPL-2.1 to MIT effective immediately.

**Comment by Ocramius** [comment]
We're through :ship:
