### ISSUE TITLE
Upgrade to Box 3

### ISSUE THREAD

**Issue by theofidry** [doctrine/migrations#624]
Before I start to try to replace the existing Box2 with Box3, I would like to know if there is any e2e tests to ensure the generated PHAR is working.

/cc @mikeSimonson

**Comment by jwage** [comment]
I don't think there are unfortunately.

**Comment by mikeSimonson** [comment]
The e2e test is me running some version and status command on my local machine ;p

**Comment by theofidry** [comment]
Haha fair, ok follow up in #270 I guess

**Comment by jwage** [comment]
Can we do this for 2.0?

**Comment by theofidry** [comment]
Sure

**Comment by jwage** [comment]
@theofidry I am going to start work on this.

**Comment by theofidry** [comment]
Cool. Don't hesitate to ping me on Slack or Twitter if you have an issue
