### ISSUE TITLE
Add Doctrine\DBAL\Migrations\AbstractMigration class with deprecation warning

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#642]
Since we moved Doctrine\DBAL\Migrations to Doctrine\Migrations, we want to make the transition to 2.0 a little easier so deprecate this method in 1.8 deprecation release.

**Comment by lcobucci** [comment]
@jwage I think this should be `v1.8.0` since we're deprecating things and not fixing bugs (we're doing the same with the ORM - v2.7 will only ship deprecations).

**Comment by stof** [comment]
Well, this class cannot be deprecated in 1.8, as the new namespace is not there at all in 1.8 so this is the non-deprecated class in 1.x.

the idea of keeping a deprecated `Doctrine\DBAL\Migrations\AbstractMigration` in 2.0 would be that any migration generated with 1.x would keep working in 2.0 for people using doctrine/migrations as a tool (they should change the parent class to get rid of the deprecation)

**Comment by jwage** [comment]
@stof makes sense. I will prepare this change for the master branch and we can remove the deprecated class in 2.1.

**Comment by stof** [comment]
well, removal should happen in 3.0, not in 2.1, as that's a BC break (but the class itself will not cost a lot for maintenance, as it will be an empty class extending the new one, with a deprecation warning in the file)

**Comment by jwage** [comment]
@stof :+1:

**Comment by stof** [comment]
note that this still implies being caring about the inner API of the class for BC (code has access to protected APIs of the class, when extending it)

**Comment by lcobucci** [comment]
> Well, this class cannot be deprecated in 1.8, as the new namespace is not there at all in 1.8 so this is the non-deprecated class in 1.x.

My proposal was to rather provide a forward compatibility layer in 1.x, just like PHPUnit did. But I'm fine with both strategies.

IMO it all depends on how many intermediate major releases we want to have till the code base is properly cleaned up. Creating a well defined roadmap would definitely help us understand and communicate these things better. It would also allows us to define boundaries for the refactoring we want to do in v2.

**Comment by Majkl578** [comment]
I would prefer doing that in 1.x too, instead of polluting brand new 2.0 with deprecated code.

**Comment by jwage** [comment]
Can we put this deprecation and forward compatibility layer in a 1.7.x release so we don't have to maintain another branch in parallel with 1.7?
