### ISSUE TITLE
Should we support 7.2 only in doctrine/migrations 2.0?

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#644]
Without PHP 7.2 you will never be able to support both 1.x and 2.x if you implement/override at least one method that now has scalar parameter type hints. Should we support 7.2 only for doctrine/migrations 2.0?

**Comment by Majkl578** [comment]
7.2 benefits described more in detail here: https://github.com/doctrine/doctrine2/issues/6529

**Comment by jwage** [comment]
After a discussion in Gitter we decided that for 2.0, it is not necessary to be PHP 7.2 only. Most people use the migrations project as a tool and not a library so the use case of supporting migrations 1.x and 2.x is not something we need to worry about. If anyone else has another use case or opinion here, let us know. Thanks!
