### ISSUE TITLE
Bring back support for Symfony 3.4

### ISSUE THREAD

**Issue by emodric** [doctrine/migrations#651]
https://github.com/doctrine/migrations/pull/639 bumped old dependencies to newer versions, and in the process, Symfony components dependencies were bumped to `^4.0`.

However, since currently, only LTS version of Symfony is 3.4, and will be for the next year and a half, it would be nice for version 2.0 of Migrations to support it.

**Comment by stof** [comment]
this would be very easy, as all 4.0 features exist in 3.4, so it is already compatible (except for the constraint)

**Comment by jwage** [comment]
@emodric Thanks! Pushed up #653 to address this.
