### ISSUE TITLE
DBAL Type "date" gets saved as "datetime" in db

### ISSUE THREAD

**Issue by MichaelBelgium** [doctrine/migrations#708]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no/yes
| Version     | 1.5.0

#### Summary

I don't think this is the purpose?
The point is, when making a migration and you add a column with type "date" (`Doctrine\DBAL\Types\Type::DATE`) the type in the database is **datetime**

The MySQL version i use is 5.7 and as far as i know it [does](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) support the date type. 

#### Current behavior

When creating a table with a column that has the type date, in the database it will be a datetime

#### How to reproduce

* Generate a migration
* Create a table
* Add a column to the table with type date
```PHP
    public function up(Schema $schema)
    {
        // example i used
        $table = $schema->createTable(self::TABLE);

        $table->addColumn('id',Type::INTEGER)->setAutoincrement(true);
        $table->addColumn('datum', Type::DATE);

        $table->setPrimaryKey(['id']);
    }
```
* Execute migration
* Check on the mysql server the columns of the table and realize it's a datetime field instead of a date field
```
+-------+----------+------+-----+---------+----------------+
| Field | Type     | Null | Key | Default | Extra          |
+-------+----------+------+-----+---------+----------------+
| id    | int(11)  | NO   | PRI | NULL    | auto_increment |
| datum | datetime | NO   |     | NULL    |                |
+-------+----------+------+-----+---------+----------------+
```

#### Expected behavior

This table:
```
+-------+---------+------+-----+---------+----------------+
| Field | Type    | Null | Key | Default | Extra          |
+-------+---------+------+-----+---------+----------------+
| id    | int(11) | NO   | PRI | NULL    | auto_increment |
| datum | date    | NO   |     | NULL    |                |
+-------+---------+------+-----+---------+----------------+

```

**Comment by Majkl578** [comment]
Please open a [bug report on DBAL](https://github.com/doctrine/dbal/issues/new?template=Bug.md) repository that does the conversion to platform type (or create a pull request if possible), this is out of scope here.
Thanks.
