### ISSUE TITLE
Eliminate dependency on doctrine/common

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#722]
This will require doctrine/dbal 2.8 without common and the work to continue to split up doctrine/common in to separate projects has to be finished.

**Comment by stof** [comment]
AFAIK, the only part of Doctrine Common used directly in doctrine/migrations is the event part. So as soon as that part is extracted to a dedicated package, we can change the requirement here

**Comment by jwage** [comment]
It will remove doctrine/common from doctrine/migrations directly, but it will still be pulled in by doctrine/dbal dependency until we upgrade to doctrine/dbal 2.8.

**Comment by stof** [comment]
But until we use the event system directly, we cannot remove the direct dependency.

**Comment by goetas** [comment]
Do you thing that https://github.com/doctrine/migrations/pull/883 addresses this issue?

**Comment by alcaeus** [comment]
This library already doesn't depend on doctrine/common anymore, so I'm closing this issue. DBAL is tracked separately.
