### ISSUE TITLE
Use dependency injection for console commands

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#726]
Right now we rely on service location and Symfony console helper sets in order to get the dependencies for commands. This makes testing a pain and the code is less than ideal. We need to clean this up and rely on dependency injection for the commands.

**Comment by stof** [comment]
while this is fine for the usage in the Symfony bundle (we can configure commands there), it might be harder for the standalone CLI.

**Comment by goetas** [comment]
Should have been solved in https://github.com/doctrine/migrations/pull/858

**Comment by goetas** [comment]
done in https://github.com/doctrine/migrations/pull/898
