### ISSUE TITLE
Keep doing the same database change over and over again

### ISSUE THREAD

**Issue by hackzilla** [doctrine/migrations#728]
|    Q        |   A
|------------ | -----
| Version     | 1.7.2

### Support Question

every time I do a diff I get the same change, regardless of how many times I apply it.

an example migration that is failing:

```SQL
ALTER TABLE project CHANGE id id CHAR(36) NOT NULL COMMENT '(DC2Type:uuid)'
```

After have a look around, the issue appears to be that the information_schema.STATISTICS doesn't include any comments.

```
TABLE_CATALOG	TABLE_SCHEMA	TABLE_NAME	NON_UNIQUE	INDEX_SCHEMA	INDEX_NAME	SEQ_IN_INDEX	COLUMN_NAME	COLLATION	CARDINALITY	SUB_PART	PACKED	NULLABLE	INDEX_TYPE	COMMENT	INDEX_COMMENT
def	my-table	project	0	my-table	PRIMARY	1	id	A	1	NULL	NULL		BTREE		
```

But when I do a describe, they do.

```
SHOW FULL COLUMNS FROM  `project`;

Field	Type	Collation	Null	Key	Default	Extra	Privileges	Comment
id	char(36)	utf8mb4_unicode_ci	NO	PRI	NULL		select,insert,update,references	(DC2Type:uuid)
```

 I am using Mysql 5.7.22 and I'm hoping you can point me in the right direction.

**Comment by stof** [comment]
the computation of the schema diff is not implemented in Doctrine Migrations but in Doctrine DBAL (Doctrine Migrations reuses the DBAL feature). Please report it there
