### ISSUE TITLE
Missing class when updating from v1.7.2 to 1.8.0

### ISSUE THREAD

**Issue by Spomky** [doctrine/migrations#730]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.8.0

#### Summary

I have just called `composer update` and `doctrine/migrations` get updated from v1.7.2 to 1.8.0.

#### Previous behavior

Was working fine

#### Current behavior

I have the following exception:

> In Configuration.php line 74:
> Class Doctrine\DBAL\Migrations\Configuration\Configuration does not exist

**Comment by jwage** [comment]
@Spomky v1.8.1 was tagged, can you give it a try? Sorry about that :( https://github.com/doctrine/migrations/releases/tag/v1.8.1

**Comment by Spomky** [comment]
Looks god now.
Thank you :+1:
