### ISSUE TITLE
Backport Doctrine\Migrations\AbstractMigration to 1.5

### ISSUE THREAD

**Issue by emodric** [doctrine/migrations#732]
|    Q        |   A
|------------ | -----
| Version     | 1.5.0

Version 1.5 is the last version that supports PHP 5.6, so it would be nice if `Doctrine\Migrations\AbstractMigration` was backported to 1.5 branch to ease upgrades to Migrations 2.0 once we kick out PHP 5.6 for good.

Is there any chance for this to happen?

Thanks!

**Comment by Majkl578** [comment]
I don't think this could happen, 1.5 is not maintained anymore.
I'd suggest to upgrade to 1.8 first, update your references, then upgrade to 2.0.
Both 1.8 and 2.0 require PHP 7.1 so once on 1.8, it should be really easy to switch to 2.0.

**Comment by jwage** [comment]
I don't think we can technically based on semver anyways. Deprecations can't be introduced in a point release right?

**Comment by emodric** [comment]
@Majkl578 I can't upgrade to 1.8, because our app still allows installing on PHP 5.6 and there are two or three clients actually using PHP 5.6, so for them, 1.5 is an only viable option. If it were PHP 7.1 only, there would be no issues.

The only reason why I ask for backport to 1.5 is to get rid of deprecations by switching to the new namespace. Old class wouldn't need to be deprecated in 1.5 ofcourse.

**Comment by Majkl578** [comment]
@emodric That is ok, when they only use PHP 5.6, they'll never be able to upgrade to Migrations 2.0 anyway. In that case, it's perfectly ok to keep the current namespace.
I don't think this can/should be handled on our side, but you can easily introduce the polyfill yourself in your application (using i.e. `class_alias` + composer autoload-files).

**Comment by emodric** [comment]
> but you can easily introduce the polyfill yourself in your application (using i.e. class_alias + composer autoload-files).

Yep, I'm aware :) I asked here though since most probably there are others with similar needs.

**Comment by stof** [comment]
I think that the proper migration path for people stuck on PHP 5.6 today would be to migrate to PHP 7 first, then to upgrade to doctrine/migrations 1.8 to get the deprecation layers and then go to 2.0.
I don't think backporting this to 1.5 makes sense.

**Comment by alcaeus** [comment]
> I don't think we can technically based on semver anyways. Deprecations can't be introduced in a point release right?

Correct - deprecations MUST be introduced in a minor release. Any new API (new methods, interfaces, classes) also require a minor release, so there's no chance you can backport the new class including the deprecation to a previous minor release.

As stof said, if your concern is migration to 2.0, you should always be running on the latest 1.x release before you start fixing deprecations. Backporting deprecations to older minor releases is not something we should spend our time with (and something that's actually disallowed by Semver).

**Comment by emodric** [comment]
> Backporting deprecations to older minor releases is not something we should spend our time with (and something that's actually disallowed by Semver).

For the record, I didn't ask a deprecation to be made in 1.5, only a forward compatible class to be added.

But anyway, I realized later that migration to 2.0 wouldn't be possible anyway while keeping compatibility with PHP 5.6, due to introduced return typehints in 2.0.
