### ISSUE TITLE
Add standalone list command for listing migrations

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#734]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Currently you can show versions with the `status --show-versions` command and option but it'd be a better and more clear developer experience to have a `list` command. This command could also show more information than the `status --show-versions` command.

**Comment by goetas** [comment]
done in https://github.com/doctrine/migrations/pull/908
