### ISSUE TITLE
Running UpToDate command always says migrations are not up to date.

### ISSUE THREAD

**Issue by JanMikes** [doctrine/migrations#738]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 1.8.1

#### Summary

I was debugging and found the problem is in following condition:
<img width="1321" alt="screenshot 2018-06-24 17 32 34" src="https://user-images.githubusercontent.com/3995003/41820688-fe0a4232-77d5-11e8-8418-90ee04d83e8b.png">

`$availableMigrations` is -2 which obviously results `=== 0` to false.

Though i am not sure why `$migrations` is 0 and not 2? I found out that the problem might be caused by that `Doctrine\DBAL\Migrations\Configuration::getMigrations()` is called, when the `$migrations` property is empty.

Imho this would be fixed by adding similar check to `getMigrations()` method as is here:
```php
    public function getVersion($version)
    {
        if (empty($this->migrations)) {
            $this->registerMigrationsFromDirectory($this->getMigrationsDirectory());
        }
```

#### Current behavior

`bin/console migrations:up-to-date` alwas reports it is not up-to date:
```
▶ bin/console migrations:up-to-date            
Out-of-date! 18446744073709551614 migration is available to execute.
```

#### How to reproduce

Just create any diff, migrate and run the up-to-date command.

#### Expected behavior

Expected output is to see it is up to date 😄

**Comment by magnetik** [comment]
In version 2.0-dev the up-to-date commands works fine here. 

It might be already fixed for 2.0?

**Comment by jwage** [comment]
It is possible. In 2.0 everything was refactored and lots of inconsistencies were fixed so it might have been fixed indirectly.

**Comment by magnetik** [comment]
So yep, confirming it as fixed 👍
