### ISSUE TITLE
MigrationStatusInfosHelper::getFormattedVersionAlias() doesn't show full class name + sub-namespace

### ISSUE THREAD

**Issue by Majkl578** [doctrine/migrations#742]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.0-alpha1

#### Summary

Given a structured migrations setup with sub-namespaces, where migration class name looks like:
```
App\Migrations\SomeFeature\Version20180702173000
```
Where `App\Migrations` is the root migrations' namespace.

The Status command only shows version number itself, not the class number + namespace.

#### Current behavior

The class above would be reported as:
```
Current Version: 2018-07-02 17:30:00 (20180702173000)
```

#### Expected behavior

When using sub-namespaces, it'd be a good idea to output the namespace as well. Maybe printing the sub-namespace + class name would be ideal:
```
Current Version: 2018-07-02 17:30:00 (SomeFeature\Version20180702173000)
```

Also it's questionable whether it's desired to print version number formatted as a date like this as _current version_.

**Comment by goetas** [comment]
I believe that this is solved in 3.x
