### ISSUE TITLE
Eliminate HelperSet usage in console-related code

### ISSUE THREAD

**Issue by Majkl578** [doctrine/migrations#743]
### Feature Request

|    Q        |   A
|------------ | ------
| RFC         | yes
| BC Break    | yes

#### Summary

Depending on whether https://github.com/symfony/symfony/pull/27647 gets merged into Symfony 4.2 or not, HelperSet may become deprecated.

This would affect all Migrations console commands as the HelperSet is used [quite extensively](https://github.com/doctrine/migrations/search?q=helperset&unscoped_q=helperset):
* https://github.com/doctrine/migrations/blob/ba84e1ee9059a586abaefa51bb1b983f6cc67888/lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php#L32
* https://github.com/doctrine/migrations/blob/bba2123d7d8ab43927ff2370a4785892b7c181d5/lib/Doctrine/Migrations/Tools/Console/ConnectionLoader.php#L47
* https://github.com/doctrine/migrations/blob/f392a2b8ee980e9c2420a946c31ddae5bca4ecd5/lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php#L175-L199
* https://github.com/doctrine/migrations/blob/ba84e1ee9059a586abaefa51bb1b983f6cc67888/lib/Doctrine/Migrations/Configuration/Connection/Loader/ConnectionHelperLoader.php#L22-L51
* https://github.com/doctrine/migrations/blob/08aba2a70b8c9eb7ddd53cf3c28b25f943b5035d/bin/doctrine-migrations.php#L65-L91

Even if the referenced deprecation doesn't make it into 4.2/4.x, it'd still be a good idea to do this change before 2.0 GA.

**Comment by goetas** [comment]
https://github.com/doctrine/migrations/pull/898 should address this

**Comment by goetas** [comment]
done in https://github.com/doctrine/migrations/pull/898
