### ISSUE TITLE
Incorrect Message Display When Generating Migrations In a Read-Only File System

### ISSUE THREAD

**Issue by vitoacme** [doctrine/migrations#744]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | not sure
| Version     | 1.5

#### Summary

Running `migrations:generate` in a read only directory displays `Generated new migration class to _path_to_new_migration_file_in_config_dir.php` even though, no file gets generated.

#### How to reproduce
1. Create a read only directory
2. Set that directory as your migrations directory
3. Run the command to generate migrations

#### Expected behavior
Should display message similar to `Cannot create the migration file. Specified migration directory is for read only.`

**Comment by alcaeus** [comment]
Can you please provide a more thorough explanation of the "read only file system" you created? We write the migration using `file_put_contents`, which will generally cause an error when it can't write to the path specified. For example, making the directory unwritable using `chown`/`chmod` causes an exception:
```
In GenerateCommand.php line 114:
                                                                                                                                                      
  Warning: file_put_contents([...]/migrations/Version20180724134259.php): failed to open stream: Permission denied                                                                                                
```

If this exception doesn't appear, your file system is doing something funky and acknowledging writes even though it's throwing the written contents in the trash. In that case, we can't find out whether it's a "read-only" file system or not. As mentioned above, please provide additional details - the information we have does not point to an error in this library.

**Comment by vitoacme** [comment]
After a little bit of digging I realized that we were doing something funky so I'll close this issue. Sorry to bother and thanks for your time :)
