### ISSUE TITLE
WordPress example

### ISSUE THREAD

**Issue by szepeviktor** [doctrine/migrations#750]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I'd like to donate WordPress configuration `migrations-db.php`

```php
<?php
/**
 * Doctrine Migrations Configuration for WordPress
 *
 * @link https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/configuration.html
 */

require_once __DIR__ . '/vendor/autoload.php';

// Load WordPress
require_once __DIR__ . '/path/to/wp-load.php';

// Set up connection
return array(
    'driver'   => 'mysqli',
    'host'     => DB_HOST,
    'dbname'   => DB_NAME,
    'user'     => DB_USER,
    'password' => DB_PASSWORD,
);
```

How to proceed?
Please advise.

**Comment by jwage** [comment]
Hi, thanks for the issue. Maybe we can add this to the documentation to show people how you can integrate with Wordpress?

**Comment by szepeviktor** [comment]
@jwage OK. Could you please add it to the appropriate document?

**Comment by jwage** [comment]
Hi @szepeviktor, I tend to work on things in doctrine/migrations that are interesting and/or useful for me with how I use the project. If you would like to see this addition, I would gladly merge a pull request from you or someone else.

**Comment by szepeviktor** [comment]
@jwage Okay!

This issue can be found by searching for "wordpress".

**Comment by axi** [comment]
In the CLI context, I had to set 
```php
$_SERVER['HTTP_HOST'] = 'localhost';
```
before loading wordpress.
