### ISSUE TITLE
Generated migration is not full qualified class name

### ISSUE THREAD

**Issue by kemoc** [doctrine/migrations#751]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no (i think no)
| Version     | 1.8.1

#### Summary

i think class name for generated migrations is wrong, do not respect correct namespace.

#### Current behavior

generated class name is:
DoctrineMigrations\Version20180923160333

#### How to reproduce

i have everything in bundle: RadekZ/Blog/BackendBundle/ in directory bundles/ - it's configured like App in Symfony demo
```
#composer.json
"psr-4": {
            "App\\": "src/",
            "RadekZ\\": "bundles/RadekZ/"
        }
```

i generated migration class by command:
```
php bin/console make:migration
```
then run:
```
php bin/console doctrine:migrations:migrate
```

i have got error:
```
  The autoloader expected class "RadekZ\Blog\BackendBundle\Migrations\Version20180923160333" to be defined in file "/var/www/project/vendor/compose  
  r/../../bundles/RadekZ/Blog/BackendBundle/Migrations/Version20180923160333.php". The file was found but the class was not in it, the class name o  
  r namespace probably has a typo. 
```
generated class name is:
DoctrineMigrations\Version20180923160333
in the file bundles/RadekZ/Blog/BackendBundle/Migrations/Version20180923160333.php

#### Expected behavior

i think class name should be
RadekZ/Blog/BackendBundle/Migrations/Version20180923160333

**Comment by jwage** [comment]
Can I see the configuration for your migrations setup? You have to specify the namespace you want your migrations to be in. See https://www.doctrine-project.org/projects/doctrine-migrations-bundle/en/1.3/index.html#line-number-736438bd40191058ab879b5b0069e537b43fe5c6-4

**Comment by kemoc** [comment]
> 
> 
> Can I see the configuration for your migrations setup? You have to specify the namespace you want your migrations to be in. See https://www.doctrine-project.org/projects/doctrine-migrations-bundle/en/1.3/index.html#line-number-736438bd40191058ab879b5b0069e537b43fe5c6-4

Thank you, i followed your link and configured, it helps, issue to close.
