### ISSUE TITLE
Migrations are always trying to overwrite default

### ISSUE THREAD

**Issue by MinDBreaK** [doctrine/migrations#755]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.8.1
#### Summary

All the entities and the annotations has been generated from the an existent database using the import tool from Doctrine. I encountered several issues, but in the end, it almost worked out well. 
Now I'm stuck with never ending default overwriting bug. 

I must add that everything must be generated through database are the app is migrating from ZF2 to SF4 and I cannot allow BC in ZF2 at the moment. 

#### Current behavior
When I am generating a migration, default are either : 
- Created
- Created then immediately dropped

It alternated every other migration.

Ex:

Migration 1: 
```php
$this->addSql('ALTER TABLE automatic_temperature_reading ALTER automatic_temperature_reading_id SET DEFAULT nextval(\'automatic_temperature_reading_automatic_temperature_reading_seq\'::regclass)');

$this->addSql('ALTER TABLE point_of_sales_automatic_reading ALTER point_of_sales_automatic_reading_id SET DEFAULT nextval(\'point_of_sales_automatic_read_point_of_sales_automatic_read_seq\'::regclass)');

$this->addSql('ALTER TABLE point_of_sales_store_order_item ALTER point_of_sales_store_order_item_id SET DEFAULT nextval(\'point_of_sales_store_order_point_of_sales_store_order_id_seq\'::regclass)');
```

Migration 2: 

```
$this->addSql('ALTER TABLE automatic_temperature_reading ALTER automatic_temperature_reading_id SET DEFAULT nextval(\'automatic_temperature_reading_automatic_temperature_reading_seq\'::regclass)');

$this->addSql('ALTER TABLE automatic_temperature_reading ALTER automatic_temperature_reading_id DROP DEFAULT');

$this->addSql('ALTER TABLE point_of_sales_automatic_reading ALTER point_of_sales_automatic_reading_id SET DEFAULT nextval(\'point_of_sales_automatic_read_point_of_sales_automatic_read_seq\'::regclass)');

$this->addSql('ALTER TABLE point_of_sales_automatic_reading ALTER point_of_sales_automatic_reading_id DROP DEFAULT');

$this->addSql('ALTER TABLE point_of_sales_store_order_item ALTER point_of_sales_store_order_item_id SET DEFAULT nextval(\'point_of_sales_store_order_point_of_sales_store_order_id_seq\'::regclass)');

$this->addSql('ALTER TABLE point_of_sales_store_order_item ALTER point_of_sales_store_order_item_id DROP DEFAULT');
```

And the next migration would be the first migration. 
I am aware that the sequences' names are not standard, but it should not impact as we are defining everything through options. 

One of the entity is defined as following. The two others are pretty much the same. 

```
    /**
     * @var int
     *
     * @ORM\Column(name="automatic_temperature_reading_id", type="integer", nullable=false,
     *      options={"default"= "nextval('automatic_temperature_reading_automatic_temperature_reading_seq'::regclass)"}
     * )
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="automatic_temperature_reading_automatic_temperature_reading_seq", allocationSize=1, initialValue=1)
     */
    private $automaticTemperatureReadingId;
```

#### How to reproduce

You need to create a database with entities generating id with a sequence and the default should be the `nextval(\'sequence_name\'::regclass)`

#### Expected behavior

The default should not be regenerated or dropped at each migration. 

> I will provide any information required. However I am not able to provide anytime soon a playground as demo.

**Comment by jwage** [comment]
1.3 is quite an old unsupported version. Can you test with the latest supported version and provide a  failing test case? It might be an issue in doctrine/dbal. What version of the dbal are you using?

**Comment by MinDBreaK** [comment]
Sorry this is a typo, I'm on 1.8.1. 
I have edited the post

I'm on DBAL 2.8.0

**Comment by broneq** [comment]
I'd the same issue, problem is that porstgresql DB schema reader has hardcoded pregmatch matching nextval(*) and setting default to null and autoincrement variable to true, which in your and my case isn't true.

I was thinking about overwrite that logic, but faster will be create overwritten nextval function in postgresql, and use it as default.

Unfortunately code of that library is't full OOP standard there is much of conditions hardcoded, I have custom type in my database and have many problems to support that (many extends and more conditions)

Maybe it is some other migrator, maybe dedicated for postgresql - but I didn't heard about that.

**Comment by jwage** [comment]
Can we move this issue to doctrine/dbal? That is where the problem will need to be worked on and fixed.

**Comment by broneq** [comment]
Ok, I tomorrow I'll describe more precisely and add a topic in dbal.
