### ISSUE TITLE
No backticks used in Migration Up function, but used in Migration Down function

### ISSUE THREAD

**Issue by PBrouwer** [doctrine/migrations#756]
### Bug Report

On my Entities I have used the `@ORM\Table` annotation to define the table name. Because I don't want to be restricted by reserved keywords of MySQL is used backticks in the table names.
However when I run `doctrine:migrations:diff`, after a change in the entity, the backticks are only used in the 'down' function and are not used in the 'up' function.

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | 1.3.1

#### Summary

No backticks used in Migration Up function, but used in Migration Down function

#### Current behavior

```php
public function up(Schema $schema) : void
{
    $this->addSql('ALTER TABLE language CHANGE created_by created_by INT NOT NULL');
}

public function down(Schema $schema) : void
{
    $this->addSql('ALTER TABLE `language` CHANGE created_by created_by INT DEFAULT NULL');
}
```
#### How to reproduce

Create an entity with ``@ORM\Table(name="`language`")`` annotation.
Run doctrine:migrations:diff command
Change a field in the Entity (i.e. make a field not nullable)
Run `doctrine:migrations:diff` command again

Created entity:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Language
 * @package App\Entity
 * @ORM\Entity()
 * @ORM\Table(name="`language`")
 * )
 */
class Language
{
   /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="createdEntities")
     * @ORM\JoinColumn(name="created_by")
     */
    private $createdBy;
}
```

Changed created_by to not nullable:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Language
 * @package App\Entity
 * @ORM\Entity()
 * @ORM\Table(name="`language`")
 * )
 */
class Language
{
   /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="createdEntities")
     * @ORM\JoinColumn(name="created_by", nullable=false)
     */
    private $createdBy;
}
```
#### Expected behavior
```php
public function up(Schema $schema) : void
{
    $this->addSql('ALTER TABLE `language` CHANGE created_by created_by INT NOT NULL');
}

public function down(Schema $schema) : void
{
    $this->addSql('ALTER TABLE `language` CHANGE created_by created_by INT DEFAULT NULL');
}
```

**Comment by stof** [comment]
That should be reported to DBAL, as that's were the SQL queries are generated for the diff
