### ISSUE TITLE
How can I use multiple migrations configuration?

### ISSUE THREAD

**Issue by roman-nagorny** [doctrine/migrations#762]
I have two variants of the doctrine.migrations_configuration:

Firstly, my ZF3 application uses 'orm_default' key in a configuration for its own migrations
    'doctrine' => [
        'migrations_configuration' => [
            'orm_default' => [
                'directory' => 'data/migration',
                'name'      => 'Doctrine Database Migrations for Password Storage Application',
                'namespace' => 'Migration',
                'table'     => 'migration',
            ],
        ],
    ],

Secondly, my another module from composer uses 'doctrine.migrations_configuration.selaxar_orm_entitymanager' for its own needs.

I'm trying to execute the migrations from another module via command line unsing --object-manager :
./vendor/bin/doctrine-module migrations:migrate --object-manager=doctrine.entitymanager.selaxar_orm_entitymanager

The problem is I can't execute migrations from another module. Can I execute another configuration instead of 'orm_default' settings?

There is another module:
[selaxar-lang.zip](https://github.com/doctrine/migrations/files/2534766/selaxar-lang.zip)
And I want to execute its migrations separately via command line. Is it possible?

**Comment by jwage** [comment]
This issue belongs in the https://github.com/doctrine/DoctrineORMModule repository which is the integration repository for the Zend Framework.
