### ISSUE TITLE
Broken page link

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine/migrations#769]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | x.y.z

#### Summary
Current version docs (at least) index page is broken

#### How to reproduce
1. go to https://www.doctrine-project.org/projects/migrations.html
2. then click the current version docs (which is https://www.doctrine-project.org/projects/doctrine-migrations/en/1.8/index.html at the moment )
3. See "Page not found" response

#### Expected behavior

1. go to https://www.doctrine-project.org/projects/migrations.html
2. then click the current version docs (which is https://www.doctrine-project.org/projects/doctrine-migrations/en/1.8/index.html at the moment )
3. See index page like here https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/index.html but for 1.8

**Comment by jwage** [comment]
Thanks, this is fixed now! The website had an issue with the deploy.
