### ISSUE TITLE
Remove `abortIf` with an option in command

### ISSUE THREAD

**Issue by roukmoute** [doctrine/migrations#781]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

We have created our own template wich have a `preUp` and `preDown`.
Thoses methods use `$this->abortIf(…)`.

So now this is not really necessary to keep this line in all our migration files: `$this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');`

Do you accept a P.R. with a new option which if it is given [it does not add](https://github.com/doctrine/migrations/blob/f392a2b8ee980e9c2420a946c31ddae5bca4ecd5/lib/Doctrine/Migrations/Generator/SqlGenerator.php#L62) this line?

**Comment by jwage** [comment]
Sure, we can include that as a new feature option in 2.1

**Comment by roukmoute** [comment]
Ok cool!
So I will do a P.R. shortly.

**Comment by jwage** [comment]
Awesome! Be sure to include an update to the documentation here https://github.com/doctrine/migrations/blob/master/docs/en/reference/configuration.rst
