### ISSUE TITLE
Notice: Uninitialized string offset 0 in MySqlSchemaManager.php

### ISSUE THREAD

**Issue by fzieris** [doctrine/migrations#785]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0

#### Summary

I work in the context of a Symfony project.
With a recent "composer update", my `doctrine/migrations` package was upgraded from 1.3.2 to 2.0.0.
The current dependency chain is as follows:

```bash
$> composer why -rt doctrine/migrations
doctrine/migrations v2.0.0
└──doctrine/doctrine-migrations-bundle v2.0.0 (requires doctrine/migrations ^2.0)
   └──symfony/orm-pack v1.0.6 (requires doctrine/doctrine-migrations-bundle ^1.3|^2.0)
      └──__root__ (requires symfony/orm-pack ^1.0)
```

When trying to perform any migration-related task (creating a migration, applying a migration, ...), I always see an ErrorException "Uninitialized string offset: 0".
The trace is as follows:

```
In MySqlSchemaManager.php line 223:

  [ErrorException]
  Notice: Uninitialized string offset: 0


Exception trace:
 () at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:223
 Doctrine\DBAL\Schema\MySqlSchemaManager->getMariaDb1027ColumnDefault() at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:169
 Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition() at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:804
 Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList() at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:162  Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns() at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:264
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:291
 Doctrine\DBAL\Schema\MySqlSchemaManager->listTableDetails() at /app/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tracking/TableStatus.php:63
 Doctrine\Migrations\Tracking\TableStatus->isUpToDate() at /app/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tracking/TableManipulator.php:56
 Doctrine\Migrations\Tracking\TableManipulator->createMigrationTable() at /app/vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/Configuration.php:317
 Doctrine\Migrations\Configuration\Configuration->createMigrationTable() at /app/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/AbstractCommand.php:76
 Doctrine\Migrations\Tools\Console\Command\AbstractCommand->initialize() at /app/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:40
 Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->initialize() at /app/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:919
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /app/bin/console:39
```

Although the stacktrace points to `doctrine/dbal`, I'm reporting this behavior here in `doctrine/migrations` since my `doctrine/dbal` version was at the current version 2.9.2 even before this problem occurred.
So I suspect a change in `doctrine/migrations` to be the cause.

#### Previous behavior

Using commands provided by `doctrine/doctrine-migrations-bundle`, such as doctrine:migrations:status worked without any problem.
My migrations classes were all created with executions of doctrine:migrations:diff.

#### Current behavior

Commands provided by doctrine/doctrine-migrations-bundle, such as doctrine:migrations:status fail with the above message/stacktrace.

#### How to reproduce

I am unsure how to go about finding a MWE as the error message is several levels of abstraction below what I am used to work on. Any pointers for circling in on this issue are appreciated.

**Comment by jwage** [comment]
Was the doctrine/dbal dependency updated too? From what version to what?

**Comment by fzieris** [comment]
Nope, `doctrine/dbal` has been at 2.9.2 before and still is.

**Comment by SenseException** [comment]
@fzieris Does your project has any EventListeners that are fired on schema changes like column definitions?

**Comment by fzieris** [comment]
In my own code, I only have event listeners for the following Doctrine ORM lifecycle events (https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#lifecycle-events):

* preRemove
* prePersist
* preUpdate
* postLoad

There might be listeners in my vendor directory. What precisely am I looking for (method or class names, constants, ...)?

**Comment by SenseException** [comment]
`Doctrine\DBAL\Events::onSchemaColumnDefinition` or this constant's string `'onSchemaColumnDefinition'` allows listeners to influence the schema at this point. Do you know which entity and property is responsible for the empty default value?

**Comment by fzieris** [comment]
Quick update: Back in February 2019, I added version `2.0.*` as a conflict in my `composer.json` to circumvent this issue:

```json
"conflict": {
    "doctrine/migrations": "2.0.*"
}
```

After the release of `doctrine/migrations` version 2.1.0 in June, the dependency in my `composer.lock` got upgraded from `1.8.1` to `2.1.0` and the bug reported above did *not* occur.

I therefore close this issue. Thanks to everyone who works on this project!
