### ISSUE TITLE
Generate the same migration for spatial index

### ISSUE THREAD

**Issue by ottaviano** [doctrine/migrations#794]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.0.0

#### Summary

Hi, 
after upgrade from 1.7.2 to 2.0.0 the command `bin/console doctrine:migration:diff` generates always the same migration for spacial index:

```
$this->addSql('DROP INDEX geo_data_geo_shape_idx ON geo_data');
$this->addSql('CREATE SPATIAL INDEX geo_data_geo_shape_idx ON geo_data (geo_shape)');
```

#### Previous behavior

migration:diff -> 0 new migration
migration:migrate -> do nothing
migration:diff -> 0 new migration

#### Current behavior

migration:diff -> generates a new migration with two queries for spatial index.
migration:migrate -> 1 migration executed
migration:diff -> will generate a new migration file with the same two queries.

**Comment by stof** [comment]
have you upgraded Doctrine DBAL too during that update ? The schema comparison is actually performed by DBAL, not by that library.

**Comment by ottaviano** [comment]
@stof yes, I'm on `doctrine/dbal:v2.9.2`. 
should I create an issue in DBAL project instead?

**Comment by stof** [comment]
if the DBAL upgrade caused such a change, please report it to DBAL, yes (with more details about the platform you use and the mapping you have in place)

**Comment by SenseException** [comment]
This might be related to doctrine/dbal#3458

**Comment by alcaeus** [comment]
Yes, looks related. Closing in favour of linked issue.

**Comment by ottaviano** [comment]
Thank you @SenseException, it's related To this issue.
I downgrade to DBAL 2.9.1 and it works well
