### ISSUE TITLE
Unable to run older migrations if newer migration is ran.

### ISSUE THREAD

**Issue by AngelsDustz** [doctrine/migrations#798]
Hello, recently doctrine/symfony made a change that migration versions column can no longer be longer than 14 characters. We used to have a migration called `9999_FooBarJohnDoe`, we had to rename this to `9_FooBar`.

We then ran the migrations and all looked well, except we are no longer able to run ANY migrations, because of an update it now looks at the version column as leading key for any new migrations and since ours starts with 9 it ignores all newly made migrations even those made with `bin/console doctrine:migrations:diff`.

We basically have a dead lock on our database. If this is wrongly place (wrong repo) I apologize in advance.

![image](https://user-images.githubusercontent.com/4640484/54525578-cdd78b80-4974-11e9-8479-e0ebf67048ef.png)

**Comment by jwage** [comment]
In doctrine/migrations 2.0 your version must be an integert/timestamp/date which controls the order of the migrations to execute. The column length can be configured and it defaults to 14. See docs https://www.doctrine-project.org/projects/doctrine-migrations/en/2.0/reference/configuration.html#line-number-4da4819f0081a92d2fc5d96ac9242099e1f8512d-8
