### ISSUE TITLE
ocramius/proxy-manager v2.3.x is now requiring PHP 7.4.x

### ISSUE THREAD

**Issue by simshaun** [doctrine/migrations#800]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.0.0

#### Summary

ocramius/proxy-manager v2.3.x has bumped its PHP constraint to 7.4.0 minimum. 

This repo is still requiring PHP ^7.1, but since the ocramius/proxy-manager constraint is "^2.0.2", it's pulling in 2.3.1 of that lib and failing because we're on PHP 7.2.x.

**Comment by Majkl578** [comment]
Migrations require ProxyManager ^2.0.2, Composer will not install ProxyManager that is incompatible with your PHP so you will get ProxyManager 2.2.x.
