### ISSUE TITLE
Renaming the migrations table

### ISSUE THREAD

**Issue by emodric** [doctrine/migrations#810]
|    Q        |   A
|------------ | -----
| Version     | 2.0

Hi. I have an app that uses Doctrine Migrations for upgrades. My config also has a custom table name for migration versions in order not to collide with other potential migrations from other software running in the same app.

I'd like to rename my migrations versions table due to migrating to new database names. What would be the best way to achieve this? Is there an event I can listen to, to execute the `RENAME TABLE` MySQL command before migrations are executed, or do I have to document for my clients to do it manually?

Thanks!

**Comment by jwage** [comment]
You have to do it manually.

**Comment by emodric** [comment]
Alright, thanks for the answer!
