### ISSUE TITLE
Not work with localhost

### ISSUE THREAD

**Issue by max-save** [doctrine/migrations#811]
Run migration on Max OS Mojave
php 7.1.23
mysql 8.0.15

in db config  host = localhost

try run  vendor/bin/doctrine-migrations migrations:status -v

http://prntscr.com/nayq0z
http://prntscr.com/nayq95

after edit host on 127.0.0.1 always run good.

**Comment by jwage** [comment]
This is an issue with your local database configuration. Not sure exactly what but it is not an issue with doctrine/migrations.
