### ISSUE TITLE
Event `onMigrationsMigrating` triggered twice

### ISSUE THREAD

**Issue by olivermack** [doctrine/migrations#814]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.0.0

#### Summary

The event `onMigrationsMigrating` is currently executed twice in `\Doctrine\Migrations\Migrator::executeMigration()` and I can't figure out why.

#### Current behavior

When you execute the migrations, the migrator is emitting the `onMigrationsMigrating` twice:

https://github.com/doctrine/migrations/blob/2d5c1141e91833ae706d5611cb74c56cdc7a7402/lib/Doctrine/Migrations/Migrator.php#L163
https://github.com/doctrine/migrations/blob/2d5c1141e91833ae706d5611cb74c56cdc7a7402/lib/Doctrine/Migrations/Migrator.php#L174

This causes obviously multiple invokations of any subscriber which is an issue - at least for me ;)

#### How to reproduce

Just execute the migrations. Optionally, add a listener/subscriber for that event and dump its invokations

#### Expected behavior

The event should only be triggered once

**Comment by jwage** [comment]
I believe this is a bug introduced in v2.0.0. I will fix it and release v2.0.2
