### ISSUE TITLE
Connection is not rolled back on dry run

### ISSUE THREAD

**Issue by krmcbride** [doctrine/migrations#82]
In [Version](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Version.php#L294) the connection is committed even during a dry run.  

This isn't an issue for SQL added via `addSQL` (or through `SchemaManager`), which are never executed, however, a reference to the connection is `protected` in `AbstractMigration`, so it's possible to use the connection to do advanced data manipulation: using a PHP function to modify data, for example.  These changes are committed even during a dry run.

It seems that either the `$connection` in `AbstractMigration` should be `private` (a BC break) or the connection should be rolled back.

We use the `protected` connection once in a while to do complex data manipulation.  One could argue that this migration tool should only be used for static SQL, but so far we've found it easiest to pool all DDL, DML and custom transformations in one place.

**Comment by mikeSimonson** [comment]
@krmcbride Can you provide a PR to not commit when in the dry-run case ?

Thanks

**Comment by mikeSimonson** [comment]
@krmcbride In fact after looking at it, I can't imagine a sane way of making a rollback if you touch at the connection.

If you do a DDL most of the case it's going to be autocommited by your DB anyway.
And if you don't then the sane way is for you to start the transaction and then commit it after you have finnished.
```php
$this->connection->beginTransaction();

$this->connection->...your stuff;
$this->connection->commit();
```
