### ISSUE TITLE
doctrine:migrations:diff with column type datetimetz produce same migration for every command run

### ISSUE THREAD

**Issue by scion4581** [doctrine/migrations#835]
version 1.2.1

Having column type like below datetimetz
```  
/**
 * Class TestBug
 * @package AppBundle\Entity
 * @ORM\Entity()
 */
class TestBug
{
...................
  /**
     * @ORM\Column(type="datetimetz")
     */
    private $uploadedAt;
.................
```
always produce new migrations file after doctrine:migrations:diff

`$this->addSql('ALTER TABLE test_bug CHANGE uploaded_at uploaded_at DATETIME NOT NULL');`

And you have many same migrations file but you field doesnt change 

To fix this you must set format like just 'datetime'. Unfortunately, I cant do this cause some legacy entity in vendor has this type of field, so i cant override it...

**Comment by jwage** [comment]
This is quite an old version. Is it still the same problem on the latest supported versions of dbal and migrations?

**Comment by stof** [comment]
Why platform are you using ?

**Comment by scion4581** [comment]
I forked project and change data type to simple datetime.
Unfortunately I have no time to invistigate for now...

**Comment by Cartman34** [comment]
This is happening on every datetimetz field using MariaDB version 10.3.31-MariaDB-0ubuntu0.20.04.1.
