### ISSUE TITLE
Executor::SkipMigration Connection Rollback causes ConnectionException

### ISSUE THREAD

**Issue by fyrye** [doctrine/migrations#838]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.1.0

#### Summary

Skipped Migrations cause the connection to be put in a rollback state and then throws an exception when it attempts to update the migration version afterwards.

#### Current behavior

When running `migrations:execute` or `migrations:migrate` and `skipIf` is used, the migration transaction is rolled back, then the version is attempted to be updated in a rollback state, resulting in a thrown `ConnectionException`.

#### How to reproduce

```php
//Version201901.php

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version201901 extends AbstractMigration
{
    public function isTransactional(): bool
    {
         return true;
    }

     public function up(Schema $schema)
     {
          $this->skipIf(true, 'TESTING');
     }

     public function down(Schema $schema)
     {
          $this->skipIf(true, 'TESTING');
     }
}
```

```php
//Version201902.php

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version201902 extends AbstractMigration
{
     public function up(Schema $schema)
     {
          $this->addSql('SELECT 1');
     }

     public function down(Schema $schema)
     {
          $this->addSql('SELECT 1');
     }
}
```

```bash
$ ./vendor/bin/doctrine-migrations migrate

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 201902 from 201900

  ++ migrating 201901


  SS skipped (Reason: TESTING)

  ++ migrating 201902


     -> SELECT 1

  ++ migrated (took 3.7ms, used 26M memory)
Migration 201902 failed during Post-Checks. Error Transaction commit failed because the transaction has been marked for rollback only.

In ConnectionException.php line 12:
                                                                                        
  Transaction commit failed because the transaction has been marked for rollback only. 

```

#### Expected behavior

Skip is expected to be somewhat benign, allowing the migration to be gracefully reverted and other migrations in the chain to be processed. 

So `Version201901` migration should be skipped and then continue with the `Version201902` migration being successful.

The issue appears to be caused by [`Doctrine\Migrations\Version\Executor::skipMigration`](https://github.com/doctrine/migrations/blob/2.1/lib/Doctrine/Migrations/Version/Executor.php#L289)

```php
    private function skipMigration(
        SkipMigration $e,
        Version $version,
        AbstractMigration $migration,
        string $direction,
        MigratorConfiguration $migratorConfiguration
    ) : void {
        if ($migration->isTransactional()) {
            //only rollback transaction if in transactional mode
            $this->connection->rollBack();
        }

        if (! $migratorConfiguration->isDryRun()) {
            //attempt to create the migrations table and insert/delete the version number
            $version->markVersion($direction);
            //since the connection is in a rollback state, this fails.
        }
        //...
    }
```
It appears the connection needs to be reestablished prior to calling [`$version->markVersion($direction)`](https://github.com/doctrine/migrations/blob/2.1/lib/Doctrine/Migrations/Version/Version.php#L198). Although I am also unsure as to why it is there, since this could result in a false flag, since the migration is intended to be "skipped", it would technically not be migrated in either direction.

**Comment by Avd6977** [comment]
Any update on this? Still seeing it happen

**Comment by ammadfa** [comment]
any update?

**Comment by fyrye** [comment]
It has been a few years since I added the issue, so doubt it will be resolved in 2.x. 

With version 3.5.x, it seems the issue is no longer valid, as a message was added when the transaction is in a rollback state and prompts with a message to override it in `AbstractMigration::isTransactional()`.
https://github.com/doctrine/migrations/blob/3.5.x/lib/Doctrine/Migrations/Tools/TransactionHelper.php#L42
