### ISSUE TITLE
Doesn't work for oracle

### ISSUE THREAD

**Issue by Princelo** [doctrine/migrations#847]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.1.1

#### Summary
there is a bug executing a migration for oracle:

In AbstractOracleDriver.php line 57:

  An exception occurred while executing 'INSERT INTO doctrine_migration_versions (version, executed_at) VALUES (?, ?)' with params ["00001", "2019-0
  8-09 03:15:55"]:

  SQLSTATE[HY000]: General error: 1843 OCIStmtExecute: ORA-01843: not a valid month
   (/tmp/pdo_oci/oci_statement.c:157)

**Comment by l3l0** [comment]
You can try to configure NLS_DATE_FORMAT or something.
For me something like that worked:

```php
    public function preUp(Schema $schema): void
    {
        parent::preUp($schema);

        $this->addSql("ALTER session SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM'");
    }

```

**Comment by Princelo** [comment]
> You can try to configure NLS_DATE_FORMAT or something.
> For me something like that worked:
> 
> ```
>     public function preUp(Schema $schema): void
>     {
>         parent::preUp($schema);
> 
>         $this->addSql("ALTER session SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM'");
>     }
> ```

thanks！

**Comment by lcobucci** [comment]
Closing here as per @l3l0's comment.
