### ISSUE TITLE
Critical Error [v0.10.8]

### ISSUE THREAD

**Issue by taurussoft** [doctrine/migrations#850]
### Bug Report

My PHP version is 7.1

After installation last version I get some error message:

`php vendor/bin/phinx 
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /var/www/html/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /var/www/html/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /var/www/html/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /var/www/html/vendor/robmorgan/phinx/bin/phinx(27): require('/var/www/html/v...')
#5 {main}
  thrown in /var/www/html/vendor/symfony/console/Command/Command.php on line 453`

**Comment by lcobucci** [comment]
@taurussoft it looks like you opened this in the wrong repository. Perhaps you meant https://github.com/cakephp/phinx?

**Comment by lcobucci** [comment]
I'll be closing this one as invalid since it isn't related to doctrine migrations.

**Comment by taurussoft** [comment]
Oh! Sorry.
Yes, it is.
