### ISSUE TITLE
Migration dependencies

### ISSUE THREAD

**Issue by goetas** [doctrine/migrations#853]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | ?? (hopefully no)

#### Summary

Hi, 
I'm working on an application that has some kind of plugins. Each plugin can have dependencies with other plugins. Each plugin has its-own set of tables, (and migrations).
Tables have foreign keys to other tables  (created by plugins on which the current plugin depends).

This scenario requires to load migrations from multiple paths, and to have a different execution order from the current default migrations sorting and the possibility to load migrations from multiple folders.

From what I could see, this is not yet supported by doctrine migrations. I'm planning to work on something to implement this kind of feature.
The idea is to introduce an interface `MigrationsSorter` used as migration sorting strategy. The default implementation will use the current sorting algorithm, but it will be possible to provide different sorting mechanism.

Is something as this interesting for this project?

**Comment by alcaeus** [comment]
> Is something as this interesting for this project?

Absolutely. I needed something like this myself when working on an application that uses Sylius. We needed to run all migrations from Sylius but also add our own migrations, which wasn't possible by default. The only way we achieved this was by symlinking the Sylius migrations and making sure that our migrations use the same namespace as Sylius migrations, which was hacky to say the least.

I'm not sure what we need to do to fully support this, but I think loading migrations from other packages (like we load mappings for our object managers) would definitely be a great improvement for this library!

**Comment by goetas** [comment]
great to hear that! As soon as I have a more clear road map, will give you an update

**Comment by goetas** [comment]
Started to work on this in https://github.com/doctrine/migrations/pull/855

**Comment by slince** [comment]
Hello, I'm having a similar problem. I'm trying to extend these classes myself, but the dependencies seem too complex; Many of the properties are private, which is so hard to extend that I have to re-inherit almost all the classes. Is there any plan to re-implement this?

**Comment by goetas** [comment]
See https://github.com/doctrine/migrations/pull/858

**Comment by goetas** [comment]
Fixed in https://github.com/doctrine/migrations/pull/858
