### ISSUE TITLE
Casting Versions to int leads to errors on 32 bit architecture

### ISSUE THREAD

**Issue by inceddy** [doctrine/migrations#863]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.y.z

#### Summary

Version _from_ and _to_ is casted to `int` to distinguish migration [direction](https://github.com/doctrine/migrations/blob/50c7d160c249b9acbc25090a6a8eb2ee8f66e959/lib/Doctrine/Migrations/Migrator.php#L245) and to [decide](https://github.com/doctrine/migrations/blob/5650e82955d8c4f2bbb5e46222844feea331c8ab/lib/Doctrine/Migrations/MigrationPlanCalculator.php#L57) (and folloing lines) which migrations to execute. This leads to errors on 32 bit architecture where integer size is limited to 2147483647.

#### Current behavior

All migration versions are rounded to 2147483647 and are not comparable anymore.

#### How to reproduce

Use migrations on a 32 bit system.

#### Expected behavior

Cast to `float` instead to fix this bug.

**Comment by alcaeus** [comment]
See #854.

**Comment by stof** [comment]
Closing as duplicate
