### ISSUE TITLE
Unable to change primary key in a single migration for Sql Server

### ISSUE THREAD

**Issue by akrabat** [doctrine/migrations#871]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | `1.8.1` and `2.2.0`

#### Summary

With Sql Server, you cannot drop a table's primary key and set a new one in the same migration. Using two consecutive migrations works though.

#### Current behavior / How to reproduce

Given this migration:

```php
final class Version20191023125629 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->dropPrimaryKey();
        $table->setPrimaryKey(['page_uuid', 'category_id']);
    }

    public function down(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->dropPrimaryKey();
        $table->setPrimaryKey(['page_id', 'category_id']);
    }
}
```

Running the `migrate` command gives this error:

```
 ++ migrating 20191023125629

     -> IF EXISTS (SELECT * FROM sysobjects WHERE name = '[primary]')
    ALTER TABLE page_category DROP CONSTRAINT [primary]
ELSE
    DROP INDEX [primary] ON page_category
Migration 20191023125629 failed during Execution. Error An exception occurred while executing 'IF EXISTS (SELECT * FROM sysobjects WHERE name = '[primary]')
    ALTER TABLE page_category DROP CONSTRAINT [primary]
ELSE
    DROP INDEX [primary] ON page_category':

SQLSTATE[42S02]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot drop the index 'page_category.primary', because it does not exist or you do not have permission.
```

Note that the `name` of the index it is trying to drop is called `[primary]` when it should be `[PK__page_cat__E48D0CA0589C25F3]`.

#### Expected behavior

Changing to two consecutive migrations works:

```php
final class Version20191023125629 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->dropPrimaryKey();
    }

    public function down(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->setPrimaryKey(['page_id', 'category_id']);
    }
}
```

and

```php
final class Version20191023125630 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->setPrimaryKey(['page_uuid', 'category_id']);
    }

    public function down(Schema $schema) : void
    {
        $table = $schema->getTable('page_category');
        $table->dropPrimaryKey();
    }
}
```

Works as expected:

```
  ++ migrating 20191023125629

     -> IF EXISTS (SELECT * FROM sysobjects WHERE name = 'PK__page_cat__E48D0CA0589C25F3')
    ALTER TABLE page_category DROP CONSTRAINT PK__page_cat__E48D0CA0589C25F3
ELSE
    DROP INDEX PK__page_cat__E48D0CA0589C25F3 ON page_category

  ++ migrated (0.77s)

  ++ migrating 20191023125630

     -> ALTER TABLE page_category ADD PRIMARY KEY (page_uuid, choice_key_name)

  ++ migrated (0.77s)
```

**Comment by stof** [comment]
As you are using the Doctrine DBAL schema tool to perform the changes (and letting DBAL generate the SQL on the fly), this should be reported to doctrine/dbal.

As a side note, using the Schema object to perform the migrations has several drawbacks:

- it forbids you to perform any data migrations (making these migrations unsafe to run on a non-empty database, and potentially impossible to run on non-empty databases depending on the changes and the platform, for instance adding a non-nullable field on Postgresql)
- it forbids you to review the SQL being used (as it is generated on the fly)
- it forbids you to control the SQL generated (which is actually one of the reasons for the first point)
- it is a lot slower when you have many migrations being executed as doctrine/migrations needs to introspect the schema again before each migration using the Schema object (in the past, the schema was always introspecting, and changing it to be done lazily allowed to have things like 99% speed-ups on projects with a few hundred migrations)

**Comment by akrabat** [comment]
Raised on doctrine/migrations as [Issue 3736](https://github.com/doctrine/dbal/issues/3736).
