### ISSUE TITLE
[2.2.0] No migration generated after added a new field

### ISSUE THREAD

**Issue by PastisD** [doctrine/migrations#873]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.2.0

#### Summary

After upgrading to 2.2.0, no migration are generated. The command `php bin/console doctrine:migrations:diff` return `No changes detected in your mapping information.`

I had to rollback to 2.1.2 to generate migration file.

#### Behavior

With 2.2.0 :
![image](https://user-images.githubusercontent.com/442023/69419824-98621980-0d1d-11ea-8de2-4882d40ff882.png)

With 2.1.2 :
![image](https://user-images.githubusercontent.com/442023/69419798-884a3a00-0d1d-11ea-8938-493e371337d4.png)

#### How to reproduce

I just added a new simple field

```php
    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $yousignSignatureUiId;
```

EDIT :
I just saw that `doctrine/doctrine-migrations-bundle` was also downgraded to 2.0.0. 
Maybe the problem is in the bundle but i didn't saw any issue on it about that either

**Comment by Sander-hub** [comment]
I am facing a similar issue on version 2.2.0. I don't get the 'no changes detected' warning, but the 'up' function stays empty after adding a column and followed by make:migration. I can workaround by clearing the cache before making the migration: doctrine:cache:clear-metadata. Then the migration does populate the up function. My setup is just a brand new symfony 5 skeleton project, orm-pack and mssql configured.

Regarding not getting the 'no changes detected' warning in my situation: I suspect there is a second issue in my setup that causes migrations to see changes, although there aren't. In each migration the 'down' function is populated with 10 'CREATE SCHEMA' entries. Hence migrations will never show the warning.

Running on docker ubuntu php73, docker ubuntu sqlserver 2017.

**Comment by alcaeus** [comment]
I suspect this is due to https://github.com/doctrine/DoctrineBundle/issues/1069. Can you please try to clear the cache before generating a migration with 2.2.0? Thanks!

**Comment by djmetla** [comment]
I have same issue :( any solution for fix this? I try cache:clear, but still issue.

**Comment by sanhup** [comment]
> I have same issue :( any solution for fix this? I try cache:clear, but still issue.

Can you try doctrine:cache:clear-metadata instead of cache:clear? That works for me.

**Comment by dmaicher** [comment]
New patch release for DoctrineBundle should fix this issue. Can you confirm?

**Comment by sanhup** [comment]
Yes! I installed the patch and now it works as expected. Thank you!

**Comment by alcaeus** [comment]
Good to know. Thanks!
