### ISSUE TITLE
Migration failed during Pre-Checks

### ISSUE THREAD

**Issue by prettykingking** [doctrine/migrations#895]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.2

#### Summary

When run migrate command from CLI, the migration failed during Pre-Checks with the following error message.

`Failed opening script ProxyManagerGeneratedProxy///PM///Doctrine/DBAL/Schema/Schema/Generated1838957e13fce5f54efb7a1f10bc2e1d.php: No such file or directory`

I checked the path and the file actually does not exist. It's very strange, as it's the first time to migration the database connection is success.

**Comment by SenseException** [comment]
If you still are running into this issue, can you please provide more information about it (e.g. reproducable example)? Did your migrations work before or is this your first one?

**Comment by prettykingking** [comment]
Sorry, It's my fault. It's caused by my custom class autoloader. Finally I fixed this error.
