### ISSUE TITLE
Can't update symfony4 using composer 

### ISSUE THREAD

**Issue by MaryanShvets** [doctrine/migrations#905]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.2.0

#### Summary

Can't update symfony4 using composer

after executing  "composer update"
I see

Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.

#### Current behavior
in composer.json now is included "ocramius/proxy-manager": "^2.0.2",
but according https://www.zend.com/blog/what-status-zend-framework-transition-laminas
Package zendframework is abandoned, and should avoid using it. Use laminas

it was fixed in Ocramius/ProxyManager  "ocramius/proxy-manager": "^2.6.0"

please use in composer.json "ocramius/proxy-manager": "^2.6.0"

**Comment by stof** [comment]
AFAIK, these are just composer warnings. They will not make the update fail. So please provide more details about why you cannot updated.

And the current constraint in Symfony package *already* allows installing ocramius/proxy-manager 2.6.0. But Composer will select that version only if you run on PHP 7.4 (as that's the requirement of that version).
Making 2.6.0 our minimum requirement will actually be the change breaking things (as it would become impossible to install Symfony on PHP 7.2 or 7.3).

**Comment by alcaeus** [comment]
Closing here - this is not an issue to be fixed here.
