### ISSUE TITLE
Switch to PSR-4

### ISSUE THREAD

**Issue by goetas** [doctrine/migrations#909]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | - (only for master)

#### Summary

Switch to the more recent PSR-4 autoload standard

**Comment by lcobucci** [comment]
This is a no go for any doctrine package, as decided in the past.

**Comment by alcaeus** [comment]
I feel the issue can at least be discussed. No need to close it outright.

**Comment by goetas** [comment]
ORM seems using it, see https://github.com/doctrine/orm/blob/ff65cae17083266c43f091fff03289197db9e4fb/composer.json#L60

**Comment by lcobucci** [comment]
In the same way as this lib https://github.com/doctrine/migrations/blob/master/composer.json#L42

**Comment by goetas** [comment]
nmm, i see.

**Comment by goetas** [comment]
I think that we can keep it as it is
