### ISSUE TITLE
Update ocramius/proxy-manager

### ISSUE THREAD

**Issue by simivar** [doctrine/migrations#921]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

#### Summary
Zend Framework has been moved from *zendframework* namespace to *laminas* namespace. Doctrine Migrations is setto depend on `ocramius/proxy-manager` version `2.0.2` which dependencies are in old namespace. Because of that we get:
```
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
```

`ocramius/proxy-manager` uses new namespace in `2.6`. Is there a specific reason why it's set strictly to version `^2.0.2` and not `^2.0`?

CC @Ocramius as you are an author of library and you are in both Doctrine and Laminas organizations.

**Comment by greg0ire** [comment]
`^2.0.2` has the same effect as `^2.0` (but not the same as `~2.0.2`) IIRC. Are you sure this constraint is the reason you can't upgrade? Use `composer why-not` to make sure.

**Comment by simivar** [comment]
You are right, my bad. Sorry.

**Comment by tacman** [comment]
I'm no expert at this, just wondering if I can get rid of the warning.  

```bash
composer why zendframework/zend-code
ocramius/proxy-manager  2.2.3  requires  zendframework/zend-code (^3.3.0)  


composer why ocramius/proxy-manager
doctrine/migrations  2.2.1  requires  ocramius/proxy-manager (^2.0.2)  
```

https://github.com/doctrine/migrations/blob/master/composer.json#L18

        "ocramius/proxy-manager": "^2.0.2",

I imagine this will eventually go away during some update, but wondering if there's a way to get a version that doesn't give the warning.  Not urgent at all, but those warning messages can be distracting.  Thanks.

**Comment by Ocramius** [comment]
`ocramius/proxy-manager` is already on `laminas/laminas-code` since `2.6.0`.

**Comment by alcaeus** [comment]
@tacman `composer why-not ocramius/proxy-manager 2.6.0`. You're most likely running an older PHP version which is no longer supported by proxy manager. Our constraint (`^2.0.2`) allows installing 2.6.0 if your platform supports it.
