### ISSUE TITLE
Display a warning if running diff command with previous non-executed migrations

### ISSUE THREAD

**Issue by VincentLanglet** [doctrine/migrations#930]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Related to https://github.com/doctrine/DoctrineMigrationsBundle/issues/177

Running the diff command should display a warning if not in sync with the current migrations is welcome.

**Comment by goetas** [comment]
sounds a good idea.

**Comment by goetas** [comment]
Are you interested in implementing this feature?

**Comment by VincentLanglet** [comment]
@goetas Why not, but I don't know the project so If you know where I should look at, I take it.

**Comment by goetas** [comment]
done in https://github.com/doctrine/migrations/pull/948
