### ISSUE TITLE
Is there a way to execute a migration programatically?

### ISSUE THREAD

**Issue by RoqueCampos** [doctrine/migrations#943]
Dear Friends,

I really need to be able to trigger a migration programmatically, without using the shell_exec or the exec php functions.

Is there a way to call the method "up" from a Versionxxxx.php class programmatically?  The class needs an instance of the Doctrine\Migrations\Version class passed in the constructor, but I don't know the meaning of the different parameters of the version class.

Maybe you have a sample of how this can be done?

Thanks in advance.

**Comment by andrew-demb** [comment]
You can check current logic implemented in console command and adapt it for your case.
https://github.com/doctrine/migrations/blob/master/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php

**Comment by goetas** [comment]
Using the latest master, you can do:

```php

$di = $this->getDependencyFactory(); // retrive somehow the DI factory

$planCalculator = $di->getMigrationPlanCalculator();
$plan = $planCalculator->getPlanForVersions([new Version('your version')], Direction::UP);

$migratorConfiguration = new MigratorConfiguration();
$di->getMigrator()->migrate($plan, $migratorConfiguration);
```

**Comment by RoqueCampos** [comment]
Thank you for pointing me in the right direction. Finally, I looked at the source code of the MigrationCommand, and with the guidelines from goetas, I used the following snippet to trigger the migration:

`$configuration = new Configuration( $this->em->getConnection() );

		$migrationsConfig        = json_decode( file_get_contents( $pathToConfigurationFile ) );

		$configuration->setName( $migrationsConfig->name );
		$configuration->setMigrationsNamespace( $migrationsConfig->migrations_namespace );
		$configuration->setMigrationsTableName( $migrationsConfig->table_name );
		$configuration->setMigrationsColumnName( $migrationsConfig->column_name );
		$configuration->setMigrationsColumnLength( $migrationsConfig->column_length );
		$configuration->setMigrationsExecutedAtColumnName( $migrationsConfig->executed_at_column_name );
		$configuration->setMigrationsDirectory( $plugin_dir_path . '/' . $migrationsConfig->migrations_directory );
		$configuration->setAllOrNothing( $migrationsConfig->all_or_nothing );
		$configuration->setCheckDatabasePlatform( $migrationsConfig->check_database_platform );

		/** @var DependencyFactory $di */
		$di = $configuration->getDependencyFactory();
		$di->getMigrator()->migrate();`

**Comment by dmeehan1968** [comment]
The API has changed since the last comment, and I ended up creating the following based on `MigrateCommand::execute()`.  First pass and might be a bit simplistic.

```
$config = new PhpFile(join(DIRECTORY_SEPARATOR, [$_SERVER['PWD'], 'migrations.php']));
$loader = new ExistingEntityManager(self::$entityManager);
$dependencyFactory = DependencyFactory::fromEntityManager($config, $loader); // or use ::fromConnection()

$version = $dependencyFactory->getVersionAliasResolver()->resolveVersionAlias('latest');
$planCalculator = $dependencyFactory->getMigrationPlanCalculator();
$plan = $planCalculator->getPlanUntilVersion($version);
$migrator = $dependencyFactory->getMigrator();
$migratorConfigurationFactory = $dependencyFactory->getConsoleInputMigratorConfigurationFactory();
$migratorConfiguration = $migratorConfigurationFactory->getMigratorConfiguration(new ArrayInput([]));

$sql = $migrator->migrate($plan, $migratorConfiguration);
// not sure that you'd so with the resulting $sql
```

**Comment by sebastianstucke87** [comment]
In case you get this error `The metadata storage is not initialized, please run the sync-metadata-storage command to fix this issue.` you have to `$dependencyFactory->getMetadataStorage()->ensureInitialized()`.

(As stated above, this is based on `\Doctrine\Migrations\Tools\Console\Command\MigrateCommand::execute`)

Cheers!

**Comment by 11k** [comment]
You can also simply create an instance of and run `MigrateCommand` directly.

```
use Doctrine\DBAL\DriverManager;
use Doctrine\Migrations\Configuration\Connection\ExistingConnection;
use Doctrine\Migrations\Configuration\Migration\PhpFile;
use Doctrine\Migrations\DependencyFactory;
use Doctrine\Migrations\Tools\Console\Command\MigrateCommand;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;

$migrationsConfigFile = '...';
$connectionParameters = ['...'];

$dependencyFactory = DependencyFactory::fromConnection(
    new PhpFile($migrationsConfigFile),
    new ExistingConnection(
        DriverManager::getConnection($connectionParameters)
    ),
);
$dependencyFactory->getMetadataStorage()->ensureInitialized();

$input = new ArrayInput([]);
$input->setInteractive(false);

$command = new MigrateCommand($dependencyFactory);
$command->run($input, new NullOutput());
```

**Comment by Luc-cpl** [comment]
In my case I use a DI container setted with Symfony Console and with a doctrine provider doing the configuration part, so I just need to call:

```
$input = new ArrayInput(['command' => 'migrations:migrate']);
$input->setInteractive(false);
$this->app->get(Application::class)->doRun($input, new NullOutput());
```
