### ISSUE TITLE
[Index] Function-based index

### ISSUE THREAD

**Issue by Guikingone** [doctrine/migrations#947]
|    Q        |   A
|------------ | -----
| Version     | 2.0 (bundle)

### Support Question

Hi 👋 

Small question about function-based index, is there any way to tell Doctrine to *not* regenerate the index once it's been added to the database? 

Here's the case I'm facing: 

I've a simple migration where I add this index: 

```yaml
    public function up(Schema $schema) : void
    {
        $this->addSql('CREATE INDEX test_autocomplete ON test (LOWER(name))');
    }
```

The idea is to add a function-based index which use the "lowered" version of the column `name` (for autocompletion purpose), the index name is correctly set on the entity and the migration is correctly executed but when I try to generate a new migration (with new schema updates), this index is generated once again (without the lower func), it seems that Doctrine doesn't like this type of index, is there any workaround? 🤔 

Thanks for the help and have a great day 🙂

**Comment by SenseException** [comment]
@Guikingone On which RDBMS does this happen?

This looks probably like a DBAL issue. (@goetas)

**Comment by Guikingone** [comment]
@SenseException Hi 👋 

This happen on Postgresql 🙂

**Comment by goetas** [comment]
this is something that i was already aware. DBAL does not understand functional indexes (also because each RDBMS implements in a different way).
And I personally thing is not worth for DBAL to try to support it...

Do you have the `test_autocomplete` defined also as doctrine metadata?

**Comment by SieGeL2k16** [comment]
Hi,

I've just faced the same problem, and I've added the unique index as doctrine metadata:

`@ORM\Table(name="building", uniqueConstraints{@ORM\UniqueConstraint(name="uidx_building_name", columns={"name"})})
`
and manually added the "lower(name)" to the resulting migration file.
Whenever I've create a new migration file via symfony, the unique index is always dumped out again.

Maybe it is better to avoid adding Doctrine metadata for these unique functional indexes and simply add them manually to the migration file instead?

**Comment by Guikingone** [comment]
@goetas The `test_autocomplete` is not defined as metadata (which can explain the fact that Doctrine tries to generate it every time?)

@SieGeL2k16 I think that's the solution, as @goetas suggest it, that's probably not needed in the DBAL (even if it could be useful, that's not a mandatory feature).

**Comment by goetas** [comment]
@SieGeL2k16 
> Maybe it is better to avoid adding Doctrine metadata for these unique functional indexes and simply add them manually to the migration file instead?

This is how I do it in my projects

**Comment by anaelChardan** [comment]
@goetas That's what I wanted to do but how do you deal with empty column name when doing a schema:drop or a schema:update ? ;)

**Comment by goetas** [comment]
Hmm maybe because i'm using postgres (that had functional indexes for years) and in the prostgres driver this was already handled? (pure guessing here)

**Comment by goetas** [comment]
But anyway I'm closing this as it is a DBAL issue.
