### ISSUE TITLE
Fields with a default value are erroneously marked as changed by migrations:diff

### ISSUE THREAD

**Issue by psrpinto** [doctrine/migrations#95]
When a field has a default value defined by `options={"default" = 0}`, `migrations:diff` always marks the field as changed, thus generating a migration with unneeded statements.

**How to reproduce**

Create an entity as follows:

```
/**
 * @ORM\Table(name="dummy")
 * @ORM\Entity
 */
class DummyIdentity
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     */
    private $id;

    /**
     * @ORM\Column(type="integer", options={"default" = 0})
     */
    private $dummy;
}
```
1. Generate a migration with `doctrine:migrations:diff`
2. Run the generated migration with `doctrine:migrations:migrate`
3. Run `doctrine:migrations:diff` again

The migration generated by 3. will have a statement to change the `dummy` field, even though it wasn't changed:

```
ALTER TABLE dummy CHANGE dummy dummy INT DEFAULT 0 NOT NULL"
```

**Comment by maciek-kemnitz** [comment]
The same is now happening for fields that are marked as nullable = true

` $this->addSql('ALTER TABLE user CHANGE password password VARCHAR(255) NOT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT NULL, CHANGE facebook_id facebook_id VARCHAR(32) DEFAULT NULL, CHANGE facebookAccessToken facebookAccessToken VARCHAR(100) DEFAULT NULL, CHANGE activatedAt activatedAt DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL, CHANGE updatedAt updatedAt DATETIME DEFAULT NULL, CHANGE loginToken loginToken VARCHAR(255) DEFAULT NULL');
`
![mysql 5 5 5-10 2 7-mariadb slowhop_dev-slowhop_dev-user 2017-07-26 13-01-37](https://user-images.githubusercontent.com/1951694/28617933-aa77d780-7202-11e7-8d63-01b553961b5c.png)

**Comment by stof** [comment]
@maciek-kemnitz the SQL queries themselves are not generated by doctrine/migrations but by doctrine DBAL

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.
