### ISSUE TITLE
MySQL/MariaDB Trigger Syntax

### ISSUE THREAD

**Issue by Cahdek** [doctrine/migrations#951]
|    Q        |   A
|------------ | -----
| Version     | 1.5

### Support Question

I'm having trouble with syntax for creating a trigger in MariaDB. This is a trimmed version of the commands:

$this->addSql('DELIMITER $$');

$this->addSql('CREATE TRIGGER <triggerName> BEFORE INSERT ON <table> FOR EACH ROW BEGIN SET NEW.id = <something>; END$$');

$this->addSql('DELIMITER ;');

This results in:
Migration 20200325222506 failed during Execution. Error An exception occurred while executing 'DELIMITER $$':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$' at line 1

**Comment by Cahdek** [comment]
Cancel that I found the answer using Life Cycle Events.. For those curious, here is the solution:

https://stackoverflow.com/questions/18377690/how-to-handle-sql-triggers-in-symfony2#answer-18390089

**Comment by goetas** [comment]
I believe you have to put them as a single SQL statement.

```php
$this->addSql('DELIMITER $$
CREATE TRIGGER BEFORE INSERT ON
   FOR EACH ROW BEGIN SET NEW.id = ; END$$
DELIMITER ;');
```

**Comment by brianmerz** [comment]
FYI, I recently ran into this issue. It turns out you don't need the `DELIMITER` statements at all, just put the whole `CREATE TRIGGER` statement into an `addSql` call using the semi-colons and it you won't get a syntax error and it will create the trigger.
