### ISSUE TITLE
StatusCommand --show-versions option

### ISSUE THREAD

**Issue by dmaicher** [doctrine/migrations#955]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.0-alpha1

#### Summary

I saw this in the Upgrade file

> The --show-versions option from migrations:status command has been removed, use migrations:list instead.

The option is still defined though:
https://github.com/doctrine/migrations/blob/3.0.0-alpha1/lib/Doctrine/Migrations/Tools/Console/Command/StatusCommand.php#L26

This is a bit confusing since it does not do anything currently

#### Expected behavior

Remove the option completely?

**Comment by SenseException** [comment]
> Remove the option completely?

I guess so. This might need deprecations in the earlier versions too, right?

**Comment by dmaicher** [comment]
@SenseException deprecating it in 2.x would mean that we need to add the new command there already, or?
Otherwise its a deprecation that one cannot get rid of until upgrading to 3.x

**Comment by goetas** [comment]
There is a note about the removal of the parameter in the upgrading notes https://github.com/doctrine/migrations/blob/master/UPGRADE.md#console

**Comment by goetas** [comment]
Not all the features present in 3.x are also available as forward compatibile in 2.x. This is one example where the list command is not available in 2.x

**Comment by goetas** [comment]
Forward compatibility is nice to have, but with the current time limits, I don't have the time to implement everything in 2.x too

**Comment by halfpastfouram** [comment]
Documentation still mentions the `--show-versions` parameter: https://www.doctrine-project.org/projects/doctrine-migrations/en/3.2/reference/managing-migrations.html#managing-migrations

**Comment by rolandinsh** [comment]
Still in 3.7: `./vendor/bin/doctrine-migrations status --show-versions` https://www.doctrine-project.org/projects/doctrine-migrations/en/3.7/reference/managing-migrations.html
