### ISSUE TITLE
"Specified key was too long; max key length is 767 bytes" - for version column in doctrine_migration_versions as PRIMARY key

### ISSUE THREAD

**Issue by kfrankiewicz** [doctrine/migrations#958]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0-alpha1

#### Summary

I use MariaDB 10.1.41, but it may happen with MySQL as well. With default configuration, when I'm running `d:m:migrate` for the first time and doctrine migration tries to create its core table in the database, I get an error:

```
An exception occurred while executing 'CREATE TABLE doctrine_migration_versions (version VARCHAR(1024) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INT DEFAULT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB':                   
                                                                                                                                                     
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

In the definition we have `version VARCHAR(1024)`, and then `PRIMARY KEY(version))`, so the version column is too long to be the primary key.

#### Current behavior

Error in the console as described above.

#### How to reproduce

In the console:
```
composer create-project symfony/website-skeleton docmig_version_issue
cd docmig_version_issue
composer require doctrine/doctrine-migrations-bundle:3.0.0-alpha.1 doctrine/migrations:3.0.0-alpha1
touch ./src/Entity/MyEntity.php
```

Update config in ./config/packages/doctrine_migrations.yaml to:
```
doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/Migrations'
```

Create a database, update ./.env.local with the path to database:
`DATABASE_URL=mysql://user:password@127.0.0.1:3306/database?serverVersion=10.1`
The version above doesn't matter - tried with 5.5, 5.7 and 10.1.
        
Update file ./src/Entity/MyEntity.php to:
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table
 */
class MyEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

In the console run:
```
php bin/console d:m:diff
php bin/console d:m:migrate -n
```

The error should be printed in the console.

#### Expected behavior

No error and the table should be created correctly.

**Comment by goetas** [comment]
Thanks for trying the alpha version. 

Fixed in https://github.com/doctrine/migrations/pull/960
