### ISSUE TITLE
Change the URL link to this project on GitHub

### ISSUE THREAD

**Issue by michaelperrin** [doctrine/migrations#96]
This project's Github page (https://github.com/doctrine/migrations) links to the http://www.doctrine-project.org/extension/migrations page which doesn't exist anymore.

Change it to http://www.doctrine-project.org/projects/migrations.html .

Easy but nice :)

**Comment by mikeSimonson** [comment]
@Ocramius This is the issue that needs the admin right to be corrected.
The url is highlighted in the image.
![url](https://cloud.githubusercontent.com/assets/907613/6204894/8a86a026-b55a-11e4-81a4-5b555dfa6ed0.png)

**Comment by Ocramius** [comment]
Done :-)

**Comment by TomasVotruba** [comment]
@Ocramius Awesome! Thanks a lot!
