### ISSUE TITLE
Show current version with the command line

### ISSUE THREAD

**Issue by loverg-c** [doctrine/migrations#961]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hello,

It will be nice to have a command for showing current version like the latest command

**Comment by goetas** [comment]
Isn't that available via status command?

**Comment by goetas** [comment]
In alternative it could be a added on the 'up-to-date' command

**Comment by goetas** [comment]
Fixed in https://github.com/doctrine/migrations/pull/965

**Comment by loverg-c** [comment]
Sorry for the late answer, yes actually I do (with symfony console)

`bin/console doctrine:migrations:status | sed -n 's/.*Current Version:.*(//p' | cut -d ')' -f 1`

But a specific command from the bundle is so much better :)
