### ISSUE TITLE
[3.0-alpha] Seamless 2.0 -> 3.0 upgrade, keeping migration versions data

### ISSUE THREAD

**Issue by pamil** [doctrine/migrations#967]
Is there a recommended way to upgrade an existing application to use Migrations 3.0 and not lose migration versions data?

Ideally, after updating the package versions and adjusting the configuration, Migrations 3.0 would know which migrations have already been applied by Migrations 2.0.

My ideas:

1) An extension point to transform previous migration versions to the new format. For example, I could define that `20170101235959` is now `Sylius\CoreBundle\Migrations\Version20170101235959` and it would execute before actually running the migrations.

2) More of a meta-solution. Does it make sense to make a migration that migrates that data? Migration that inserts rows into the new migrations versions table based on the old one.

**Comment by goetas** [comment]
That should be already automatically handled by https://github.com/doctrine/migrations/blob/c8ccaeb98bcc118b4657b854802e5202f04f40dc/lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php#L204 

if is not the case, there might be a bug. Did you already try it?

**Comment by emodric** [comment]
I had no problems with keeping migrations data. I did have to run `doctrine:migrations:sync-metadata-storage` to upgrade to the new storage format, though.

On a related note, @goetas would it be possible to run `doctrine:migrations:sync-metadata-storage` command automatically the first time `doctrine:migrations:migrate` command is ran after upgrading to v3?

**Comment by goetas** [comment]
> On a related note, @goetas would it be possible to run doctrine:migrations:sync-metadata-storage command automatically the first time doctrine:migrations:migrate command is ran after upgrading to v3?

That should have been already the case.
Will double check it.

**Comment by pamil** [comment]
I'll try whether I can reproduce it.

**Comment by pamil** [comment]
It was mostly my fault, I deleted `table_name` configuration option instead of setting its equivalent in the new configuration. After configuring migrations to use the same table, migration works, but only after running `sync-metadata-storage`:

<img width="1680" alt="Screenshot 2020-04-22 at 12 17 15" src="https://user-images.githubusercontent.com/1897953/79970622-79fe7680-8493-11ea-9823-77d64bce3bfd.png">

**Comment by goetas** [comment]
Will be fixed in https://github.com/doctrine/migrations/pull/973
