### ISSUE TITLE
Execute do:mi:mi multiple times in command

### ISSUE THREAD

**Issue by CharlyPoppins** [doctrine/migrations#982]
|    Q        |   A
|------------ | -----
| Version     | v1.3.2

### Support Question

Hello, I'm trying to execute do:mi:mi multiple times in a command like this :
````
$command = $this->getApplication()->find('doctrine:migration:status');
...
$arguments = new ArrayInput(
    [
        '--em' => 'customer',
        '--no-interaction' => true,
    ]
);
foreach ($connections as $connection) {
    ...
    $returnCode = $command->run($arguments, $output);
}
````

then in the second occurrence  of the loop I've got an exception :
````
In MigrationException.php line 44:
Migration version 20191231183319 already registered with class Doctrine\DBAL\Migrations\Version
````
because migration files are already registred, any clue on how to avoid this ?

**Comment by goetas** [comment]
That is an interesting way to use the migrations library.

The version 1.x is not maintained anymore.
I would suggest to migrate to 2.x, or better to 3.0 (currently in beta, but a stable release is expected in few weeks) and see if the problem is still there.

**Comment by goetas** [comment]
In doctrine 3.0  dependency injection is used, thus you are able to instantiate a custom version of any doctrine command with its dedicated dependencies.

See https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/custom-integration.html#custom-integration  (as you can see `$dependencyFactory` is passed to each command, you can repeat that in a loop and create a `DependencyFactory` with a different connection each time)
