### ISSUE TITLE
Got Error on try update doctrine from 2.2.* to 3.*

### ISSUE THREAD

**Issue by ShikiDev** [doctrine/migrations#995]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.2.1 to 3.0.0.

#### Summary

I have got an issue after update my project from 2.2.1 to 3.0.0.

#### Previous behavior

Previous version work well. 

#### Current behavior
I've got this error on deploy:
`Script cache:clear returned with error code 1 
 In ArrayNode.php line 319: Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection ", "custom_template", "em", "factories", "migrations", "migrations_paths",   
"organize_migrations", "services", "storage". `

Fix my problem by rollback to version 2.2.1

#### How to reproduce

Update project with doctrine 2.2.1 to a new version.

**Comment by BlackWiCKED** [comment]
I faced the same problem. You need to update your configuration files, follow the instructions in [Upgrade to 3.0](https://github.com/doctrine/migrations/blob/master/UPGRADE.md#upgrade-to-30)

**Comment by greg0ire** [comment]
Closing since it's by definition OK to get BC-breaks when upgrading to a new major version.
