### ISSUE TITLE
Missing SQL output during migration

### ISSUE THREAD

**Issue by bobvandevijver** [doctrine/migrations#996]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | not really, it was available in 2.x
| RFC         | no
| BC Break    | no

#### Summary

I'm missing the SQL output when running the migrate command, and I do not see any option to enable it (except for writing to file). This is something that was available earlier, and I would like to see it return if possible.

**Comment by goetas** [comment]
as explained in the upgrade notes (https://github.com/doctrine/migrations/blob/master/UPGRADE.md#console), you can use the `-vvv` option

**Comment by bobvandevijver** [comment]
Okay, I missed that, thanks. 

Would it be an idea to add this to the help of the command itself? Because that was actually the place I was looking for the option, and the upgrade notes will probably not be read by people using this in new projects. In my opinion the default description for `-v|vv|vvv, --verbose` does not reflect that it is actually used for this functionality.

**Comment by goetas** [comment]
that can be a nice thing to do. 
Do you want to send a pull request for it?
