### ISSUE TITLE
--query-time option requires -vv as well

### ISSUE THREAD

**Issue by bobvandevijver** [doctrine/migrations#998]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.0

#### Summary

The `--query-time` command option requires `-vv` to be also supplied in order to produce output.

#### Current behavior

See summary.

#### How to reproduce

```
bobvandevijver@webdev:/var/www/dev$ bin/console doctrine:migrations:migrate --no-interaction --query-time
[notice] Migrating up to DoctrineMigrations\Version20200616155007
[notice] finished in 60.1ms, used 22M memory, 1 migrations executed, 1 sql queries

bobvandevijver@webdev:/var/www/dev$ bin/console doctrine:migrations:migrate --no-interaction prev
[notice] Migrating down to 0
[notice] finished in 51.4ms, used 22M memory, 1 migrations executed, 1 sql queries

bobvandevijver@webdev:/var/www/dev$ bin/console doctrine:migrations:migrate --no-interaction --query-time -vv
[notice] Migrating up to DoctrineMigrations\Version20200616155007
[info] ++ migrating DoctrineMigrations\Version20200616155007 (Add entity)
[debug] CREATE TABLE <snip>
[debug] 26.2ms
[info] Migration DoctrineMigrations\Version20200616155007 migrated (took 55.2ms, used 22M memory)
[notice] finished in 66.2ms, used 22M memory, 1 migrations executed, 1 sql queries
```
#### Expected behavior

The `--query-time` option should output the query time even when `-vv` is not supplied. 

I would propose to add some descriptive text with the query time, instead of only showing the milliseconds (cause, what is the time for?). For example: `[debug] Previous query took 26.2ms`.

**Comment by goetas** [comment]
Solved in https://github.com/doctrine/migrations/pull/1010
